// MAMAEXPERT — nama-data-2.js
// Arab Perempuan (150), Melayu (100), Turkish (80), Persian (80), Urdu (60)

const namaArabPerempuan = [
  { nama: "Aisyah", makna: "Yang hidup, yang ceria dan bahagia", asal: "Nama isteri Nabi Muhammad S.A.W", popular: true },
  { nama: "Fatimah", makna: "Yang menahan diri, yang suci", asal: "Nama puteri Nabi Muhammad S.A.W", popular: true },
  { nama: "Khadijah", makna: "Yang lahir pramatang, yang mulia", asal: "Nama isteri pertama Nabi Muhammad S.A.W", popular: true },
  { nama: "Zahra", makna: "Bunga, yang bersinar, yang cerah", asal: "Gelaran Saidatina Fatimah Al-Zahra", popular: true },
  { nama: "Maryam", makna: "Yang taat beribadah, bunga", asal: "Nama ibu Nabi Isa A.S", popular: true },
  { nama: "Nur", makna: "Cahaya, sinar yang menerangi", asal: "Dari Al-Quran surah An-Nur" },
  { nama: "Sara", makna: "Yang mulia, puteri", asal: "Nama isteri Nabi Ibrahim A.S" },
  { nama: "Hana", makna: "Kebahagiaan, kesenangan", asal: "Dari kata Arab hana bermaksud gembira" },
  { nama: "Laila", makna: "Malam yang indah, cantik seperti malam", asal: "Nama popular dalam sastera Arab" },
  { nama: "Amira", makna: "Puteri, pemimpin wanita", asal: "Bentuk feminin dari amir" },
  { nama: "Zainab", makna: "Pokok yang harum, yang mulia", asal: "Nama puteri dan isteri Nabi Muhammad S.A.W" },
  { nama: "Nadia", makna: "Yang memanggil, yang lembut", asal: "Dari kata Arab nada bermaksud embun" },
  { nama: "Insyirah", makna: "Kelapangan dada, ketenangan", asal: "Dari Al-Quran surah Al-Insyirah" },
  { nama: "Wardah", makna: "Bunga ros, yang cantik", asal: "Dari kata Arab ward bermaksud bunga ros" },
  { nama: "Sofea", makna: "Yang suci, yang jernih hatinya", asal: "Dari kata Arab safa bermaksud jernih" },
  { nama: "Iman", makna: "Kepercayaan, keimanan kepada Allah", asal: "Dari kata Arab amana bermaksud percaya" },
  { nama: "Yasmin", makna: "Bunga jasmine yang harum", asal: "Nama bunga yang harum dalam bahasa Arab" },
  { nama: "Rania", makna: "Yang memandang dengan penuh kasih", asal: "Dari kata Arab rana bermaksud memandang" },
  { nama: "Alya", makna: "Yang tinggi, yang mulia", asal: "Dari kata Arab ala bermaksud tinggi" },
  { nama: "Humaira", makna: "Yang kemerahan, yang cantik", asal: "Gelaran Nabi kepada Saidatina Aisyah R.A" },
  { nama: "Farhana", makna: "Yang gembira, yang bahagia", asal: "Dari kata Arab farah bermaksud gembira" },
  { nama: "Qistina", makna: "Yang adil, keadilan", asal: "Dari kata Arab qist bermaksud keadilan" },
  { nama: "Irdina", makna: "Agamaku, keislamanku", asal: "Dari kata Arab din bermaksud agama" },
  { nama: "Razan", makna: "Yang tenang dan bijaksana", asal: "Dari kata Arab razana bermaksud tenang" },
  { nama: "Izzati", makna: "Kemuliaanku, kehormatanku", asal: "Dari kata Arab izza bermaksud kemuliaan" },
  { nama: "Bilqis", makna: "Ratu yang bijaksana", asal: "Nama Ratu Saba yang disebutkan dalam Al-Quran" },
  { nama: "Mardhiah", makna: "Yang diredhai Allah", asal: "Dari kata radha bermaksud redha" },
  { nama: "Nadhirah", makna: "Yang berseri, yang cantik bercahaya", asal: "Dari kata Arab nadhara bermaksud bersinar" },
  { nama: "Batrisyia", makna: "Yang mulia, yang terhormat", asal: "Variasi Arab bermaksud mulia" },
  { nama: "Sumayyah", makna: "Yang tinggi, yang mulia", asal: "Nama syahidah pertama dalam Islam" },
  { nama: "Safiyyah", makna: "Yang suci hati, yang terpilih", asal: "Nama isteri Nabi Muhammad S.A.W" },
  { nama: "Ruqayyah", makna: "Yang naik, yang meningkat darjat", asal: "Nama puteri Nabi Muhammad S.A.W" },
  { nama: "Hafsah", makna: "Singa betina, yang kuat", asal: "Nama isteri Nabi Muhammad S.A.W" },
  { nama: "Raihana", makna: "Bunga yang harum, tumbuhan wangi", asal: "Nama sahabiyah Nabi Muhammad S.A.W" },
  { nama: "Zulaikha", makna: "Yang cantik jelita", asal: "Nama wanita cantik dalam kisah Nabi Yusuf A.S" },
  { nama: "Asiah", makna: "Yang mengubati, yang menyembuhkan", asal: "Nama isteri Firaun yang beriman kepada Allah" },
  { nama: "Hajar", makna: "Batu, yang tabah dan kuat", asal: "Nama isteri Nabi Ibrahim A.S" },
  { nama: "Fatin", makna: "Yang memikat, yang menarik hati", asal: "Dari kata fatana bermaksud memikat" },
  { nama: "Najwa", makna: "Bisikan, kata-kata rahsia yang mesra", asal: "Dari kata naja bermaksud berbisik" },
  { nama: "Hanin", makna: "Kerinduan, yang rindu", asal: "Dari kata hanna bermaksud rindu" },
  { nama: "Zafirah", makna: "Yang berjaya, yang menang", asal: "Dari kata zafara bermaksud menang" },
  { nama: "Zahirah", makna: "Yang bersinar, yang jelas", asal: "Dari kata zahara bermaksud bersinar" },
  { nama: "Khairunnisa", makna: "Sebaik-baik wanita", asal: "Gabungan khair dan nisa bermaksud wanita terbaik" },
  { nama: "Salsabila", makna: "Mata air syurga yang jernih", asal: "Disebutkan dalam Al-Quran surah Al-Insan" },
  { nama: "Raudhah", makna: "Taman bunga yang indah", asal: "Dari kata rawdha bermaksud taman syurga" },
  { nama: "Malak", makna: "Malaikat, yang cantik bagai malaikat", asal: "Dari kata malaka bermaksud malaikat" },
  { nama: "Jannah", makna: "Syurga, taman yang indah", asal: "Dari kata janna bermaksud taman syurga" },
  { nama: "Dhuha", makna: "Waktu pagi yang cerah", asal: "Dari Al-Quran surah Ad-Dhuha" },
  { nama: "Farah", makna: "Kegembiraan, kebahagiaan", asal: "Dari kata farih bermaksud gembira" },
  { nama: "Huda", makna: "Petunjuk, hidayah yang benar", asal: "Dari kata hada bermaksud memberi petunjuk" },
  { nama: "Ibtisam", makna: "Senyuman, yang selalu tersenyum", asal: "Dari kata ibtasama bermaksud tersenyum" },
  { nama: "Marwa", makna: "Bukit Marwa, batu putih yang bersih", asal: "Nama bukit suci dalam Islam" },
  { nama: "Naimah", makna: "Yang mewah, yang hidup senang", asal: "Dari kata naama bermaksud nikmat" },
  { nama: "Qamar", makna: "Bulan yang indah dan bercahaya", asal: "Dari kata qamar bermaksud bulan" },
  { nama: "Sharifah", makna: "Yang mulia, berketurunan mulia", asal: "Dari kata sharafa bermaksud mulia" },
  { nama: "Tasneem", makna: "Mata air syurga yang tertinggi", asal: "Disebutkan dalam Al-Quran surah Al-Mutaffifin" },
  { nama: "Umaimah", makna: "Ibu kecil yang disayangi", asal: "Nama sahabiyah Nabi Muhammad S.A.W" },
  { nama: "Widad", makna: "Cinta, kasih sayang yang tulus", asal: "Dari kata wadda bermaksud mencintai" },
  { nama: "Yusra", makna: "Kemudahan, yang mudah urusannya", asal: "Dari Al-Quran surah Al-Insyirah" },
  { nama: "Amirah", makna: "Puteri raja, pemimpin wanita", asal: "Bentuk feminin dari amir" },
  { nama: "Bashirah", makna: "Pembawa berita gembira", asal: "Dari kata bashshara bermaksud khabar baik" },
  { nama: "Dalilah", makna: "Petunjuk, pemandu yang benar", asal: "Dari kata dalla bermaksud menunjuk" },
  { nama: "Fitriah", makna: "Yang fitrah, yang suci semula jadi", asal: "Dari kata fitra bermaksud kejadian asal" },
  { nama: "Habibah", makna: "Yang dicintai, kekasih", asal: "Dari kata habba bermaksud mencintai" },
  { nama: "Inaayah", makna: "Perhatian, penjagaan Allah", asal: "Dari kata anaya bermaksud penjagaan" },
  { nama: "Jumaanah", makna: "Permata mutiara, yang berharga", asal: "Dari kata jumana bermaksud mutiara" },
  { nama: "Karimah", makna: "Yang mulia hati, yang pemurah", asal: "Dari kata karuma bermaksud mulia" },
  { nama: "Latifah", makna: "Yang lembut, yang halus budi", asal: "Salah satu nama Allah Al-Latif" },
  { nama: "Maisarah", makna: "Kemudahan, yang serba senang", asal: "Dari kata yasara bermaksud mudah" },
  { nama: "Nabilah", makna: "Yang mulia dan cerdas", asal: "Dari kata nabala bermaksud mulia" },
  { nama: "Qotrunnada", makna: "Titisan embun, yang segar", asal: "Dari kata qatr bermaksud titisan" },
  { nama: "Ramlah", makna: "Pasir, yang lembut", asal: "Nama isteri Nabi Muhammad S.A.W" },
  { nama: "Sabihah", makna: "Yang cantik, yang bersinar pagi", asal: "Dari kata sabaha bermaksud cantik" },
  { nama: "Thurayya", makna: "Bintang Pleiades, yang bersinar", asal: "Nama kumpulan bintang dalam bahasa Arab" },
  { nama: "Wadiah", makna: "Yang damai, yang lemah lembut", asal: "Dari kata wadi bermaksud lembah yang tenang" },
  { nama: "Afifah", makna: "Yang suci, yang menjaga kehormatan diri", asal: "Dari kata affa bermaksud suci" },
  { nama: "Barakah", makna: "Keberkatan, yang penuh berkat", asal: "Dari kata baraka bermaksud berkat" },
  { nama: "Fadilah", makna: "Yang mulia, yang mempunyai kelebihan", asal: "Dari kata fadl bermaksud kelebihan" },
  { nama: "Ghaliyah", makna: "Yang mahal, yang berharga", asal: "Dari kata ghala bermaksud mahal" },
  { nama: "Haleemah", makna: "Yang sabar, yang lemah lembut", asal: "Nama ibu susuan Nabi Muhammad S.A.W" },
  { nama: "Inas", makna: "Keramahan, kemesraan", asal: "Dari kata anisa bermaksud mesra" },
  { nama: "Khalidah", makna: "Yang kekal, yang abadi", asal: "Dari kata khalada bermaksud kekal" },
  { nama: "Lubna", makna: "Pokok getah yang manis", asal: "Nama pokok yang menghasilkan resin wangi" },
  { nama: "Manar", makna: "Cahaya, menara cahaya", asal: "Dari kata nara bermaksud bercahaya" },
  { nama: "Nadiyah", makna: "Yang lembut, yang berembun", asal: "Dari kata nada bermaksud embun" },
  { nama: "Raniyah", makna: "Yang memandang dengan mata indah", asal: "Dari kata rana bermaksud memandang" },
  { nama: "Sidratul", makna: "Pokok sidr di langit tertinggi", asal: "Dari Al-Quran bermaksud pokok di langit tinggi" },
  { nama: "Ghazalah", makna: "Rusa betina, yang lembut dan anggun", asal: "Dari kata ghazal bermaksud rusa" },
  { nama: "Kifah", makna: "Yang berjuang, yang gigih", asal: "Dari kata kafaha bermaksud berjuang" },
  { nama: "Lamia", makna: "Yang bersinar, yang berkilauan", asal: "Dari kata lama bermaksud bersinar" },
  { nama: "Rawiyah", makna: "Perawi hadis, yang meriwayat", asal: "Dari kata rawa bermaksud meriwayatkan" },
  { nama: "Tabassumah", makna: "Yang tersenyum, yang ceria", asal: "Dari kata tabassum bermaksud senyuman" },
  { nama: "Bushra", makna: "Berita gembira, khabar baik", asal: "Dari kata bashshara bermaksud khabar baik" },
  { nama: "Dariyah", makna: "Yang mengetahui, yang bijak", asal: "Dari kata daraya bermaksud mengetahui" },
  { nama: "Ezdihar", makna: "Yang berkembang, yang maju", asal: "Dari kata izdahara bermaksud berkembang" },
  { nama: "Ghina", makna: "Kekayaan, yang merasa cukup", asal: "Dari kata ghany bermaksud kaya" },
  { nama: "Nusaybah", makna: "Yang berketurunan mulia", asal: "Nama sahabiyah yang terkenal dalam Islam" },
  { nama: "Zaynab", makna: "Pokok yang harum, yang indah", asal: "Variasi dari Zainab" },
  { nama: "Aabidah", makna: "Yang tekun beribadah", asal: "Dari kata abada bermaksud beribadah" },
  { nama: "Aanisah", makna: "Yang mesra, yang ramah", asal: "Dari kata anisa bermaksud mesra" },
  { nama: "Aasiyah", makna: "Yang mengubati, yang menyembuhkan", asal: "Variasi dari Asiah" },
  { nama: "Abeer", makna: "Wangian, yang harum baunya", asal: "Dari kata abara bermaksud harum" },
  { nama: "Abeer", makna: "Wangian, yang harum", asal: "Dari kata abara bermaksud harum" },
  { nama: "Abla", makna: "Yang cantik tubuhnya, yang sempurna", asal: "Dari kata abila bermaksud cantik" },
  { nama: "Adibah", makna: "Yang bersopan, yang beradab", asal: "Dari kata aduba bermaksud beradab" },
  { nama: "Afrah", makna: "Kegembiraan-kegembiraan", asal: "Dari kata farih bermaksud gembira" },
  { nama: "Ahlam", makna: "Mimpi-mimpi yang indah", asal: "Dari kata hulm bermaksud mimpi" },
  { nama: "Aisha", makna: "Yang hidup, yang ceria", asal: "Variasi dari Aisyah" },
  { nama: "Ajwa", makna: "Jenis kurma terbaik dari Madinah", asal: "Nama kurma yang disebutkan dalam hadis" },
  { nama: "Ala", makna: "Ketinggian, kemuliaan", asal: "Dari kata ala bermaksud tinggi" },
  { nama: "Alhan", makna: "Melodi, nyanyian yang indah", asal: "Dari kata lahn bermaksud melodi" },
  { nama: "Almas", makna: "Berlian, permata yang berharga", asal: "Dari bahasa Parsi bermaksud berlian" },
  { nama: "Almaza", makna: "Permata yang berharga", asal: "Dari bahasa Arab bermaksud berlian" },
  { nama: "Ama", makna: "Hamba wanita, yang khidmat", asal: "Dari kata ama bermaksud hamba wanita" },
  { nama: "Amal", makna: "Harapan, cita-cita yang mulia", asal: "Dari kata amala bermaksud berharap" },
  { nama: "Amani", makna: "Harapan-harapan, cita-cita", asal: "Dari kata tamanna bermaksud berharap" },
  { nama: "Amatus", makna: "Hamba Allah yang wanita", asal: "Dari kata ama bermaksud hamba wanita" },
  { nama: "Ambara", makna: "Wangian yang harum, ambar", asal: "Dari kata ambar bermaksud wangian" },
  { nama: "Ambar", makna: "Ambar, wangian yang mahal", asal: "Nama wangian yang berharga dalam Arab" },
  { nama: "Ameena", makna: "Yang amanah, yang boleh dipercayai", asal: "Nama ibu Nabi Muhammad S.A.W" },
  { nama: "Amina", makna: "Yang amanah, yang aman", asal: "Nama ibu Nabi Muhammad S.A.W" },
  { nama: "Aminah", makna: "Yang amanah, yang dipercayai", asal: "Nama ibu Nabi Muhammad S.A.W" },
  { nama: "Amira", makna: "Puteri, pemimpin wanita", asal: "Bentuk feminin dari amir" },
  { nama: "Anbar", makna: "Wangian ambar, yang harum", asal: "Dari kata anbar bermaksud wangian mahal" },
  { nama: "Andalib", makna: "Burung bulbul, yang merdu suaranya", asal: "Dari kata andalib bermaksud bulbul" },
  { nama: "Anisa", makna: "Yang mesra, yang ramah", asal: "Dari kata anisa bermaksud mesra" },
  { nama: "Aqilah", makna: "Yang berakal, yang bijak", asal: "Dari kata aql bermaksud akal" },
  { nama: "Arij", makna: "Wangian yang semerbak", asal: "Dari kata ariha bermaksud harum" },
  { nama: "Arwa", makna: "Kambing gunung betina", asal: "Nama sahabiyah Nabi yang terkenal" },
  { nama: "Arzu", makna: "Keinginan, harapan", asal: "Dari bahasa Turki bermaksud harapan" },
  { nama: "Asma", makna: "Nama-nama, yang mulia", asal: "Nama puteri Abu Bakar As-Siddiq" },
  { nama: "Asmaa", makna: "Yang mulia, yang tinggi darjat", asal: "Variasi dari Asma" },
  { nama: "Atika", makna: "Yang cantik, yang muda", asal: "Dari kata atiqa bermaksud cantik dan muda" },
  { nama: "Atikah", makna: "Yang bebas, yang mulia", asal: "Dari kata atiqa bermaksud bebas" },
  { nama: "Awatif", makna: "Perasaan-perasaan yang indah", asal: "Dari kata atafa bermaksud perasaan" },
  { nama: "Ayla", makna: "Cahaya bulan, yang bercahaya", asal: "Dari bahasa Turki bermaksud cahaya bulan" },
  { nama: "Aysha", makna: "Yang hidup, yang ceria", asal: "Variasi dari Aisyah" },
  { nama: "Azizah", makna: "Yang mulia, yang perkasa", asal: "Dari kata aziza bermaksud mulia dan perkasa" },
  { nama: "Azyza", makna: "Yang paling mulia", asal: "Variasi dari Azizah" },
];

const namaMelayuLelaki = [
  { nama: "Putra", makna: "Anak lelaki yang mulia", asal: "Dari bahasa Sanskrit" },
  { nama: "Wira", makna: "Pahlawan, hero yang gagah", asal: "Kata asli Melayu" },
  { nama: "Arif", makna: "Yang bijaksana dan berpengetahuan", asal: "Dari bahasa Arab arafa" },
  { nama: "Haziq", makna: "Yang cerdik dan mahir", asal: "Dari bahasa Arab hazaqa" },
  { nama: "Azri", makna: "Penolong, yang membantu", asal: "Variasi Melayu dari nama Arab" },
  { nama: "Fakhrul", makna: "Kebanggaan yang terbaik", asal: "Dari bahasa Arab fakhr" },
  { nama: "Syahmi", makna: "Yang mulia, yang terhormat", asal: "Variasi Melayu bermaksud mulia" },
  { nama: "Azfar", makna: "Yang paling berjaya", asal: "Dari kata Arab zafara" },
  { nama: "Hairul", makna: "Kebaikan yang terbaik", asal: "Variasi dari khairul" },
  { nama: "Syafwan", makna: "Yang bersih, yang jernih", asal: "Dari bahasa Arab safwa" },
  { nama: "Farhan", makna: "Yang gembira, yang bahagia", asal: "Dari kata Arab farih" },
  { nama: "Ridzuan", makna: "Keredhaan Allah", asal: "Variasi Melayu dari ridhwan" },
  { nama: "Syazwan", makna: "Yang harum, yang wangi", asal: "Variasi Melayu" },
  { nama: "Amsyar", makna: "Yang paling mulia", asal: "Variasi dari ashraf" },
  { nama: "Azmil", makna: "Yang bercita-cita tinggi", asal: "Dari kata Arab azm" },
  { nama: "Nadzmi", makna: "Yang tersusun rapi", asal: "Dari kata Arab nazm" },
  { nama: "Shafwan", makna: "Yang bersih hati, yang murni", asal: "Nama sahabat Nabi" },
  { nama: "Syuaib", makna: "Yang membara, yang bersemangat", asal: "Nama Nabi Syuaib A.S" },
  { nama: "Hafizuddin", makna: "Penjaga agama", asal: "Gabungan hafiz dan din" },
  { nama: "Zulhilmi", makna: "Yang memiliki kelembutan", asal: "Gabungan zul dan hilm" },
  { nama: "Mukhriz", makna: "Yang berjaya, yang lulus cemerlang", asal: "Dari kata Arab akhraja" },
  { nama: "Syahrul", makna: "Bulan yang terkenal", asal: "Dari kata Arab syahr" },
  { nama: "Hambali", makna: "Yang bersemangat", asal: "Dinisbahkan kepada Imam Ahmad" },
  { nama: "Zulfahmi", makna: "Yang memiliki kefahaman mendalam", asal: "Gabungan zul dan fahm" },
  { nama: "Akhyar", makna: "Yang paling baik, terpilih", asal: "Dari kata Arab khayr" },
  { nama: "Mukhlis", makna: "Yang ikhlas, yang tulus hati", asal: "Dari kata Arab akhlasa" },
  { nama: "Syahiran", makna: "Yang masyhur dengan kebaikan", asal: "Dari kata Arab syahara" },
  { nama: "Faizul", makna: "Kemenangan, yang berjaya", asal: "Dari kata Arab faza" },
  { nama: "Hairuddin", makna: "Kebaikan agama", asal: "Gabungan khayr dan din" },
  { nama: "Helmi", makna: "Yang lemah lembut, yang sabar", asal: "Dari kata Arab hilm" },
  { nama: "Hazwani", makna: "Yang berhati-hati, yang teliti", asal: "Dari kata Arab hazm" },
  { nama: "Izwan", makna: "Yang mulia, yang terhormat", asal: "Variasi Melayu bermaksud kemuliaan" },
  { nama: "Khairul Anwar", makna: "Cahaya yang terbaik", asal: "Gabungan khairul dan anwar" },
  { nama: "Luqmanul Hakim", makna: "Luqman yang bijaksana", asal: "Dari Al-Quran surah Luqman" },
  { nama: "Mahzan", makna: "Yang bersedih, yang penyayang", asal: "Dari kata Arab huzn bermaksud sedih" },
  { nama: "Mohd Azlan", makna: "Muhammad yang kukuh", asal: "Gabungan Muhammad dan azlan" },
  { nama: "Nasrawi", makna: "Yang memberi kemenangan", asal: "Dari kata Arab nasr" },
  { nama: "Norfazli", makna: "Cahaya kelebihan", asal: "Gabungan nur dan fadli" },
  { nama: "Norhaidi", makna: "Cahaya petunjuk", asal: "Gabungan nur dan hadi" },
  { nama: "Norhalim", makna: "Cahaya yang lemah lembut", asal: "Gabungan nur dan halim" },
  { nama: "Shahrul Nizam", makna: "Bulan yang tersusun", asal: "Gabungan syahrul dan nizam" },
  { nama: "Shamsul", makna: "Matahari, yang bersinar", asal: "Dari kata Arab syams" },
  { nama: "Shamsuri", makna: "Matahari yang membantu", asal: "Dari kata Arab syams" },
  { nama: "Sobri", makna: "Yang sabar, yang tabah", asal: "Variasi dari Sabri" },
  { nama: "Solehan", makna: "Yang soleh, yang baik", asal: "Dari kata Arab salaha" },
  { nama: "Suffian", makna: "Yang cepat, yang tangkas", asal: "Variasi dari Sufian" },
  { nama: "Syafruddin", makna: "Syafaat agama", asal: "Gabungan syafa dan din" },
  { nama: "Syamsul Bahri", makna: "Matahari laut", asal: "Gabungan syams dan bahr" },
  { nama: "Termizi", makna: "Yang berkaitan ilmu hadis", asal: "Dinisbahkan kepada Imam At-Tirmizi" },
  { nama: "Uthman Hakim", makna: "Khalifah yang bijaksana", asal: "Gabungan Uthman dan hakim" },
  { nama: "Wan Mohd", makna: "Putera Muhammad", asal: "Wan adalah gelaran bangsawan Melayu" },
  { nama: "Yahyaa", makna: "Yang hidup", asal: "Variasi dari Yahya" },
  { nama: "Yazwan", makna: "Yang bertambah baik", asal: "Variasi Melayu bermaksud kemajuan" },
  { nama: "Zairul", makna: "Pelawat yang mulia", asal: "Dari kata Arab zara bermaksud melawat" },
  { nama: "Zaki", makna: "Yang suci, yang bijak", asal: "Dari kata Arab zaka" },
  { nama: "Zakri", makna: "Ingatanku, zikirku", asal: "Variasi dari Zikri" },
  { nama: "Zamri", makna: "Rakan seperjuangan", asal: "Dari kata Arab zamala" },
  { nama: "Zayyad", makna: "Yang bertambah baik", asal: "Variasi dari Ziyad" },
  { nama: "Zharif", makna: "Yang bijak, yang peramah", asal: "Dari kata Arab zarafa" },
  { nama: "Zhafri", makna: "Yang berjaya", asal: "Dari kata Arab zafara" },
  { nama: "Ziyaul Haq", makna: "Cahaya kebenaran", asal: "Gabungan dhiya dan haq" },
  { nama: "Zubir", makna: "Yang kuat", asal: "Variasi dari Zubair" },
];

const namaMelayuPerempuan = [
  { nama: "Puteri", makna: "Anak perempuan yang mulia, puteri raja", asal: "Kata Melayu asli dari Sanskrit putri" },
  { nama: "Melati", makna: "Bunga melati yang harum dan putih", asal: "Nama bunga Melayu yang melambangkan kesucian" },
  { nama: "Mutiara", makna: "Permata laut yang berharga dan cantik", asal: "Kata Melayu asli untuk permata mutiara" },
  { nama: "Cahaya", makna: "Sinar yang menerangi, cahaya kehidupan", asal: "Kata Melayu asli bermaksud sinar" },
  { nama: "Indah", makna: "Yang cantik dan elok", asal: "Kata Melayu asli bermaksud cantik" },
  { nama: "Anisa", makna: "Yang ramah, yang menyenangkan", asal: "Dari bahasa Arab anisa" },
  { nama: "Suraya", makna: "Bintang Pleiades, bintang yang cantik", asal: "Nama kumpulan bintang dalam bahasa Arab" },
  { nama: "Liyana", makna: "Yang lembut, yang mudah bergaul", asal: "Dari bahasa Arab layn" },
  { nama: "Delima", makna: "Buah delima yang berharga", asal: "Buah yang disebutkan dalam Al-Quran" },
  { nama: "Arina", makna: "Yang damai, yang tenang", asal: "Variasi Melayu bermaksud kedamaian" },
  { nama: "Syahirah", makna: "Yang terkenal dengan kebaikan", asal: "Dari kata Arab syuhrah" },
  { nama: "Nurfatehah", makna: "Cahaya pembuka, cahaya permulaan", asal: "Gabungan nur dan fatehah" },
  { nama: "Syakirah", makna: "Yang bersyukur, yang berterima kasih", asal: "Dari kata syakara" },
  { nama: "Izzah", makna: "Kemuliaan, kehormatan yang tinggi", asal: "Dari kata izza" },
  { nama: "Syazana", makna: "Yang harum, yang wangi baunya", asal: "Variasi Melayu" },
  { nama: "Nurain", makna: "Dua cahaya, yang bersinar ganda", asal: "Gabungan nur dan ain" },
  { nama: "Hafizah", makna: "Penghafaz Al-Quran, yang memelihara", asal: "Bentuk feminin dari hafiz" },
  { nama: "Arisya", makna: "Yang mulia, yang terhormat", asal: "Variasi Melayu bermaksud kemuliaan" },
  { nama: "Damia", makna: "Yang tenang, yang damai", asal: "Variasi Melayu bermaksud ketenangan" },
  { nama: "Safwanah", makna: "Yang jernih hati, yang bersih", asal: "Dari kata Arab safwa" },
  { nama: "Thahirah", makna: "Yang suci, yang bersih", asal: "Dari kata Arab tahara" },
  { nama: "Nurliana", makna: "Cahaya yang lembut dan indah", asal: "Gabungan nur dan liana" },
  { nama: "Khairiah", makna: "Yang baik, penuh kebaikan", asal: "Dari kata khayr" },
  { nama: "Ilyana", makna: "Cahaya yang murni dan lembut", asal: "Variasi Melayu bermaksud cahaya lembut" },
  { nama: "Faizah", makna: "Yang berjaya, yang menang", asal: "Dari kata Arab faza" },
  { nama: "Eryna", makna: "Yang damai, yang tenang jiwa", asal: "Variasi Melayu bermaksud ketenangan" },
  { nama: "Diyanah", makna: "Agama, yang taat beragama", asal: "Dari kata Arab din" },
  { nama: "Balqis", makna: "Ratu yang bijaksana", asal: "Variasi Melayu dari Bilqis" },
  { nama: "Azwani", makna: "Yang cantik, yang elok parasnya", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Nabilah", makna: "Yang mulia, yang cerdas", asal: "Dari kata nabala" },
  { nama: "Maisarah", makna: "Kemudahan, yang serba senang", asal: "Dari kata yasara" },
  { nama: "Jihanah", makna: "Arah yang benar, dunia yang indah", asal: "Dari kata jiha" },
  { nama: "Huwaina", makna: "Yang kecil dan lembut", asal: "Variasi Melayu dari kata Arab" },
  { nama: "Ghaziah", makna: "Yang berjuang, yang gigih", asal: "Dari kata Arab ghaza" },
  { nama: "Sulalah", makna: "Keturunan yang baik, yang terpilih", asal: "Dari kata Arab sulalah" },
  { nama: "Rabitah", makna: "Pertautan hati, yang terikat kasih", asal: "Dari kata Arab rabata" },
  { nama: "Qurratul", makna: "Penyejuk mata, penyeri hati", asal: "Dari kata Arab qurrat" },
  { nama: "Norhaliza", makna: "Cahaya yang bersinar indah", asal: "Gabungan nur dan haliza" },
  { nama: "Norhayati", makna: "Cahaya kehidupan", asal: "Gabungan nur dan hayat" },
  { nama: "Norhidayah", makna: "Cahaya petunjuk", asal: "Gabungan nur dan hidayah" },
  { nama: "Norjannah", makna: "Cahaya syurga", asal: "Gabungan nur dan jannah" },
  { nama: "Norlia", makna: "Cahaya yang indah", asal: "Gabungan nur dan lia" },
  { nama: "Normah", makna: "Cahaya kemuliaan", asal: "Gabungan nur dan mahabbah" },
  { nama: "Norshahida", makna: "Cahaya syahidah", asal: "Gabungan nur dan syahidah" },
  { nama: "Norshazwani", makna: "Cahaya yang harum", asal: "Gabungan nur dan syazwani" },
  { nama: "Norzahra", makna: "Cahaya bunga", asal: "Gabungan nur dan zahra" },
  { nama: "Norzalifah", makna: "Cahaya yang dekat", asal: "Gabungan nur dan zalifah" },
  { nama: "Norzuraidah", makna: "Cahaya bunga-bungaan", asal: "Gabungan nur dan zuraidah" },
  { nama: "Nursabrina", makna: "Cahaya kesabaran", asal: "Gabungan nur dan sabrina" },
  { nama: "Nursyafiqah", makna: "Cahaya kasih sayang", asal: "Gabungan nur dan syafiqah" },
  { nama: "Nursyahirah", makna: "Cahaya yang terkenal", asal: "Gabungan nur dan syahirah" },
  { nama: "Nursyamimi", makna: "Cahaya angin lembut", asal: "Gabungan nur dan syamimi" },
  { nama: "Nursyazwani", makna: "Cahaya yang harum", asal: "Gabungan nur dan syazwani" },
  { nama: "Nurul", makna: "Cahaya yang terang", asal: "Dari kata Arab nur bermaksud cahaya" },
  { nama: "Nurul Izzah", makna: "Cahaya kemuliaan", asal: "Gabungan nurul dan izzah" },
  { nama: "Nurul Ain", makna: "Cahaya mata, penyeri hati", asal: "Gabungan nurul dan ain" },
  { nama: "Nurul Huda", makna: "Cahaya petunjuk", asal: "Gabungan nurul dan huda" },
  { nama: "Nurul Iman", makna: "Cahaya keimanan", asal: "Gabungan nurul dan iman" },
  { nama: "Siti", makna: "Puan, nyonya yang mulia", asal: "Gelaran wanita mulia dalam tradisi Melayu" },
  { nama: "Siti Aishah", makna: "Puan yang hidup dan ceria", asal: "Gabungan Siti dan Aishah" },
  { nama: "Siti Fatimah", makna: "Puan yang suci", asal: "Gabungan Siti dan Fatimah" },
  { nama: "Wan Nur", makna: "Cahaya puteri", asal: "Wan adalah gelaran bangsawan Melayu" },
  { nama: "Wanie", makna: "Yang cantik, yang menarik", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Wardina", makna: "Bunga ros yang indah", asal: "Dari kata Arab ward" },
  { nama: "Wawa", makna: "Yang comel, yang menggemaskan", asal: "Nama panggilan Melayu yang comel" },
  { nama: "Yuzlinda", makna: "Yang elok dan indah", asal: "Variasi Melayu bermaksud keindahan" },
  { nama: "Zaidatulakmar", makna: "Tambahan bintang yang cantik", asal: "Gabungan zaidat dan akmar" },
  { nama: "Zaleha", makna: "Yang cantik, yang indah rupa", asal: "Dari kata Arab zulaikha" },
  { nama: "Zaliha", makna: "Yang baik, yang solehah", asal: "Variasi dari Zaleha" },
  { nama: "Zalina", makna: "Yang cantik dan bersinar", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Zamila", makna: "Rakan sejawat, yang setia", asal: "Dari kata Arab zamala" },
  { nama: "Zarith", makna: "Bintang yang bersinar", asal: "Variasi Melayu bermaksud bintang" },
  { nama: "Zasya", makna: "Yang manis, yang comel", asal: "Variasi Melayu bermaksud kelucuan" },
  { nama: "Zaty", makna: "Diri, yang bermakna diri sendiri", asal: "Dari kata Arab dzat bermaksud diri" },
  { nama: "Ziana", makna: "Yang bersinar, yang cantik", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Ziyana", makna: "Hiasan, yang menghiasi", asal: "Dari kata Arab zayn bermaksud hiasan" },
  { nama: "Zulaikha", makna: "Yang cantik jelita", asal: "Dari kisah Nabi Yusuf A.S" },
  { nama: "Zulaika", makna: "Yang cantik jelita", asal: "Variasi dari Zulaikha" },
  { nama: "Zuraida", makna: "Bunga-bungaan yang indah", asal: "Dari kata Arab zuhur bermaksud bunga" },
  { nama: "Zuraidah", makna: "Bunga-bungaan, yang cantik", asal: "Variasi dari Zuraida" },
];

const namaTurkishLelaki = [
  { nama: "Aras", makna: "Sungai yang mengalir bebas", asal: "Nama sungai di Turki, melambangkan kebebasan" },
  { nama: "Arslan", makna: "Singa, simbol keberanian", asal: "Nama Turki bermaksud singa" },
  { nama: "Aslan", makna: "Singa yang gagah perkasa", asal: "Dari bahasa Turki bermaksud singa" },
  { nama: "Ayaz", makna: "Angin malam yang sejuk", asal: "Nama Turki bermaksud angin sejuk malam" },
  { nama: "Aybars", makna: "Singa bulan", asal: "Gabungan ay (bulan) dan bars (harimau)" },
  { nama: "Aydin", makna: "Yang bercahaya, yang terang", asal: "Dari bahasa Turki bermaksud terang" },
  { nama: "Aykut", makna: "Bertuah seperti bulan", asal: "Gabungan ay (bulan) dan kut (bertuah)" },
  { nama: "Bahadir", makna: "Yang berani, pahlawan", asal: "Nama Turki bermaksud pahlawan gagah berani" },
  { nama: "Baran", makna: "Hujan yang subur", asal: "Nama Turki bermaksud hujan" },
  { nama: "Baris", makna: "Keamanan, yang damai", asal: "Dari bahasa Turki bermaksud aman" },
  { nama: "Batuhan", makna: "Pemimpin yang berani", asal: "Dari bahasa Turki bermaksud pemimpin gagah" },
  { nama: "Bayram", makna: "Perayaan, yang gembira", asal: "Nama Turki bermaksud hari raya" },
  { nama: "Bekir", makna: "Yang pertama, yang awal", asal: "Variasi Turki dari Abu Bakar" },
  { nama: "Bilal", makna: "Kelembapan, yang menyejukkan", asal: "Nama Arab yang popular di Turki" },
  { nama: "Birkan", makna: "Pemimpin yang tunggal", asal: "Dari bahasa Turki bermaksud pemimpin" },
  { nama: "Burak", makna: "Kilat, yang pantas", asal: "Nama haiwan yang dibawa Nabi semasa Isra Mikraj" },
  { nama: "Can", makna: "Jiwa, yang bersemangat", asal: "Dari bahasa Turki bermaksud jiwa" },
  { nama: "Caner", makna: "Jiwa yang pemberani", asal: "Gabungan can dan er bermaksud jiwa pemberani" },
  { nama: "Cemal", makna: "Keindahan, yang cantik", asal: "Variasi Turki dari Jamal" },
  { nama: "Cengiz", makna: "Dunia, yang menguasai dunia", asal: "Nama Turki bermaksud penguasa" },
  { nama: "Deniz", makna: "Laut, yang luas", asal: "Nama Turki bermaksud laut" },
  { nama: "Demir", makna: "Besi, yang kuat dan teguh", asal: "Nama Turki bermaksud besi" },
  { nama: "Doruk", makna: "Puncak, yang paling tinggi", asal: "Nama Turki bermaksud puncak gunung" },
  { nama: "Duman", makna: "Asap, yang misterius", asal: "Nama Turki bermaksud asap" },
  { nama: "Ediz", makna: "Yang tinggi, yang mulia", asal: "Nama Turki bermaksud ketinggian" },
  { nama: "Ege", makna: "Laut Aegean, yang luas", asal: "Nama Turki dari nama laut Aegean" },
  { nama: "Emre", makna: "Saudara, yang setia", asal: "Nama Turki bermaksud saudara" },
  { nama: "Emir", makna: "Pemimpin, putera", asal: "Variasi Turki dari Amir" },
  { nama: "Enes", makna: "Yang mesra, yang ramah", asal: "Variasi Turki dari Anas" },
  { nama: "Engin", makna: "Yang luas, yang dalam", asal: "Nama Turki bermaksud luas dan dalam" },
  { nama: "Ercan", makna: "Jiwa yang kuat", asal: "Gabungan er (kuat) dan can (jiwa)" },
  { nama: "Erdem", makna: "Kebajikan, yang berbudi luhur", asal: "Nama Turki bermaksud kebajikan" },
  { nama: "Erhan", makna: "Khan yang kuat", asal: "Gabungan er (kuat) dan han (khan)" },
  { nama: "Erkan", makna: "Darah pahlawan", asal: "Gabungan er (pahlawan) dan kan (darah)" },
  { nama: "Erman", makna: "Orang yang kuat", asal: "Dari bahasa Turki bermaksud kuat" },
  { nama: "Firat", makna: "Sungai Euphrates, yang mengalir", asal: "Nama sungai suci dalam sejarah Islam" },
  { nama: "Furkan", makna: "Pembeza, yang membeza", asal: "Variasi Turki dari Furqan" },
  { nama: "Gokhan", makna: "Khan dari langit", asal: "Gabungan gok (langit) dan han (khan)" },
  { nama: "Hamit", makna: "Yang memuji, yang bersyukur", asal: "Variasi Turki dari Hamid" },
  { nama: "Hasan", makna: "Yang tampan, yang baik", asal: "Variasi Turki dari Hassan" },
  { nama: "Huseyin", makna: "Yang cantik, yang baik sekali", asal: "Variasi Turki dari Hussain" },
  { nama: "Ibrahim", makna: "Bapa kepada banyak bangsa", asal: "Variasi Turki dari Ibrahim" },
  { nama: "Ilhan", makna: "Pemimpin rakyat", asal: "Dari bahasa Turki bermaksud pemimpin" },
  { nama: "Ilker", makna: "Lelaki pertama, yang asal", asal: "Dari bahasa Turki bermaksud pertama" },
  { nama: "Ismail", makna: "Allah mendengar", asal: "Variasi Turki dari Ismail" },
  { nama: "Kadir", makna: "Yang berkuasa", asal: "Variasi Turki dari Qadir" },
  { nama: "Kemal", makna: "Kesempurnaan, yang sempurna", asal: "Variasi Turki dari Kamal" },
  { nama: "Kerem", makna: "Kemurahan hati, yang murah hati", asal: "Dari bahasa Turki bermaksud kemurahan" },
  { nama: "Korkut", makna: "Yang menakutkan musuh", asal: "Nama Turki bermaksud yang disegani" },
  { nama: "Kuzey", makna: "Utara, yang dari utara", asal: "Nama Turki bermaksud arah utara" },
  { nama: "Mahmut", makna: "Yang terpuji", asal: "Variasi Turki dari Mahmud" },
  { nama: "Mert", makna: "Yang berani, yang laki-laki sejati", asal: "Nama Turki bermaksud berani" },
  { nama: "Musa", makna: "Diselamatkan dari air", asal: "Variasi Turki dari Musa" },
  { nama: "Mustafa", makna: "Yang terpilih", asal: "Variasi Turki dari Mustafa" },
  { nama: "Oguzhan", makna: "Khan suku Oguz", asal: "Dari nama puak Turki yang terkenal" },
  { nama: "Onur", makna: "Kehormatan, yang terhormat", asal: "Nama Turki bermaksud kehormatan" },
  { nama: "Osman", makna: "Yang lembut, yang penyayang", asal: "Variasi Turki dari Uthman" },
  { nama: "Ozgur", makna: "Yang bebas, yang merdeka", asal: "Nama Turki bermaksud kebebasan" },
  { nama: "Recep", makna: "Bulan Rejab yang mulia", asal: "Variasi Turki dari Rajab" },
  { nama: "Selim", makna: "Yang sejahtera, yang sihat", asal: "Variasi Turki dari Salim" },
  { nama: "Serhat", makna: "Sempadan, yang menjaga sempadan", asal: "Nama Turki bermaksud sempadan" },
  { nama: "Sinan", makna: "Lembing, yang tajam", asal: "Nama arkitek terkenal Turki Uthmaniyah" },
  { nama: "Suleyman", makna: "Yang sejahtera", asal: "Variasi Turki dari Sulaiman" },
  { nama: "Taner", makna: "Fajar yang kebiruan", asal: "Nama Turki bermaksud warna fajar" },
  { nama: "Tarkan", makna: "Khan yang pantas", asal: "Dari bahasa Turki bermaksud pemimpin pantas" },
  { nama: "Tayfur", makna: "Yang membara semangat", asal: "Nama Turki bermaksud semangat" },
  { nama: "Timur", makna: "Besi, yang kuat", asal: "Nama Turki bermaksud besi" },
  { nama: "Tolga", makna: "Topi perang, yang bersedia", asal: "Nama Turki bermaksud perisai" },
  { nama: "Tunahan", makna: "Khan yang berkuasa", asal: "Gabungan tuna dan han bermaksud berkuasa" },
  { nama: "Ufuk", makna: "Ufuk, cakrawala yang luas", asal: "Nama Turki bermaksud cakrawala" },
  { nama: "Umut", makna: "Harapan, yang penuh harapan", asal: "Nama Turki bermaksud harapan" },
  { nama: "Utku", makna: "Kemenangan, yang menang", asal: "Nama Turki bermaksud kemenangan" },
  { nama: "Volkan", makna: "Gunung berapi, yang penuh semangat", asal: "Nama Turki bermaksud gunung berapi" },
  { nama: "Yavuz", makna: "Yang berani, yang kuat", asal: "Nama Turki bermaksud pemberani" },
  { nama: "Yilmaz", makna: "Yang tidak mengalah", asal: "Nama Turki bermaksud pantang menyerah" },
  { nama: "Yusuf", makna: "Allah menambah", asal: "Variasi Turki dari Yusuf" },
  { nama: "Zeki", makna: "Yang cerdas, yang pintar", asal: "Dari bahasa Turki bermaksud cerdas" },
];

const namaTurkishPerempuan = [
  { nama: "Aylin", makna: "Bulan yang bersinar", asal: "Dari bahasa Turki ay (bulan) dan lin (yang bersinar)" },
  { nama: "Aysel", makna: "Banjir cahaya bulan", asal: "Gabungan ay (bulan) dan sel (banjir)" },
  { nama: "Aysegul", makna: "Bunga cahaya bulan", asal: "Gabungan ayse dan gul (bunga)" },
  { nama: "Aytac", makna: "Mahkota bulan", asal: "Gabungan ay (bulan) dan tac (mahkota)" },
  { nama: "Bahar", makna: "Musim bunga, yang segar", asal: "Nama Turki bermaksud musim bunga" },
  { nama: "Banu", makna: "Puteri, yang mulia", asal: "Nama Turki bermaksud puteri" },
  { nama: "Bedia", makna: "Yang menakjubkan, yang cantik", asal: "Dari bahasa Arab badi bermaksud ajaib" },
  { nama: "Belkis", makna: "Ratu Saba yang bijaksana", asal: "Variasi Turki dari Bilqis" },
  { nama: "Berin", makna: "Yang tinggi, yang mulia", asal: "Nama Turki bermaksud ketinggian" },
  { nama: "Berrak", makna: "Yang jernih, yang bening", asal: "Nama Turki bermaksud jernih" },
  { nama: "Beyza", makna: "Yang putih bersih", asal: "Dari bahasa Arab baydha bermaksud putih" },
  { nama: "Birgul", makna: "Satu bunga yang istimewa", asal: "Gabungan bir (satu) dan gul (bunga)" },
  { nama: "Busra", makna: "Berita gembira", asal: "Variasi Turki dari Bushra" },
  { nama: "Ceylan", makna: "Rusa yang anggun", asal: "Nama Turki bermaksud rusa betina" },
  { nama: "Ceyda", makna: "Yang cantik seperti rusa", asal: "Dari bahasa Turki bermaksud anggun" },
  { nama: "Ceren", makna: "Rusa muda yang cantik", asal: "Nama Turki bermaksud rusa muda" },
  { nama: "Damla", makna: "Titisan air, yang segar", asal: "Nama Turki bermaksud titisan" },
  { nama: "Defne", makna: "Pokok laurel, yang mulia", asal: "Nama Turki dari pokok laurel Greek" },
  { nama: "Derya", makna: "Laut yang luas", asal: "Nama Turki bermaksud lautan" },
  { nama: "Dilan", makna: "Hati yang penuh kasih", asal: "Dari bahasa Kurdi bermaksud hati" },
  { nama: "Dua", makna: "Doa, permohonan kepada Allah", asal: "Dari bahasa Arab bermaksud doa" },
  { nama: "Ebrar", makna: "Yang salih, yang taat", asal: "Dari bahasa Arab abrar bermaksud orang salih" },
  { nama: "Ece", makna: "Ratu, yang memerintah", asal: "Nama Turki bermaksud ratu" },
  { nama: "Ecrin", makna: "Pahala yang besar", asal: "Dari bahasa Arab ajr bermaksud pahala" },
  { nama: "Elif", makna: "Huruf pertama Arab, yang anggun", asal: "Dari huruf alif bermaksud yang pertama" },
  { nama: "Elmas", makna: "Berlian, yang berharga", asal: "Dari bahasa Turki bermaksud berlian" },
  { nama: "Emine", makna: "Yang amanah, yang dipercayai", asal: "Variasi Turki dari Aminah" },
  { nama: "Esma", makna: "Nama-nama, yang mulia", asal: "Variasi Turki dari Asma" },
  { nama: "Esra", makna: "Perjalanan malam, Isra", asal: "Dari bahasa Arab bermaksud perjalanan malam" },
  { nama: "Fadime", makna: "Yang menahan diri, yang suci", asal: "Variasi Turki dari Fatimah" },
  { nama: "Fatma", makna: "Yang menahan diri, yang suci", asal: "Variasi Turki dari Fatimah" },
  { nama: "Feray", makna: "Bulan yang menerangi", asal: "Gabungan fer (cahaya) dan ay (bulan)" },
  { nama: "Filiz", makna: "Tunas, yang baru tumbuh", asal: "Nama Turki bermaksud tunas muda" },
  { nama: "Gonca", makna: "Bunga yang belum mekar", asal: "Nama Turki bermaksud kuntum bunga" },
  { nama: "Gozde", makna: "Yang disayangi, yang istimewa", asal: "Nama Turki bermaksud yang dikasihi" },
  { nama: "Gul", makna: "Bunga ros, yang cantik", asal: "Nama Turki bermaksud bunga ros" },
  { nama: "Gulbahar", makna: "Bunga musim bunga", asal: "Gabungan gul (bunga) dan bahar (musim bunga)" },
  { nama: "Gulden", makna: "Bunga emas", asal: "Gabungan gul (bunga) dan den (emas)" },
  { nama: "Gulnaz", makna: "Bunga yang manja", asal: "Gabungan gul (bunga) dan naz (manja)" },
  { nama: "Gulsum", makna: "Muka yang seperti bunga", asal: "Variasi Turki dari Ummu Kultsum" },
  { nama: "Gunes", makna: "Matahari, yang bersinar", asal: "Nama Turki bermaksud matahari" },
  { nama: "Hale", makna: "Lingkaran bulan, yang bercahaya", asal: "Nama Turki bermaksud lingkaran cahaya" },
  { nama: "Hatice", makna: "Yang lahir pramatang, yang mulia", asal: "Variasi Turki dari Khadijah" },
  { nama: "Havva", makna: "Ibu kepada manusia, Hawa", asal: "Variasi Turki dari Hawa, isteri Nabi Adam" },
  { nama: "Hazal", makna: "Daun-daun musim gugur", asal: "Nama Turki bermaksud daun gugur" },
  { nama: "Hilal", makna: "Bulan sabit, yang baru bermula", asal: "Dari bahasa Arab bermaksud bulan sabit" },
  { nama: "Inci", makna: "Mutiara, yang berharga", asal: "Nama Turki bermaksud mutiara" },
  { nama: "Ipek", makna: "Sutera, yang lembut", asal: "Nama Turki bermaksud kain sutera" },
  { nama: "Irem", makna: "Taman syurga", asal: "Dari bahasa Arab iram bermaksud taman syurga" },
  { nama: "Kader", makna: "Takdir Allah", asal: "Dari bahasa Arab qadar bermaksud takdir" },
];

const namaPersianLelaki = [
  { nama: "Arman", makna: "Impian, cita-cita yang mulia", asal: "Dari bahasa Parsi bermaksud impian dan harapan" },
  { nama: "Arash", makna: "Anak panah yang laju", asal: "Nama wira Parsi yang terkenal" },
  { nama: "Ardalan", makna: "Yang tinggi dan mulia", asal: "Dari bahasa Parsi bermaksud kemuliaan" },
  { nama: "Aref", makna: "Yang bijaksana, yang mengenal", asal: "Variasi Parsi dari Arif" },
  { nama: "Arvin", makna: "Sahabat rakyat", asal: "Dari bahasa Parsi bermaksud sahabat" },
  { nama: "Azad", makna: "Yang bebas, yang merdeka", asal: "Dari bahasa Parsi bermaksud merdeka" },
  { nama: "Bavar", makna: "Kepercayaan, keyakinan", asal: "Dari bahasa Parsi bermaksud percaya" },
  { nama: "Behnam", makna: "Yang terkenal baik, berwibawa", asal: "Gabungan beh (baik) dan nam (nama)" },
  { nama: "Behrad", makna: "Hadiah kebaikan", asal: "Gabungan beh (baik) dan rad (pemberi)" },
  { nama: "Behrooz", makna: "Yang bertuah, yang bahagia", asal: "Gabungan beh (baik) dan rooz (hari)" },
  { nama: "Borzou", makna: "Yang tinggi, yang mulia", asal: "Dari bahasa Parsi bermaksud tinggi" },
  { nama: "Cyrus", makna: "Matahari, yang bersinar", asal: "Nama raja Parsi yang agung" },
  { nama: "Dara", makna: "Yang memegang kekayaan", asal: "Dari bahasa Parsi bermaksud kaya" },
  { nama: "Dariush", makna: "Yang memiliki kebaikan", asal: "Nama raja Parsi yang masyhur" },
  { nama: "Danesh", makna: "Pengetahuan, ilmu", asal: "Dari bahasa Parsi bermaksud ilmu pengetahuan" },
  { nama: "Dawood", makna: "Yang dicintai", asal: "Variasi Parsi dari Daud" },
  { nama: "Ershad", makna: "Petunjuk, bimbingan", asal: "Dari bahasa Arab irsyad bermaksud petunjuk" },
  { nama: "Esfahani", makna: "Dari Isfahan, yang berkebudayaan", asal: "Dinisbahkan kepada kota Isfahan" },
  { nama: "Farhad", makna: "Kegembiraan, yang bahagia", asal: "Nama wira Parsi yang terkenal" },
  { nama: "Farzan", makna: "Yang bijak, yang cerdas", asal: "Dari bahasa Parsi bermaksud bijaksana" },
  { nama: "Fazel", makna: "Yang bermoral, yang mulia", asal: "Variasi Parsi dari Fadil" },
  { nama: "Firouz", makna: "Yang menang, yang berjaya", asal: "Dari bahasa Parsi bermaksud kemenangan" },
  { nama: "Ghassan", makna: "Belia, yang muda bersemangat", asal: "Dari bahasa Arab bermaksud masa muda" },
  { nama: "Hamid", makna: "Yang memuji Allah, yang terpuji", asal: "Dari bahasa Arab hamida bermaksud memuji" },
  { nama: "Hamed", makna: "Yang bersyukur, yang memuji", asal: "Variasi Parsi dari Hamid" },
  { nama: "Hassan", makna: "Yang tampan, yang baik", asal: "Variasi Parsi dari Hassan" },
  { nama: "Hormuz", makna: "Yang penuh cahaya", asal: "Nama dewa Parsi bermaksud cahaya" },
  { nama: "Iraj", makna: "Putera raja Parsi", asal: "Nama putera raja dalam mitologi Parsi" },
  { nama: "Jamshid", makna: "Raja yang bersinar seperti matahari", asal: "Nama raja Parsi purba yang terkenal" },
  { nama: "Javad", makna: "Yang pemurah, yang dermawan", asal: "Dari bahasa Arab jawad bermaksud pemurah" },
  { nama: "Kamran", makna: "Yang berjaya, yang bahagia", asal: "Dari bahasa Parsi bermaksud kejayaan" },
  { nama: "Kasra", makna: "Raja yang memecahkan", asal: "Nama raja Parsi bermaksud memecah batas" },
  { nama: "Kaveh", makna: "Pahlawan yang berani", asal: "Nama wira Parsi yang terkenal" },
  { nama: "Kian", makna: "Raja, yang berkuasa", asal: "Dari bahasa Parsi bermaksud raja purba" },
  { nama: "Kiyan", makna: "Yang bijaksana dan berani", asal: "Dari bahasa Parsi bermaksud kerajaan" },
  { nama: "Kouros", makna: "Pemuda, anak raja", asal: "Dari bahasa Parsi bermaksud pemuda" },
  { nama: "Mahdi", makna: "Yang mendapat hidayah", asal: "Variasi Parsi dari Mahdi" },
  { nama: "Majid", makna: "Yang mulia, yang agung", asal: "Dari bahasa Arab majada bermaksud mulia" },
  { nama: "Mehdi", makna: "Yang mendapat petunjuk", asal: "Variasi Parsi dari Mahdi" },
  { nama: "Mehran", makna: "Yang penuh kasih", asal: "Dari bahasa Parsi bermaksud kasih sayang" },
  { nama: "Milad", makna: "Kelahiran, yang dilahirkan", asal: "Dari bahasa Parsi bermaksud hari lahir" },
  { nama: "Mohsen", makna: "Yang berbuat baik, yang dermawan", asal: "Dari bahasa Arab ahsana bermaksud berbuat baik" },
  { nama: "Navid", makna: "Berita gembira, yang membahagiakan", asal: "Dari bahasa Parsi bermaksud khabar baik" },
  { nama: "Nima", makna: "Yang baik, yang adil", asal: "Dari bahasa Parsi bermaksud setengah bulan" },
  { nama: "Omid", makna: "Harapan, yang penuh harapan", asal: "Dari bahasa Parsi bermaksud harapan" },
  { nama: "Parviz", makna: "Yang bertuah, yang berjaya", asal: "Dari bahasa Parsi bermaksud kemenangan" },
  { nama: "Payam", makna: "Pesanan, yang membawa khabar", asal: "Dari bahasa Parsi bermaksud pesanan" },
  { nama: "Ramin", makna: "Yang gembira, yang bahagia", asal: "Nama wira Parsi dalam puisi klasik" },
  { nama: "Rashid", makna: "Yang mendapat petunjuk", asal: "Variasi Parsi dari Rashid" },
  { nama: "Reza", makna: "Keredhaan, yang redha", asal: "Dari bahasa Arab ridha bermaksud redha" },
  { nama: "Rostam", makna: "Yang kuat seperti batu", asal: "Nama pahlawan Parsi yang paling terkenal" },
  { nama: "Saeed", makna: "Yang bahagia, yang bertuah", asal: "Dari bahasa Arab said bermaksud bahagia" },
  { nama: "Saman", makna: "Yang mendamaikan", asal: "Dari bahasa Parsi bermaksud keamanan" },
  { nama: "Sanjar", makna: "Yang menikam pedang", asal: "Nama sultan Seljuk yang terkenal" },
  { nama: "Sasan", makna: "Pengasas kerajaan Sassanid", asal: "Nama raja Parsi purba" },
  { nama: "Shaheen", makna: "Helang, yang gagah dan bebas", asal: "Dari bahasa Parsi bermaksud helang diraja" },
  { nama: "Shahram", makna: "Raja yang terkenal", asal: "Gabungan shah (raja) dan ram (terkenal)" },
  { nama: "Shahriyar", makna: "Raja kota, yang memerintah", asal: "Dari bahasa Parsi shah (raja) dan yar (kota)" },
  { nama: "Siamak", makna: "Anak hitam, yang kuat", asal: "Nama putera raja dalam mitologi Parsi" },
  { nama: "Sina", makna: "Yang berpengetahuan", asal: "Dinisbahkan kepada Ibnu Sina, ahli perubatan" },
  { nama: "Siroos", makna: "Yang bersinar seperti matahari", asal: "Variasi Parsi dari Cyrus" },
  { nama: "Sobhan", makna: "Maha Suci", asal: "Variasi Parsi dari Subhan" },
  { nama: "Sohrab", makna: "Air merah, yang berani", asal: "Nama wira dalam epik Parsi Shahnameh" },
  { nama: "Taher", makna: "Yang suci, yang bersih", asal: "Variasi Parsi dari Tahir" },
  { nama: "Vahid", makna: "Yang tunggal, yang unik", asal: "Variasi Parsi dari Wahid" },
  { nama: "Vali", makna: "Wali, yang menjaga", asal: "Dari bahasa Arab wali bermaksud pelindung" },
  { nama: "Yashar", makna: "Yang hidup, yang terus hidup", asal: "Dari bahasa Parsi bermaksud kehidupan" },
  { nama: "Yousef", makna: "Allah menambah", asal: "Variasi Parsi dari Yusuf" },
  { nama: "Zafar", makna: "Kemenangan, yang berjaya", asal: "Variasi Parsi dari Zafar" },
  { nama: "Zaid", makna: "Pertumbuhan, yang bertambah", asal: "Variasi Parsi dari Zaid" },
];

const namaPersianPerempuan = [
  { nama: "Afshan", makna: "Yang menaburkan cahaya", asal: "Dari bahasa Parsi bermaksud menaburkan" },
  { nama: "Afsoon", makna: "Mantera, yang mempesona", asal: "Dari bahasa Parsi bermaksud pesona" },
  { nama: "Anahita", makna: "Dewi air yang suci", asal: "Dari bahasa Parsi bermaksud yang suci" },
  { nama: "Andisha", makna: "Fikiran, yang berfikir", asal: "Dari bahasa Parsi bermaksud pemikiran" },
  { nama: "Ariana", makna: "Yang mulia, dari tanah Arya", asal: "Dari bahasa Parsi bermaksud kemuliaan" },
  { nama: "Asal", makna: "Madu, yang manis", asal: "Dari bahasa Parsi bermaksud madu" },
  { nama: "Azar", makna: "Api, yang bersemangat", asal: "Dari bahasa Parsi bermaksud api" },
  { nama: "Azin", makna: "Perhiasan, yang menghias", asal: "Dari bahasa Parsi bermaksud perhiasan" },
  { nama: "Azita", makna: "Yang bebas, yang merdeka", asal: "Dari bahasa Parsi bermaksud kebebasan" },
  { nama: "Baran", makna: "Hujan yang subur", asal: "Dari bahasa Parsi bermaksud hujan" },
  { nama: "Bahar", makna: "Musim bunga, yang segar", asal: "Dari bahasa Parsi bermaksud musim bunga" },
  { nama: "Banoo", makna: "Puteri, yang mulia", asal: "Dari bahasa Parsi bermaksud puteri" },
  { nama: "Darya", makna: "Laut yang luas", asal: "Dari bahasa Parsi bermaksud lautan" },
  { nama: "Dina", makna: "Yang lembut, yang setia", asal: "Dari bahasa Parsi bermaksud agama" },
  { nama: "Elnaz", makna: "Yang manja dan paling cantik", asal: "Dari bahasa Parsi el (paling) dan naz (manja)" },
  { nama: "Farnaz", makna: "Keanggunan yang mulia", asal: "Gabungan far (mulia) dan naz (anggun)" },
  { nama: "Farangis", makna: "Puteri Perancis, yang cantik", asal: "Nama wira perempuan dalam epik Parsi" },
  { nama: "Fariba", makna: "Yang mempesona", asal: "Dari bahasa Parsi bermaksud pesona" },
  { nama: "Farideh", makna: "Yang unik, yang tiada tandingan", asal: "Dari bahasa Arab farid bermaksud unik" },
  { nama: "Farzaneh", makna: "Yang bijak, yang cerdas", asal: "Dari bahasa Parsi bermaksud bijaksana" },
  { nama: "Fereshteh", makna: "Malaikat, yang cantik", asal: "Dari bahasa Parsi bermaksud malaikat" },
  { nama: "Forough", makna: "Cahaya, yang bercahaya", asal: "Dari bahasa Parsi bermaksud cahaya" },
  { nama: "Golnaz", makna: "Bunga yang manja", asal: "Gabungan gol (bunga) dan naz (manja)" },
  { nama: "Golnessa", makna: "Bunga wanita", asal: "Gabungan gol (bunga) dan nessa (wanita)" },
  { nama: "Golroo", makna: "Muka seperti bunga", asal: "Gabungan gol (bunga) dan roo (muka)" },
  { nama: "Gulab", makna: "Bunga ros, air ros", asal: "Dari bahasa Parsi bermaksud bunga ros" },
  { nama: "Hamideh", makna: "Yang dipuji, yang terpuji", asal: "Dari bahasa Arab hamida bermaksud memuji" },
  { nama: "Hanieh", makna: "Yang bahagia, yang menyenangkan", asal: "Dari bahasa Arab hana bermaksud gembira" },
  { nama: "Hoda", makna: "Petunjuk yang benar", asal: "Variasi Parsi dari Huda" },
  { nama: "Iran", makna: "Tanah orang Arya", asal: "Dari bahasa Parsi bermaksud negeri Arya" },
  { nama: "Katayoun", makna: "Ratu, yang memerintah", asal: "Nama ratu dalam mitologi Parsi" },
  { nama: "Kimia", makna: "Emas, yang berharga", asal: "Dari bahasa Parsi bermaksud kimia dan emas" },
  { nama: "Laleh", makna: "Bunga tulip, yang cantik", asal: "Dari bahasa Parsi bermaksud bunga tulip" },
  { nama: "Layla", makna: "Malam yang indah", asal: "Variasi Parsi dari Laila" },
  { nama: "Leili", makna: "Malam, yang misterius", asal: "Variasi Parsi dari Laila" },
  { nama: "Lida", makna: "Yang manis, yang cantik", asal: "Dari bahasa Parsi bermaksud manis" },
  { nama: "Mahin", makna: "Seperti bulan", asal: "Dari bahasa Parsi bermaksud bulan" },
  { nama: "Mahsa", makna: "Seperti bulan", asal: "Dari bahasa Parsi mah (bulan) dan sa (seperti)" },
  { nama: "Mahshid", makna: "Cahaya bulan", asal: "Dari bahasa Parsi mah (bulan) dan shid (cahaya)" },
  { nama: "Mandana", makna: "Yang kekal", asal: "Nama ratu Parsi bermaksud yang kekal" },
  { nama: "Maryam", makna: "Yang taat beribadah", asal: "Variasi Parsi dari Maryam" },
  { nama: "Masoumeh", makna: "Yang suci, yang terpelihara", asal: "Dari bahasa Arab maasuma bermaksud suci" },
  { nama: "Mitra", makna: "Kasih sayang, yang menyayangi", asal: "Dari bahasa Parsi bermaksud kasih sayang" },
  { nama: "Mojgan", makna: "Bulu mata, yang menawan", asal: "Dari bahasa Parsi bermaksud bulu mata cantik" },
  { nama: "Morvarid", makna: "Mutiara, yang berharga", asal: "Dari bahasa Parsi bermaksud mutiara" },
  { nama: "Nasrin", makna: "Bunga ros liar", asal: "Dari bahasa Parsi bermaksud bunga ros liar" },
  { nama: "Nazanin", makna: "Yang manja, yang dikasihi", asal: "Dari bahasa Parsi bermaksud yang disayang" },
  { nama: "Nazgol", makna: "Bunga yang manja", asal: "Gabungan naz (manja) dan gol (bunga)" },
  { nama: "Niloofar", makna: "Bunga teratai biru", asal: "Dari bahasa Parsi bermaksud teratai" },
  { nama: "Niloufar", makna: "Bunga teratai yang indah", asal: "Variasi dari Niloofar" },
  { nama: "Noushin", makna: "Yang manis, yang sedap", asal: "Dari bahasa Parsi bermaksud manis" },
  { nama: "Parisa", makna: "Seperti pari, sangat cantik", asal: "Dari bahasa Parsi pari (peri) dan sa (seperti)" },
  { nama: "Parvaneh", makna: "Rama-rama, yang bebas", asal: "Dari bahasa Parsi bermaksud rama-rama" },
  { nama: "Pouran", makna: "Puteri raja Parsi", asal: "Nama ratu Parsi yang memerintah" },
  { nama: "Raha", makna: "Yang bebas, yang damai", asal: "Dari bahasa Parsi bermaksud damai" },
  { nama: "Romina", makna: "Yang cantik dari Rom", asal: "Dari bahasa Parsi bermaksud cantik" },
  { nama: "Roya", makna: "Impian, yang indah seperti mimpi", asal: "Dari bahasa Parsi bermaksud mimpi indah" },
  { nama: "Sanaz", makna: "Penuh keanggunan", asal: "Dari bahasa Parsi bermaksud anggun" },
  { nama: "Setareh", makna: "Bintang, yang bersinar", asal: "Dari bahasa Parsi bermaksud bintang" },
  { nama: "Shahrzad", makna: "Puteri kota, yang mulia", asal: "Nama dalam Seribu Satu Malam" },
  { nama: "Shirin", makna: "Yang manis, yang menyenangkan", asal: "Dari bahasa Parsi bermaksud manis" },
  { nama: "Shohreh", makna: "Yang terkenal, yang masyhur", asal: "Dari bahasa Parsi bermaksud masyhur" },
  { nama: "Sima", makna: "Wajah, yang cantik wajahnya", asal: "Dari bahasa Parsi bermaksud wajah" },
  { nama: "Sogand", makna: "Sumpah, yang berjanji setia", asal: "Dari bahasa Parsi bermaksud janji" },
  { nama: "Soheila", makna: "Mudah, yang menyenangkan", asal: "Dari bahasa Arab suhail bermaksud mudah" },
  { nama: "Tara", makna: "Bintang, yang bersinar", asal: "Dari bahasa Sanskrit bermaksud bintang" },
  { nama: "Yasna", makna: "Pujian, yang memuji", asal: "Dari bahasa Parsi bermaksud doa dan pujian" },
  { nama: "Zahra", makna: "Bunga, yang bersinar", asal: "Variasi Parsi dari Zahra" },
];

const namaUrduLelaki = [
  { nama: "Aarav", makna: "Bunyi damai, yang tenang", asal: "Dari bahasa Sanskrit bermaksud ketenangan" },
  { nama: "Adeel", makna: "Yang adil, yang saksama", asal: "Dari bahasa Arab adala bermaksud adil" },
  { nama: "Aftab", makna: "Matahari, yang bersinar terang", asal: "Dari bahasa Parsi bermaksud matahari" },
  { nama: "Ahad", makna: "Yang Esa, yang tunggal", asal: "Salah satu nama Allah Al-Ahad" },
  { nama: "Ahsan", makna: "Yang terbaik, yang paling cantik", asal: "Dari bahasa Arab husn bermaksud keindahan" },
  { nama: "Ahtesham", makna: "Kebesaran, yang berwibawa", asal: "Dari bahasa Arab bermaksud wibawa" },
  { nama: "Akbar", makna: "Yang terbesar, yang paling agung", asal: "Dari bahasa Arab akbara bermaksud besar" },
  { nama: "Akhtar", makna: "Bintang, yang bersinar", asal: "Dari bahasa Parsi bermaksud bintang" },
  { nama: "Aleem", makna: "Yang berpengetahuan", asal: "Salah satu nama Allah Al-Alim" },
  { nama: "Altaf", makna: "Kelembutanhati, yang penyayang", asal: "Dari bahasa Arab ltf bermaksud lembut" },
  { nama: "Amjad", makna: "Yang paling mulia", asal: "Dari bahasa Arab majd bermaksud mulia" },
  { nama: "Ammar", makna: "Yang makmur, yang membina", asal: "Nama sahabat Nabi yang terkenal" },
  { nama: "Arbab", makna: "Tuan, yang memerintah", asal: "Dari bahasa Urdu bermaksud tuan" },
  { nama: "Arsalan", makna: "Singa, yang berani", asal: "Dari bahasa Parsi bermaksud singa" },
  { nama: "Asad", makna: "Singa, yang gagah", asal: "Dari bahasa Arab bermaksud singa" },
  { nama: "Asim", makna: "Yang menjaga, yang melindungi", asal: "Dari bahasa Arab asama bermaksud menjaga" },
  { nama: "Atif", makna: "Yang penyayang, yang baik hati", asal: "Dari bahasa Arab atafa bermaksud penyayang" },
  { nama: "Awais", makna: "Yang setia, wali yang terkenal", asal: "Nama wali Allah yang terkenal" },
  { nama: "Ayaan", makna: "Hadiah Allah, yang diberkati", asal: "Dari bahasa Arab bermaksud anugerah" },
  { nama: "Azan", makna: "Seruan solat, yang memanggil", asal: "Dari bahasa Arab azan bermaksud seruan" },
  { nama: "Azlan", makna: "Singa, yang gagah perkasa", asal: "Dari bahasa Melayu bermaksud singa" },
  { nama: "Babar", makna: "Singa, yang kuat", asal: "Nama raja Mughal yang terkenal" },
  { nama: "Basit", makna: "Yang meluaskan, yang memberi nikmat", asal: "Salah satu nama Allah Al-Basit" },
  { nama: "Bilal", makna: "Muazzin pertama Islam", asal: "Nama sahabat Nabi yang terkenal" },
  { nama: "Danyal", makna: "Allah adalah hakimku", asal: "Variasi Urdu dari Danial" },
  { nama: "Dawood", makna: "Yang dicintai", asal: "Variasi Urdu dari Daud" },
  { nama: "Ehsan", makna: "Kebaikan, berbuat baik", asal: "Variasi Urdu dari Ihsan" },
  { nama: "Ehtesham", makna: "Kehormatan, yang berwibawa", asal: "Dari bahasa Arab bermaksud wibawa" },
  { nama: "Faizan", makna: "Keberkatan yang melimpah", asal: "Dari bahasa Arab faydh bermaksud limpahan" },
  { nama: "Farooq", makna: "Yang membezakan hak dan batil", asal: "Gelaran Khalifah Umar bin Al-Khattab" },
];

const namaUrduPerempuan = [
  { nama: "Aaisha", makna: "Yang hidup dan ceria", asal: "Variasi Urdu dari Aisyah" },
  { nama: "Abeera", makna: "Wangian yang harum", asal: "Dari bahasa Arab bermaksud harum" },
  { nama: "Abida", makna: "Yang tekun beribadah", asal: "Dari bahasa Arab abada bermaksud beribadah" },
  { nama: "Afreen", makna: "Pujian, yang mengagumi", asal: "Dari bahasa Parsi bermaksud cantik" },
  { nama: "Aiza", makna: "Yang mulia, yang terhormat", asal: "Dari bahasa Arab bermaksud mulia" },
  { nama: "Ajwa", makna: "Kurma terbaik Madinah", asal: "Nama kurma yang disebutkan dalam hadis" },
  { nama: "Alina", makna: "Yang lembut, yang mulia", asal: "Dari bahasa Parsi bermaksud lembut" },
  { nama: "Amna", makna: "Yang aman, yang damai", asal: "Dari bahasa Arab amn bermaksud aman" },
  { nama: "Arfa", makna: "Yang tinggi, yang mulia", asal: "Dari bahasa Arab bermaksud tinggi" },
  { nama: "Aroha", makna: "Kasih sayang", asal: "Dari bahasa Maori bermaksud kasih" },
  { nama: "Arwa", makna: "Kambing gunung, yang cantik", asal: "Nama sahabiyah Nabi yang terkenal" },
  { nama: "Asima", makna: "Yang menjaga, yang melindungi", asal: "Dari bahasa Arab asama" },
  { nama: "Asna", makna: "Yang terpuji, yang termulia", asal: "Dari bahasa Arab bermaksud terpuji" },
  { nama: "Atiya", makna: "Pemberian, hadiah yang indah", asal: "Dari bahasa Arab ata bermaksud pemberian" },
  { nama: "Ayesha", makna: "Yang hidup, yang ceria", asal: "Variasi Urdu dari Aisyah" },
  { nama: "Azka", makna: "Yang paling suci", asal: "Dari bahasa Arab zaka bermaksud suci" },
  { nama: "Basma", makna: "Senyuman, yang selalu tersenyum", asal: "Dari bahasa Arab basama bermaksud tersenyum" },
  { nama: "Benish", makna: "Yang bijak, yang berpengetahuan", asal: "Dari bahasa Parsi bermaksud ilmu" },
  { nama: "Bushra", makna: "Berita gembira, khabar baik", asal: "Dari bahasa Arab bermaksud khabar baik" },
  { nama: "Dua", makna: "Doa, permohonan kepada Allah", asal: "Dari bahasa Arab bermaksud doa" },
  { nama: "Emaan", makna: "Keimanan, kepercayaan", asal: "Variasi Urdu dari Iman" },
  { nama: "Eshal", makna: "Bunga syurga, yang cantik", asal: "Dari bahasa Urdu bermaksud bunga syurga" },
  { nama: "Fajar", makna: "Fajar, cahaya pagi", asal: "Dari bahasa Arab fajr bermaksud fajar" },
  { nama: "Fareeha", makna: "Yang gembira, yang bahagia", asal: "Dari bahasa Arab faraha bermaksud gembira" },
  { nama: "Fatima", makna: "Yang menahan diri, yang suci", asal: "Variasi Urdu dari Fatimah" },
  { nama: "Gulnaz", makna: "Bunga yang manja", asal: "Dari bahasa Parsi gul dan naz" },
  { nama: "Hadia", makna: "Hadiah, pemberian yang indah", asal: "Dari bahasa Arab hadi bermaksud petunjuk" },
  { nama: "Hajra", makna: "Batu, yang tabah dan kuat", asal: "Variasi Urdu dari Hajar" },
  { nama: "Hana", makna: "Kebahagiaan, kesenangan", asal: "Dari bahasa Arab hana bermaksud gembira" },
  { nama: "Hira", makna: "Gua Hira, tempat wahyu pertama", asal: "Nama gua di Mekah tempat wahyu pertama" },
];
