// MAMAEXPERT — nama-data-4.js
// 500+ nama tambahan — cantik untuk scroll dan discover

const namaTambahan = [
  // ── ARAB LELAKI TAMBAHAN ──
  { nama: "Haura", jantina: "perempuan", bahasa: "Arab", makna: "Bidadari syurga, mata yang indah", asal: "Dari kata hawra bermaksud mata yang indah" },
  { nama: "Adwa", jantina: "perempuan", bahasa: "Arab", makna: "Cahaya, yang menerangi", asal: "Dari kata dawa bermaksud cahaya" },
  { nama: "Aseel", jantina: "perempuan", bahasa: "Arab", makna: "Madu yang tulen, yang asli", asal: "Dari kata asal bermaksud tulen" },
  { nama: "Bayan", jantina: "perempuan", bahasa: "Arab", makna: "Penjelasan, yang jelas berbicara", asal: "Dari kata bayyana bermaksud jelas" },
  { nama: "Doha", jantina: "perempuan", bahasa: "Arab", makna: "Cahaya pagi, waktu dhuha", asal: "Dari kata duha bermaksud pagi yang cerah" },
  { nama: "Elham", jantina: "perempuan", bahasa: "Arab", makna: "Inspirasi, ilham yang indah", asal: "Dari kata alhama bermaksud mengilhamkan" },
  { nama: "Faiza", jantina: "perempuan", bahasa: "Arab", makna: "Yang berjaya, yang menang", asal: "Dari kata faza bermaksud berjaya" },
  { nama: "Ghada", jantina: "perempuan", bahasa: "Arab", makna: "Gadis muda yang cantik", asal: "Dari kata ghada bermaksud remaja yang cantik" },
  { nama: "Hessa", jantina: "perempuan", bahasa: "Arab", makna: "Bahagian, takdir yang indah", asal: "Dari kata hissa bermaksud bahagian" },
  { nama: "Isra", jantina: "perempuan", bahasa: "Arab", makna: "Perjalanan malam yang suci", asal: "Dari kata asra bermaksud perjalanan malam" },
  { nama: "Jana", jantina: "perempuan", bahasa: "Arab", makna: "Buah yang dipetik, hasil yang baik", asal: "Dari kata jana bermaksud memetik buah" },
  { nama: "Kauthar", jantina: "perempuan", bahasa: "Arab", makna: "Sungai syurga, yang banyak kebaikan", asal: "Dari Al-Quran surah Al-Kauthar" },
  { nama: "Lana", jantina: "perempuan", bahasa: "Arab", makna: "Lembut, yang halus dan tenang", asal: "Dari kata lana bermaksud lembut" },
  { nama: "Mona", jantina: "perempuan", bahasa: "Arab", makna: "Harapan, cita-cita yang indah", asal: "Dari kata muna bermaksud harapan" },
  { nama: "Nour", jantina: "perempuan", bahasa: "Arab", makna: "Cahaya yang terang benderang", asal: "Variasi dari Nur bermaksud cahaya" },
  { nama: "Ola", jantina: "perempuan", bahasa: "Arab", makna: "Ketinggian, yang mulia", asal: "Dari kata ala bermaksud tinggi" },
  { nama: "Rama", jantina: "perempuan", bahasa: "Arab", makna: "Rusa putih, yang cantik", asal: "Dari kata rama bermaksud rusa putih" },
  { nama: "Salma", jantina: "perempuan", bahasa: "Arab", makna: "Yang selamat, yang sejahtera", asal: "Dari kata salima bermaksud selamat" },
  { nama: "Tala", jantina: "perempuan", bahasa: "Arab", makna: "Pokok palma muda, yang segar", asal: "Dari kata tala bermaksud pokok muda" },
  { nama: "Ujala", jantina: "perempuan", bahasa: "Arab", makna: "Cahaya, yang bercahaya", asal: "Dari kata ujala bermaksud cahaya terang" },
  { nama: "Waad", jantina: "perempuan", bahasa: "Arab", makna: "Janji, yang menepati janji", asal: "Dari kata waada bermaksud berjanji" },
  { nama: "Xena", jantina: "perempuan", bahasa: "Arab", makna: "Yang asing, yang istimewa", asal: "Dari bahasa Greek bermaksud yang asing" },
  { nama: "Zena", jantina: "perempuan", bahasa: "Arab", makna: "Hiasan, yang menghiasi", asal: "Dari kata zayn bermaksud hiasan" },
  { nama: "Abyan", jantina: "lelaki", bahasa: "Arab", makna: "Yang jelas, yang fasih berbicara", asal: "Dari kata bayyana bermaksud jelas" },
  { nama: "Adham", jantina: "lelaki", bahasa: "Arab", makna: "Yang hitam legam, yang gagah", asal: "Dari kata adhama bermaksud hitam" },
  { nama: "Afzal", jantina: "lelaki", bahasa: "Arab", makna: "Yang lebih baik, yang unggul", asal: "Dari kata fadala bermaksud lebih baik" },
  { nama: "Agil", jantina: "lelaki", bahasa: "Arab", makna: "Yang cerdas, yang bijaksana", asal: "Dari kata aqala bermaksud berfikir" },
  { nama: "Ahyar", jantina: "lelaki", bahasa: "Arab", makna: "Yang terbaik, yang terpilih", asal: "Dari kata khayr bermaksud kebaikan" },
  { nama: "Ainul", jantina: "lelaki", bahasa: "Arab", makna: "Mata yang indah, yang menjadi penyeri", asal: "Dari kata ain bermaksud mata" },
  { nama: "Ajlan", jantina: "lelaki", bahasa: "Arab", makna: "Yang cepat, yang tangkas", asal: "Dari kata ajila bermaksud pantas" },
  { nama: "Akmal", jantina: "lelaki", bahasa: "Arab", makna: "Yang sempurna, yang lengkap", asal: "Dari kata kamula bermaksud sempurna" },
  { nama: "Alawi", jantina: "lelaki", bahasa: "Arab", makna: "Yang tinggi, yang mulia", asal: "Dinisbahkan kepada keturunan mulia" },
  { nama: "Alfian", jantina: "lelaki", bahasa: "Arab", makna: "Seribu kebaikan", asal: "Dari kata alf bermaksud seribu" },
  { nama: "Alim", jantina: "lelaki", bahasa: "Arab", makna: "Yang berpengetahuan luas", asal: "Salah satu nama Allah Al-Alim" },
  { nama: "Altamash", jantina: "lelaki", bahasa: "Arab", makna: "Yang mulia, pemimpin yang agung", asal: "Dari bahasa Turki-Arab bermaksud mulia" },
  { nama: "Ameen", jantina: "lelaki", bahasa: "Arab", makna: "Yang amanah, yang boleh dipercayai", asal: "Variasi dari Amin" },
  { nama: "Amjad", jantina: "lelaki", bahasa: "Arab", makna: "Yang paling mulia", asal: "Dari kata majd bermaksud kemuliaan" },
  { nama: "Amshal", jantina: "lelaki", bahasa: "Arab", makna: "Yang paling cantik, yang terbaik", asal: "Dari kata mathal bermaksud contoh terbaik" },
  { nama: "Annas", jantina: "lelaki", bahasa: "Arab", makna: "Yang mesra, yang ramah", asal: "Variasi dari Anas" },
  { nama: "Anwar", jantina: "lelaki", bahasa: "Arab", makna: "Yang lebih bercahaya", asal: "Dari kata nur bermaksud cahaya" },
  { nama: "Arfan", jantina: "lelaki", bahasa: "Arab", makna: "Yang mengetahui, yang berpengetahuan", asal: "Variasi dari Irfan" },
  { nama: "Arham", jantina: "lelaki", bahasa: "Arab", makna: "Yang paling penyayang", asal: "Dari kata rahim bermaksud penyayang" },
  { nama: "Arkan", jantina: "lelaki", bahasa: "Arab", makna: "Tiang-tiang, yang kukuh", asal: "Dari kata rukn bermaksud tiang" },
  { nama: "Arlind", jantina: "lelaki", bahasa: "Arab", makna: "Singa yang bersih", asal: "Gabungan nama bermaksud singa mulia" },
  { nama: "Arsyad", jantina: "lelaki", bahasa: "Arab", makna: "Yang paling mendapat petunjuk", asal: "Dari kata rashada bermaksud mendapat petunjuk" },
  { nama: "Aslan", jantina: "lelaki", bahasa: "Arab", makna: "Singa, yang gagah berani", asal: "Dari bahasa Turki bermaksud singa" },
  { nama: "Asraf", jantina: "lelaki", bahasa: "Arab", makna: "Yang mulia, yang terhormat", asal: "Variasi dari Asyraf" },
  { nama: "Athif", jantina: "lelaki", bahasa: "Arab", makna: "Yang penyayang, yang baik hati", asal: "Dari kata atafa bermaksud penyayang" },
  { nama: "Awwab", jantina: "lelaki", bahasa: "Arab", makna: "Yang selalu kembali kepada Allah", asal: "Dari kata awwaba bermaksud kembali bertaubat" },
  { nama: "Ayas", jantina: "lelaki", bahasa: "Arab", makna: "Yang cerah, yang bercahaya", asal: "Dari kata aya bermaksud tanda dan cahaya" },
  { nama: "Aysar", jantina: "lelaki", bahasa: "Arab", makna: "Yang paling mudah, yang paling senang", asal: "Dari kata yasara bermaksud mudah" },
  { nama: "Azeem", jantina: "lelaki", bahasa: "Arab", makna: "Yang agung, yang besar", asal: "Variasi dari Azim" },
  { nama: "Azher", jantina: "lelaki", bahasa: "Arab", makna: "Yang bersinar, yang cemerlang", asal: "Variasi dari Azhar" },
  { nama: "Azhim", jantina: "lelaki", bahasa: "Arab", makna: "Yang agung dan mulia", asal: "Dari kata azuma bermaksud agung" },
  { nama: "Azzahra", jantina: "perempuan", bahasa: "Arab", makna: "Yang bersinar, bunga yang cantik", asal: "Dari kata zahara bermaksud bersinar" },

  // ── MELAYU TAMBAHAN ──
  { nama: "Arissa", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mulia dan cantik", asal: "Variasi Melayu bermaksud kemuliaan" },
  { nama: "Adriana", jantina: "perempuan", bahasa: "Melayu", makna: "Yang gelap dan cantik", asal: "Variasi Melayu dari Latin Adriana" },
  { nama: "Afrina", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan mengagumkan", asal: "Dari kata Arab afrina bermaksud cantik" },
  { nama: "Aisara", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mudah, yang memberi kemudahan", asal: "Dari kata Arab yasara bermaksud mudah" },
  { nama: "Aleya", jantina: "perempuan", bahasa: "Melayu", makna: "Yang tinggi, yang mulia", asal: "Variasi Melayu dari Alya" },
  { nama: "Aleeya", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mulia dan tinggi darjat", asal: "Variasi Melayu dari Ali" },
  { nama: "Aleesha", jantina: "perempuan", bahasa: "Melayu", makna: "Yang hidup dan ceria", asal: "Variasi Melayu dari Aisyah" },
  { nama: "Aleisha", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mulia dan bahagia", asal: "Variasi Melayu bermaksud kemuliaan" },
  { nama: "Aleena", jantina: "perempuan", bahasa: "Melayu", makna: "Yang lembut dan cantik", asal: "Variasi Melayu bermaksud kelembutan" },
  { nama: "Aliana", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mulia dan cantik", asal: "Gabungan Ali dan Ana bermaksud mulia" },
  { nama: "Alieya", jantina: "perempuan", bahasa: "Melayu", makna: "Yang tinggi dan mulia", asal: "Variasi Melayu dari Alya" },
  { nama: "Alisha", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mulia dan bahagia", asal: "Variasi Melayu bermaksud kemuliaan" },
  { nama: "Aliya", jantina: "perempuan", bahasa: "Melayu", makna: "Yang tinggi, yang mulia", asal: "Dari kata Arab ala bermaksud tinggi" },
  { nama: "Aliyah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mulia dan tinggi", asal: "Dari kata Arab ala bermaksud tinggi" },
  { nama: "Alya Qistina", jantina: "perempuan", bahasa: "Melayu", makna: "Yang tinggi dan adil", asal: "Gabungan Alya dan Qistina" },
  { nama: "Alyaa", jantina: "perempuan", bahasa: "Melayu", makna: "Yang sangat tinggi dan mulia", asal: "Variasi dari Alya bermaksud tinggi" },
  { nama: "Amalin", jantina: "perempuan", bahasa: "Melayu", makna: "Harapan-harapan yang indah", asal: "Dari kata Arab amal bermaksud harapan" },
  { nama: "Amani", jantina: "perempuan", bahasa: "Melayu", makna: "Harapan dan cita-cita mulia", asal: "Dari kata Arab tamanna bermaksud berharap" },
  { nama: "Amara", jantina: "perempuan", bahasa: "Melayu", makna: "Yang kekal, yang abadi", asal: "Dari kata Arab amara bermaksud kekal" },
  { nama: "Amarina", jantina: "perempuan", bahasa: "Melayu", makna: "Yang kekal dan cantik", asal: "Gabungan Amara dan Rina" },
  { nama: "Amierah", jantina: "perempuan", bahasa: "Melayu", makna: "Puteri, pemimpin wanita", asal: "Variasi Melayu dari Amira" },
  { nama: "Amira Sofea", jantina: "perempuan", bahasa: "Melayu", makna: "Puteri yang suci hati", asal: "Gabungan Amira dan Sofea" },
  { nama: "Amirah", jantina: "perempuan", bahasa: "Melayu", makna: "Puteri raja, pemimpin wanita", asal: "Dari kata Arab amir bermaksud pemimpin" },
  { nama: "Amna", jantina: "perempuan", bahasa: "Melayu", makna: "Yang aman dan damai", asal: "Dari kata Arab amn bermaksud aman" },
  { nama: "Amnah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang memberi keamanan", asal: "Dari kata Arab amana bermaksud aman" },
  { nama: "Andini", jantina: "perempuan", bahasa: "Melayu", makna: "Angin yang sepoi-sepoi", asal: "Dari bahasa Jawa bermaksud angin lembut" },
  { nama: "Anggun", jantina: "perempuan", bahasa: "Melayu", makna: "Yang anggun dan elok", asal: "Kata Melayu asli bermaksud anggun" },
  { nama: "Aniqah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan menarik", asal: "Dari kata Arab aniqa bermaksud cantik" },
  { nama: "Aqeela", jantina: "perempuan", bahasa: "Melayu", makna: "Yang berakal dan bijak", asal: "Dari kata Arab aql bermaksud akal" },
  { nama: "Aqilah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cerdas dan bijaksana", asal: "Dari kata Arab aqala bermaksud berfikir" },
  { nama: "Arfa", jantina: "perempuan", bahasa: "Melayu", makna: "Yang tinggi dan mulia", asal: "Dari kata Arab rafa bermaksud tinggi" },
  { nama: "Arfah", jantina: "perempuan", bahasa: "Melayu", makna: "Bukit Arafah yang mulia", asal: "Nama bukit suci dalam Islam" },
  { nama: "Arina", jantina: "perempuan", bahasa: "Melayu", makna: "Yang damai dan tenang", asal: "Variasi Melayu bermaksud ketenangan" },
  { nama: "Arini", jantina: "perempuan", bahasa: "Melayu", makna: "Yang tenang dan indah", asal: "Variasi Melayu bermaksud keindahan" },
  { nama: "Arissa", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mulia dan cantik jelita", asal: "Variasi Melayu bermaksud kemuliaan" },
  { nama: "Ariza", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan bersinar", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Arlene", jantina: "perempuan", bahasa: "Melayu", makna: "Yang bersumpah, yang setia", asal: "Variasi Melayu dari nama Ireland" },
  { nama: "Armiza", jantina: "perempuan", bahasa: "Melayu", makna: "Yang bermakna dan cantik", asal: "Variasi Melayu bermaksud bermakna" },
  { nama: "Arniza", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan bersih", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Arqam", jantina: "lelaki", bahasa: "Melayu", makna: "Nombor, yang terhitung mulianya", asal: "Nama sahabat Nabi yang terkenal" },
  { nama: "Aryan", jantina: "lelaki", bahasa: "Melayu", makna: "Yang mulia dan berperadaban", asal: "Dari Sanskrit bermaksud mulia" },
  { nama: "Asyiq", jantina: "lelaki", bahasa: "Melayu", makna: "Yang penuh kasih, yang menyintai", asal: "Dari kata Arab ashiqa bermaksud mencintai" },
  { nama: "Athar", jantina: "lelaki", bahasa: "Melayu", makna: "Yang paling suci dan bersih", asal: "Dari kata Arab tahara bermaksud suci" },
  { nama: "Athirah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang wangi, yang harum", asal: "Dari kata Arab athira bermaksud harum" },
  { nama: "Atikah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang bebas dan mulia", asal: "Dari kata Arab atiqa bermaksud bebas" },
  { nama: "Atiqah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang dimerdekakan, yang mulia", asal: "Dari kata Arab atiqa bermaksud merdeka" },
  { nama: "Aufa", jantina: "perempuan", bahasa: "Melayu", makna: "Yang paling sempurna, yang lengkap", asal: "Dari kata Arab awfa bermaksud sempurna" },
  { nama: "Auliya", jantina: "perempuan", bahasa: "Melayu", makna: "Para wali, yang dilindungi Allah", asal: "Dari kata Arab wali bermaksud pelindung" },
  { nama: "Auni", jantina: "perempuan", bahasa: "Melayu", makna: "Bantuanku, pertolonganku", asal: "Dari kata Arab awn bermaksud bantuan" },
  { nama: "Auniey", jantina: "perempuan", bahasa: "Melayu", makna: "Yang memberi bantuan", asal: "Variasi Melayu dari Auni" },
  { nama: "Aura", jantina: "perempuan", bahasa: "Melayu", makna: "Cahaya, pancaran yang indah", asal: "Dari bahasa Latin bermaksud cahaya" },

  // ── INTERNATIONAL TAMBAHAN ──
  { nama: "Aaliya", jantina: "perempuan", bahasa: "International", makna: "Yang tinggi dan mulia", asal: "Nama popular di kalangan Muslim global" },
  { nama: "Abigail", jantina: "perempuan", bahasa: "International", makna: "Kegembiraan bapa, yang menyukakan", asal: "Nama Hebrew yang popular di seluruh dunia" },
  { nama: "Adelaide", jantina: "perempuan", bahasa: "International", makna: "Yang berjiwa mulia", asal: "Nama German bermaksud kemuliaan" },
  { nama: "Adrienne", jantina: "perempuan", bahasa: "International", makna: "Yang gelap, dari Adriatik", asal: "Nama Perancis yang elegan" },
  { nama: "Agatha", jantina: "perempuan", bahasa: "International", makna: "Yang baik, yang mulia", asal: "Nama Greek bermaksud kebaikan" },
  { nama: "Agnes", jantina: "perempuan", bahasa: "International", makna: "Yang suci, yang bersih", asal: "Nama Greek bermaksud suci" },
  { nama: "Aileen", jantina: "perempuan", bahasa: "International", makna: "Cahaya, yang bercahaya", asal: "Nama Ireland bermaksud cahaya" },
  { nama: "Ainsley", jantina: "perempuan", bahasa: "International", makna: "Padang yang indah", asal: "Nama Scotland bermaksud padang" },
  { nama: "Aisha", jantina: "perempuan", bahasa: "International", makna: "Yang hidup dan ceria", asal: "Nama Arab yang popular global" },
  { nama: "Akira", jantina: "perempuan", bahasa: "International", makna: "Yang terang dan cerdas", asal: "Nama Jepun bermaksud terang" },
  { nama: "Alana", jantina: "perempuan", bahasa: "International", makna: "Yang cantik, anak yang berharga", asal: "Nama Ireland bermaksud cantik" },
  { nama: "Alaska", jantina: "perempuan", bahasa: "International", makna: "Tanah yang besar, yang luas", asal: "Dari bahasa Aleut bermaksud laut" },
  { nama: "Alba", jantina: "perempuan", bahasa: "International", makna: "Fajar, yang putih bersih", asal: "Nama Latin bermaksud fajar" },
  { nama: "Alberta", jantina: "perempuan", bahasa: "International", makna: "Yang mulia dan bersinar", asal: "Nama German bermaksud mulia bersinar" },
  { nama: "Alecia", jantina: "perempuan", bahasa: "International", makna: "Yang mulia, yang terhormat", asal: "Variasi dari Alice bermaksud mulia" },
  { nama: "Alessia", jantina: "perempuan", bahasa: "International", makna: "Yang melindungi manusia", asal: "Nama Italian bermaksud pelindung" },
  { nama: "Alexa", jantina: "perempuan", bahasa: "International", makna: "Pelindung manusia", asal: "Dari Greek bermaksud pelindung" },
  { nama: "Alexandra", jantina: "perempuan", bahasa: "International", makna: "Pelindung manusia yang agung", asal: "Nama Greek bermaksud pelindung" },
  { nama: "Alexia", jantina: "perempuan", bahasa: "International", makna: "Yang melindungi", asal: "Variasi dari Alexandra" },
  { nama: "Alexis", jantina: "perempuan", bahasa: "International", makna: "Pelindung, yang membantu", asal: "Nama Greek bermaksud pelindung" },
  { nama: "Alice", jantina: "perempuan", bahasa: "International", makna: "Yang mulia, yang terhormat", asal: "Nama German bermaksud kemuliaan" },
  { nama: "Alicia", jantina: "perempuan", bahasa: "International", makna: "Yang mulia dan terhormat", asal: "Variasi dari Alice bermaksud mulia" },
  { nama: "Alina", jantina: "perempuan", bahasa: "International", makna: "Yang cantik dan lembut", asal: "Nama Slavic bermaksud cantik" },
  { nama: "Alise", jantina: "perempuan", bahasa: "International", makna: "Yang mulia dan baik", asal: "Variasi Perancis dari Alice" },
  { nama: "Alison", jantina: "perempuan", bahasa: "International", makna: "Anak Alice yang mulia", asal: "Nama British bermaksud keturunan mulia" },
  { nama: "Allegra", jantina: "perempuan", bahasa: "International", makna: "Yang riang dan gembira", asal: "Nama Italian bermaksud riang" },
  { nama: "Allison", jantina: "perempuan", bahasa: "International", makna: "Yang mulia dan cantik", asal: "Variasi dari Alison bermaksud mulia" },
  { nama: "Alma", jantina: "perempuan", bahasa: "International", makna: "Jiwa, yang penuh semangat", asal: "Nama Latin bermaksud jiwa" },
  { nama: "Alora", jantina: "perempuan", bahasa: "International", makna: "Impianku, yang diimpikan", asal: "Nama Afrika bermaksud impian" },
  { nama: "Alva", jantina: "perempuan", bahasa: "International", makna: "Yang putih, yang bersinar", asal: "Nama Scandinavian bermaksud putih" },
  { nama: "Alyssa", jantina: "perempuan", bahasa: "International", makna: "Yang mulia, bunga alyssum", asal: "Nama Greek bermaksud mulia" },
  { nama: "Amanda", jantina: "perempuan", bahasa: "International", makna: "Yang patut dicintai", asal: "Nama Latin bermaksud patut dicintai" },
  { nama: "Amara", jantina: "perempuan", bahasa: "International", makna: "Yang kekal abadi, yang cantik", asal: "Nama Latin dan Igbo bermaksud kekal" },
  { nama: "Amber", jantina: "perempuan", bahasa: "International", makna: "Batu permata kuning, yang berharga", asal: "Dari bahasa Arab anbar bermaksud permata" },
  { nama: "Amberly", jantina: "perempuan", bahasa: "International", makna: "Padang permata kuning", asal: "Gabungan Amber dan ley bermaksud padang" },
  { nama: "Amelia", jantina: "perempuan", bahasa: "International", makna: "Yang rajin, yang gigih bekerja", asal: "Nama Latin yang popular global", popular: true },
  { nama: "Amelie", jantina: "perempuan", bahasa: "International", makna: "Yang rajin dan pekerja keras", asal: "Nama Perancis bermaksud rajin" },
  { nama: "Amina", jantina: "perempuan", bahasa: "International", makna: "Yang amanah dan damai", asal: "Nama Arab yang popular global" },
  { nama: "Amira", jantina: "perempuan", bahasa: "International", makna: "Puteri, pemimpin wanita", asal: "Nama Arab yang popular global" },
  { nama: "Anastasia", jantina: "perempuan", bahasa: "International", makna: "Kebangkitan yang mulia", asal: "Nama Greek bermaksud kebangkitan" },
  { nama: "Andrea", jantina: "perempuan", bahasa: "International", makna: "Yang berani dan kuat", asal: "Nama Greek bermaksud berani" },
  { nama: "Angel", jantina: "perempuan", bahasa: "International", makna: "Malaikat, yang suci dan cantik", asal: "Dari Greek angelos bermaksud utusan" },
  { nama: "Angela", jantina: "perempuan", bahasa: "International", makna: "Malaikat, yang diutus", asal: "Dari Latin bermaksud malaikat" },
  { nama: "Angelica", jantina: "perempuan", bahasa: "International", makna: "Seperti malaikat, yang suci", asal: "Nama Latin bermaksud seperti malaikat" },
  { nama: "Angelina", jantina: "perempuan", bahasa: "International", makna: "Malaikat kecil yang cantik", asal: "Nama Latin bermaksud malaikat kecil" },
  { nama: "Angie", jantina: "perempuan", bahasa: "International", makna: "Malaikat, yang suci", asal: "Nama pendek dari Angela" },
  { nama: "Anika", jantina: "perempuan", bahasa: "International", makna: "Yang cantik, yang menyenangkan", asal: "Nama Scandinavian bermaksud cantik" },
  { nama: "Anita", jantina: "perempuan", bahasa: "International", makna: "Allah memberi rahmat", asal: "Nama Spanish bermaksud anugerah Tuhan" },
  { nama: "Anna", jantina: "perempuan", bahasa: "International", makna: "Allah memberi rahmat", asal: "Nama Hebrew yang popular global" },
  { nama: "Annabelle", jantina: "perempuan", bahasa: "International", makna: "Yang cantik dan diberkati", asal: "Gabungan Anna dan Belle bermaksud cantik" },
  { nama: "Anne", jantina: "perempuan", bahasa: "International", makna: "Allah memberi rahmat", asal: "Variasi dari Anna bermaksud rahmat" },
  { nama: "Annette", jantina: "perempuan", bahasa: "International", makna: "Allah memberi rahmat kecil", asal: "Nama Perancis bermaksud rahmat" },
  { nama: "Annie", jantina: "perempuan", bahasa: "International", makna: "Allah memberi rahmat", asal: "Variasi dari Anna bermaksud rahmat" },
  { nama: "Antonia", jantina: "perempuan", bahasa: "International", makna: "Yang tak ternilai harganya", asal: "Nama Latin bermaksud tak ternilai" },
  { nama: "Aoife", jantina: "perempuan", bahasa: "International", makna: "Yang cantik dan berkilauan", asal: "Nama Ireland bermaksud cantik" },
  { nama: "April", jantina: "perempuan", bahasa: "International", makna: "Bulan April, yang segar seperti bunga", asal: "Nama Latin dari bulan April" },
  { nama: "Arabella", jantina: "perempuan", bahasa: "International", makna: "Yang cantik jelita", asal: "Nama Latin bermaksud altaryang cantik" },
  { nama: "Ariel", jantina: "perempuan", bahasa: "International", makna: "Singa Allah, yang berani", asal: "Nama Hebrew bermaksud singa Allah" },
  { nama: "Ariella", jantina: "perempuan", bahasa: "International", makna: "Singa Allah yang cantik", asal: "Nama Hebrew bermaksud singa Allah" },
  { nama: "Arietta", jantina: "perempuan", bahasa: "International", makna: "Lagu kecil yang indah", asal: "Nama Italian bermaksud melodi kecil" },
  { nama: "Arla", jantina: "perempuan", bahasa: "International", makna: "Padang yang indah", asal: "Nama Scandinavian bermaksud padang" },
  { nama: "Arlene", jantina: "perempuan", bahasa: "International", makna: "Yang bersumpah setia", asal: "Nama Ireland bermaksud setia" },
  { nama: "Arya", jantina: "perempuan", bahasa: "International", makna: "Yang mulia dan agung", asal: "Nama Sanskrit bermaksud mulia" },
  { nama: "Asha", jantina: "perempuan", bahasa: "International", makna: "Harapan, yang penuh harapan", asal: "Nama Sanskrit bermaksud harapan" },
  { nama: "Ashlee", jantina: "perempuan", bahasa: "International", makna: "Padang pokok ash yang cantik", asal: "Nama English bermaksud padang ash" },
  { nama: "Ashley", jantina: "perempuan", bahasa: "International", makna: "Padang pokok ash yang luas", asal: "Nama English bermaksud padang" },
  { nama: "Ashlyn", jantina: "perempuan", bahasa: "International", makna: "Kolam padang pokok ash", asal: "Nama Ireland bermaksud kolam padang" },
  { nama: "Aspen", jantina: "perempuan", bahasa: "International", makna: "Pokok aspen yang menggeletar", asal: "Nama English dari pokok aspen" },
  { nama: "Asteria", jantina: "perempuan", bahasa: "International", makna: "Bintang, dewi bintang", asal: "Nama Greek bermaksud bintang" },
  { nama: "Athena", jantina: "perempuan", bahasa: "International", makna: "Dewi kebijaksanaan", asal: "Nama Greek bermaksud dewi bijak" },
  { nama: "Aubrey", jantina: "perempuan", bahasa: "International", makna: "Pemerintah elf yang mulia", asal: "Nama German bermaksud pemerintah mulia" },
  { nama: "Audrey", jantina: "perempuan", bahasa: "International", makna: "Kekuatan yang mulia", asal: "Nama English bermaksud kekuatan mulia" },
  { nama: "Augusta", jantina: "perempuan", bahasa: "International", makna: "Yang agung dan mulia", asal: "Nama Latin bermaksud agung" },
  { nama: "Aurelie", jantina: "perempuan", bahasa: "International", makna: "Yang keemasan, yang bercahaya", asal: "Nama Perancis bermaksud emas" },
  { nama: "Aurelia", jantina: "perempuan", bahasa: "International", makna: "Yang keemasan, yang mulia", asal: "Nama Latin bermaksud emas" },
  { nama: "Ava", jantina: "perempuan", bahasa: "International", makna: "Hidup, yang penuh kehidupan", asal: "Nama Latin bermaksud kehidupan", popular: true },
  { nama: "Avalon", jantina: "perempuan", bahasa: "International", makna: "Pulau epal, yang indah", asal: "Dari legenda Celtic bermaksud pulau" },
  { nama: "Avery", jantina: "perempuan", bahasa: "International", makna: "Pemerintah elf, yang bijak", asal: "Nama English bermaksud pemerintah" },
  { nama: "Ayla", jantina: "perempuan", bahasa: "International", makna: "Cahaya bulan, yang bersinar", asal: "Nama Turki bermaksud cahaya bulan" },
  { nama: "Aylin", jantina: "perempuan", bahasa: "International", makna: "Bulan yang bersinar indah", asal: "Nama Turki bermaksud bulan bersinar" },
  { nama: "Azalea", jantina: "perempuan", bahasa: "International", makna: "Bunga azalea yang cantik", asal: "Nama bunga yang cantik" },
  { nama: "Bea", jantina: "perempuan", bahasa: "International", makna: "Yang membahagiakan", asal: "Nama pendek dari Beatrice" },
  { nama: "Beatrice", jantina: "perempuan", bahasa: "International", makna: "Yang membahagiakan", asal: "Nama Latin bermaksud bahagia" },
  { nama: "Bella", jantina: "perempuan", bahasa: "International", makna: "Yang cantik jelita", asal: "Nama Italian bermaksud cantik" },
  { nama: "Belle", jantina: "perempuan", bahasa: "International", makna: "Yang cantik dan indah", asal: "Nama Perancis bermaksud cantik" },
  { nama: "Bernadette", jantina: "perempuan", bahasa: "International", makna: "Berani seperti beruang", asal: "Nama German bermaksud berani" },
  { nama: "Bianca", jantina: "perempuan", bahasa: "International", makna: "Yang putih bersih dan cantik", asal: "Nama Italian bermaksud putih" },
  { nama: "Blair", jantina: "perempuan", bahasa: "International", makna: "Padang terbuka, yang bebas", asal: "Nama Scotland bermaksud padang" },
  { nama: "Blanche", jantina: "perempuan", bahasa: "International", makna: "Yang putih bersih", asal: "Nama Perancis bermaksud putih" },
  { nama: "Blossom", jantina: "perempuan", bahasa: "International", makna: "Bunga yang mekar indah", asal: "Nama English bermaksud bunga mekar" },
  { nama: "Bonnie", jantina: "perempuan", bahasa: "International", makna: "Yang cantik dan manis", asal: "Nama Scotland bermaksud cantik" },
  { nama: "Briar", jantina: "perempuan", bahasa: "International", makna: "Bunga liar yang cantik", asal: "Nama English bermaksud bunga liar" },
  { nama: "Bridget", jantina: "perempuan", bahasa: "International", makna: "Yang kuat dan mulia", asal: "Nama Ireland bermaksud kekuatan" },
  { nama: "Briella", jantina: "perempuan", bahasa: "International", makna: "Tuhan adalah kekuatanku", asal: "Gabungan nama bermaksud kekuatan Tuhan" },
  { nama: "Brielle", jantina: "perempuan", bahasa: "International", makna: "Tuhan adalah kekuatan", asal: "Nama Perancis bermaksud kekuatan" },
  { nama: "Britta", jantina: "perempuan", bahasa: "International", makna: "Yang kuat dan tinggi", asal: "Nama Scandinavian bermaksud kuat" },
  { nama: "Brooke", jantina: "perempuan", bahasa: "International", makna: "Anak sungai kecil, yang mengalir", asal: "Nama English bermaksud anak sungai" },
  { nama: "Brooklyn", jantina: "perempuan", bahasa: "International", makna: "Anak sungai yang cantik", asal: "Nama English bermaksud sungai" },
  { nama: "Caitlin", jantina: "perempuan", bahasa: "International", makna: "Yang suci dan murni", asal: "Nama Ireland bermaksud suci" },
  { nama: "Callie", jantina: "perempuan", bahasa: "International", makna: "Yang cantik, yang indah", asal: "Nama Greek bermaksud cantik" },
  { nama: "Calliope", jantina: "perempuan", bahasa: "International", makna: "Suara yang cantik dan merdu", asal: "Nama Greek bermaksud suara cantik" },
  { nama: "Camilla", jantina: "perempuan", bahasa: "International", makna: "Yang suci dan sempurna", asal: "Nama Latin bermaksud suci" },
  { nama: "Cara", jantina: "perempuan", bahasa: "International", makna: "Yang dicintai, yang dikasihi", asal: "Nama Italian bermaksud sayang" },
  { nama: "Carina", jantina: "perempuan", bahasa: "International", makna: "Yang dikasihi, yang sayang", asal: "Nama Latin bermaksud dikasihi" },
  { nama: "Carla", jantina: "perempuan", bahasa: "International", makna: "Wanita yang bebas dan kuat", asal: "Nama German bermaksud bebas" },
  { nama: "Carmen", jantina: "perempuan", bahasa: "International", makna: "Kebun buah, yang manis", asal: "Nama Spanish bermaksud kebun" },
  { nama: "Carolina", jantina: "perempuan", bahasa: "International", makna: "Wanita yang bebas dan kuat", asal: "Nama Latin bermaksud bebas" },
  { nama: "Caroline", jantina: "perempuan", bahasa: "International", makna: "Wanita yang bebas", asal: "Nama Perancis bermaksud bebas" },
  { nama: "Cassandra", jantina: "perempuan", bahasa: "International", makna: "Yang bersinar pada manusia", asal: "Nama Greek bermaksud bersinar" },
  { nama: "Cassidy", jantina: "perempuan", bahasa: "International", makna: "Yang keriting, yang manis", asal: "Nama Ireland bermaksud keriting" },
  { nama: "Catalina", jantina: "perempuan", bahasa: "International", makna: "Yang suci dan murni", asal: "Nama Spanish bermaksud suci" },
  { nama: "Catherine", jantina: "perempuan", bahasa: "International", makna: "Yang suci dan bersih", asal: "Nama Greek bermaksud suci" },
  { nama: "Cecilia", jantina: "perempuan", bahasa: "International", makna: "Yang buta, yang lemah lembut", asal: "Nama Latin bermaksud lemah lembut" },
  { nama: "Celeste", jantina: "perempuan", bahasa: "International", makna: "Syurga, yang bersifat langit", asal: "Nama Latin bermaksud langit" },
  { nama: "Celine", jantina: "perempuan", bahasa: "International", makna: "Bulan, yang bercahaya", asal: "Nama Perancis bermaksud bulan" },
  { nama: "Charlotte", jantina: "perempuan", bahasa: "International", makna: "Wanita kecil yang bebas", asal: "Nama Perancis bermaksud bebas", popular: true },
  { nama: "Chelsea", jantina: "perempuan", bahasa: "International", makna: "Pelabuhan kapur, yang kuat", asal: "Nama English bermaksud pelabuhan" },
  { nama: "Cherie", jantina: "perempuan", bahasa: "International", makna: "Yang disayangi, yang dikasihi", asal: "Nama Perancis bermaksud sayang" },
  { nama: "Chiara", jantina: "perempuan", bahasa: "International", makna: "Yang jelas dan bercahaya", asal: "Nama Italian bermaksud cerah" },
  { nama: "Chloe", jantina: "perempuan", bahasa: "International", makna: "Yang segar dan muda", asal: "Nama Greek bermaksud tunas muda" },
  { nama: "Christelle", jantina: "perempuan", bahasa: "International", makna: "Kristal yang bersinar", asal: "Nama Perancis bermaksud kristal" },
  { nama: "Christina", jantina: "perempuan", bahasa: "International", makna: "Pengikut yang setia", asal: "Nama Greek bermaksud pengikut" },
  { nama: "Christine", jantina: "perempuan", bahasa: "International", makna: "Yang diurapi, yang setia", asal: "Nama Greek bermaksud setia" },
  { nama: "Ciara", jantina: "perempuan", bahasa: "International", makna: "Yang gelap, yang misterius", asal: "Nama Ireland bermaksud gelap" },
  { nama: "Claire", jantina: "perempuan", bahasa: "International", makna: "Yang jelas, yang bercahaya", asal: "Nama Perancis bermaksud terang" },
  { nama: "Clara", jantina: "perempuan", bahasa: "International", makna: "Yang jelas dan bersinar", asal: "Nama Latin bermaksud terang" },
  { nama: "Clarissa", jantina: "perempuan", bahasa: "International", makna: "Yang paling jelas dan cantik", asal: "Nama Latin bermaksud sangat terang" },
  { nama: "Claudia", jantina: "perempuan", bahasa: "International", makna: "Yang lemah, yang lembut hati", asal: "Nama Latin bermaksud lemah lembut" },
  { nama: "Clementine", jantina: "perempuan", bahasa: "International", makna: "Yang penyayang dan lembut", asal: "Nama Latin bermaksud penyayang" },
  { nama: "Coco", jantina: "perempuan", bahasa: "International", makna: "Yang comel dan manis", asal: "Nama popular bermaksud comel" },
  { nama: "Colette", jantina: "perempuan", bahasa: "International", makna: "Kemenangan rakyat", asal: "Nama Perancis bermaksud kemenangan" },
  { nama: "Cordelia", jantina: "perempuan", bahasa: "International", makna: "Anak laut, yang murni hati", asal: "Nama Latin bermaksud anak laut" },
  { nama: "Corinne", jantina: "perempuan", bahasa: "International", makna: "Gadis muda yang cantik", asal: "Nama Greek bermaksud gadis" },
  { nama: "Cosima", jantina: "perempuan", bahasa: "International", makna: "Keteraturan, yang harmoni", asal: "Nama Italian bermaksud harmoni" },
  { nama: "Crystal", jantina: "perempuan", bahasa: "International", makna: "Kristal yang jernih dan bersih", asal: "Nama Greek bermaksud kristal" },
  { nama: "Dahlia", jantina: "perempuan", bahasa: "International", makna: "Bunga dahlia yang cantik", asal: "Nama dari bunga dahlia" },
  { nama: "Daisy", jantina: "perempuan", bahasa: "International", makna: "Bunga daisy yang segar", asal: "Nama English dari bunga daisy" },
  { nama: "Dakota", jantina: "perempuan", bahasa: "International", makna: "Sahabat yang setia", asal: "Nama Native American bermaksud sahabat" },
  { nama: "Daniela", jantina: "perempuan", bahasa: "International", makna: "Allah adalah hakimku", asal: "Nama Hebrew bermaksud hakim Allah" },
  { nama: "Daphne", jantina: "perempuan", bahasa: "International", makna: "Pokok laurel, yang cantik", asal: "Nama Greek bermaksud pokok laurel" },
  { nama: "Dara", jantina: "perempuan", bahasa: "International", makna: "Yang bijak, yang bintang", asal: "Nama Ireland bermaksud bijak" },
  { nama: "Darcy", jantina: "perempuan", bahasa: "International", makna: "Yang gelap, yang misterius", asal: "Nama Ireland bermaksud gelap" },
  { nama: "Dawn", jantina: "perempuan", bahasa: "International", makna: "Fajar, awal yang baru", asal: "Nama English bermaksud fajar" },
  { nama: "Delia", jantina: "perempuan", bahasa: "International", makna: "Dari pulau Delos, yang cantik", asal: "Nama Greek dari pulau Delos" },
  { nama: "Delilah", jantina: "perempuan", bahasa: "International", makna: "Yang menawan, yang lemah lembut", asal: "Nama Hebrew bermaksud menawan" },
  { nama: "Della", jantina: "perempuan", bahasa: "International", makna: "Yang mulia, yang berharga", asal: "Nama English bermaksud mulia" },
  { nama: "Destiny", jantina: "perempuan", bahasa: "International", makna: "Takdir, yang ditakdirkan", asal: "Nama English bermaksud takdir" },
  { nama: "Diana", jantina: "perempuan", bahasa: "International", makna: "Dewi bulan, yang bercahaya", asal: "Nama Latin bermaksud cahaya ilahi" },
  { nama: "Dominique", jantina: "perempuan", bahasa: "International", makna: "Milik Tuhan, yang suci", asal: "Nama Perancis bermaksud milik Tuhan" },
  { nama: "Eden", jantina: "perempuan", bahasa: "International", makna: "Taman syurga, yang indah", asal: "Nama Hebrew bermaksud taman" },
  { nama: "Edith", jantina: "perempuan", bahasa: "International", makna: "Kekayaan perang, yang kuat", asal: "Nama English bermaksud kekayaan" },
  { nama: "Elaine", jantina: "perempuan", bahasa: "International", makna: "Cahaya, yang bersinar", asal: "Nama Greek bermaksud cahaya" },
  { nama: "Eleanor", jantina: "perempuan", bahasa: "International", makna: "Yang bersinar terang", asal: "Nama Greek bermaksud cahaya" },
  { nama: "Elena", jantina: "perempuan", bahasa: "International", makna: "Cahaya yang terang benderang", asal: "Nama Greek bermaksud cahaya" },
  { nama: "Eliana", jantina: "perempuan", bahasa: "International", makna: "Allah telah menjawab", asal: "Nama Hebrew bermaksud jawapan Allah" },
  { nama: "Elizabeth", jantina: "perempuan", bahasa: "International", makna: "Allah adalah sumpahku", asal: "Nama Hebrew bermaksud janji Allah" },
  { nama: "Ella", jantina: "perempuan", bahasa: "International", makna: "Yang cantik, peri", asal: "Nama German bermaksud cantik", popular: true },
  { nama: "Ellie", jantina: "perempuan", bahasa: "International", makna: "Cahaya yang terang", asal: "Nama pendek dari Eleanor" },
  { nama: "Eloise", jantina: "perempuan", bahasa: "International", makna: "Yang terkenal dalam perang", asal: "Nama Perancis bermaksud terkenal" },
  { nama: "Elsa", jantina: "perempuan", bahasa: "International", makna: "Yang bersumpah kepada Allah", asal: "Variasi dari Elizabeth" },
  { nama: "Emilia", jantina: "perempuan", bahasa: "International", makna: "Yang gigih dan bersemangat", asal: "Nama Latin bermaksud bersemangat" },
  { nama: "Emily", jantina: "perempuan", bahasa: "International", makna: "Yang rajin dan tekun", asal: "Nama Latin bermaksud rajin", popular: true },
  { nama: "Emma", jantina: "perempuan", bahasa: "International", makna: "Yang utuh, yang universal", asal: "Nama German bermaksud utuh", popular: true },
  { nama: "Emmeline", jantina: "perempuan", bahasa: "International", makna: "Yang bekerja keras", asal: "Nama German bermaksud kerja keras" },
  { nama: "Esme", jantina: "perempuan", bahasa: "International", makna: "Yang dikasihi, yang dihormati", asal: "Nama Perancis bermaksud dihormati" },
  { nama: "Estelle", jantina: "perempuan", bahasa: "International", makna: "Bintang, yang bersinar", asal: "Nama Perancis bermaksud bintang" },
  { nama: "Esther", jantina: "perempuan", bahasa: "International", makna: "Bintang, yang bersinar terang", asal: "Nama Hebrew bermaksud bintang" },
  { nama: "Eva", jantina: "perempuan", bahasa: "International", makna: "Kehidupan, yang penuh hidup", asal: "Nama Hebrew bermaksud kehidupan" },
  { nama: "Evangeline", jantina: "perempuan", bahasa: "International", makna: "Pembawa berita gembira", asal: "Nama Greek bermaksud berita baik" },
  { nama: "Evie", jantina: "perempuan", bahasa: "International", makna: "Kehidupan yang manis", asal: "Nama pendek dari Eva" },
  { nama: "Faith", jantina: "perempuan", bahasa: "International", makna: "Kepercayaan, keimanan yang teguh", asal: "Nama English bermaksud iman" },
  { nama: "Fatou", jantina: "perempuan", bahasa: "International", makna: "Yang menahan diri, yang suci", asal: "Variasi Afrika dari Fatimah" },
  { nama: "Felicia", jantina: "perempuan", bahasa: "International", makna: "Yang bertuah dan bahagia", asal: "Nama Latin bermaksud bertuah" },
  { nama: "Felicity", jantina: "perempuan", bahasa: "International", makna: "Kebahagiaan yang abadi", asal: "Nama Latin bermaksud bahagia" },
  { nama: "Fleur", jantina: "perempuan", bahasa: "International", makna: "Bunga, yang cantik dan segar", asal: "Nama Perancis bermaksud bunga" },
  { nama: "Florence", jantina: "perempuan", bahasa: "International", makna: "Yang berkembang, yang subur", asal: "Nama Latin bermaksud berkembang" },
  { nama: "Francesca", jantina: "perempuan", bahasa: "International", makna: "Yang bebas, dari Perancis", asal: "Nama Italian bermaksud bebas" },
  { nama: "Freya", jantina: "perempuan", bahasa: "International", makna: "Dewi cinta dan kesuburan", asal: "Nama Norse bermaksud mulia" },
  { nama: "Gabriella", jantina: "perempuan", bahasa: "International", makna: "Allah adalah kekuatanku", asal: "Nama Hebrew bermaksud kekuatan Allah" },
  { nama: "Gemma", jantina: "perempuan", bahasa: "International", makna: "Permata, yang berharga", asal: "Nama Italian bermaksud permata" },
  { nama: "Genevieve", jantina: "perempuan", bahasa: "International", makna: "Wanita suku Genovefa", asal: "Nama Celtic bermaksud wanita suku" },
  { nama: "Georgia", jantina: "perempuan", bahasa: "International", makna: "Petani, yang rajin bekerja", asal: "Nama Greek bermaksud petani" },
  { nama: "Gia", jantina: "perempuan", bahasa: "International", makna: "Allah adalah cantik", asal: "Nama Italian bermaksud cantik Allah" },
  { nama: "Giselle", jantina: "perempuan", bahasa: "International", makna: "Janji, yang berjanji setia", asal: "Nama German bermaksud janji" },
  { nama: "Gloria", jantina: "perempuan", bahasa: "International", makna: "Kemuliaan, yang mulia", asal: "Nama Latin bermaksud kemuliaan" },
  { nama: "Grace", jantina: "perempuan", bahasa: "International", makna: "Rahmat, yang penuh rahmat", asal: "Nama Latin bermaksud rahmat", popular: true },
  { nama: "Greta", jantina: "perempuan", bahasa: "International", makna: "Mutiara, yang berharga", asal: "Nama German bermaksud mutiara" },
  { nama: "Guinevere", jantina: "perempuan", bahasa: "International", makna: "Pari putih yang cantik", asal: "Nama Welsh bermaksud pari putih" },
  { nama: "Hailey", jantina: "perempuan", bahasa: "International", makna: "Padang jerami yang cantik", asal: "Nama English bermaksud padang" },
  { nama: "Hannah", jantina: "perempuan", bahasa: "International", makna: "Allah memberi rahmat", asal: "Nama Hebrew bermaksud rahmat Allah" },
  { nama: "Harmony", jantina: "perempuan", bahasa: "International", makna: "Keharmonian, yang damai", asal: "Nama English bermaksud harmoni" },
  { nama: "Harper", jantina: "perempuan", bahasa: "International", makna: "Pemain harpa, yang berbakat", asal: "Nama English bermaksud harpa" },
  { nama: "Harriet", jantina: "perempuan", bahasa: "International", makna: "Pemerintah rumah yang kuat", asal: "Nama German bermaksud pemerintah" },
  { nama: "Hazel", jantina: "perempuan", bahasa: "International", makna: "Pokok hazel, yang bijak", asal: "Nama English dari pokok hazel" },
  { nama: "Heidi", jantina: "perempuan", bahasa: "International", makna: "Yang mulia, berjiwa mulia", asal: "Nama German bermaksud mulia" },
  { nama: "Hollie", jantina: "perempuan", bahasa: "International", makna: "Pokok holly yang segar", asal: "Nama English dari pokok holly" },
  { nama: "Holly", jantina: "perempuan", bahasa: "International", makna: "Pokok holly, yang segar", asal: "Nama English bermaksud pokok holly" },
  { nama: "Hope", jantina: "perempuan", bahasa: "International", makna: "Harapan, yang penuh harapan", asal: "Nama English bermaksud harapan" },
  { nama: "Imogen", jantina: "perempuan", bahasa: "International", makna: "Anak gadis, yang cantik", asal: "Nama Celtic bermaksud gadis" },
  { nama: "India", jantina: "perempuan", bahasa: "International", makna: "Dari negara India yang kaya", asal: "Nama dari negara India" },
  { nama: "Indigo", jantina: "perempuan", bahasa: "International", makna: "Warna biru indigo yang indah", asal: "Nama dari warna indigo" },
  { nama: "Ingrid", jantina: "perempuan", bahasa: "International", makna: "Yang cantik dan subur", asal: "Nama Norse bermaksud cantik" },
  { nama: "Isla", jantina: "perempuan", bahasa: "International", makna: "Pulau, yang tenang dan indah", asal: "Nama Scotland bermaksud pulau" },
  { nama: "Isolde", jantina: "perempuan", bahasa: "International", makna: "Yang cantik, yang berpengaruh", asal: "Nama Celtic bermaksud cantik" },
  { nama: "Ivy", jantina: "perempuan", bahasa: "International", makna: "Pokok ivy, yang setia", asal: "Nama English dari pokok ivy" },
  { nama: "Jacqueline", jantina: "perempuan", bahasa: "International", makna: "Yang menggantikan, yang berjaya", asal: "Nama Perancis bermaksud pengganti" },
  { nama: "Jade", jantina: "perempuan", bahasa: "International", makna: "Batu jade yang berharga", asal: "Nama Spanish dari batu jade" },
  { nama: "Jamie", jantina: "perempuan", bahasa: "International", makna: "Yang menggantikan", asal: "Variasi dari James bermaksud pengganti" },
  { nama: "Jane", jantina: "perempuan", bahasa: "International", makna: "Allah memberi rahmat", asal: "Nama English bermaksud rahmat" },
  { nama: "Jasmine", jantina: "perempuan", bahasa: "International", makna: "Bunga jasmine yang harum", asal: "Nama Persian dari bunga jasmine" },
  { nama: "Jenna", jantina: "perempuan", bahasa: "International", makna: "Taman syurga yang indah", asal: "Variasi dari Jennifer bermaksud taman" },
  { nama: "Jennifer", jantina: "perempuan", bahasa: "International", makna: "Pari yang putih cantik", asal: "Nama Welsh bermaksud pari putih" },
  { nama: "Jessica", jantina: "perempuan", bahasa: "International", makna: "Allah melihat segalanya", asal: "Nama Hebrew bermaksud Allah melihat" },
  { nama: "Josephine", jantina: "perempuan", bahasa: "International", makna: "Allah akan menambah", asal: "Nama Hebrew bermaksud tambahan Allah" },
  { nama: "Joy", jantina: "perempuan", bahasa: "International", makna: "Kegembiraan, yang selalu gembira", asal: "Nama English bermaksud gembira" },
  { nama: "Julia", jantina: "perempuan", bahasa: "International", makna: "Yang muda dan bersemangat", asal: "Nama Latin bermaksud muda" },
  { nama: "Juliana", jantina: "perempuan", bahasa: "International", makna: "Yang muda dan cantik", asal: "Nama Latin bermaksud muda cantik" },
  { nama: "Juliette", jantina: "perempuan", bahasa: "International", makna: "Yang muda dan romantis", asal: "Nama Perancis bermaksud muda" },
  { nama: "June", jantina: "perempuan", bahasa: "International", makna: "Bulan Jun, yang segar", asal: "Nama dari bulan Jun" },
  { nama: "Juniper", jantina: "perempuan", bahasa: "International", makna: "Pokok juniper yang kuat", asal: "Nama dari pokok juniper" },
  { nama: "Kate", jantina: "perempuan", bahasa: "International", makna: "Yang suci dan bersih", asal: "Nama pendek dari Katherine" },
  { nama: "Katelyn", jantina: "perempuan", bahasa: "International", makna: "Yang suci dan cantik", asal: "Variasi dari Katherine" },
  { nama: "Katherine", jantina: "perempuan", bahasa: "International", makna: "Yang suci dan murni", asal: "Nama Greek bermaksud suci" },
  { nama: "Kathleen", jantina: "perempuan", bahasa: "International", makna: "Yang suci, yang murni", asal: "Variasi Ireland dari Katherine" },
  { nama: "Katrina", jantina: "perempuan", bahasa: "International", makna: "Yang suci dan bersih", asal: "Variasi dari Katherine" },
  { nama: "Kayla", jantina: "perempuan", bahasa: "International", makna: "Yang suci, yang cantik", asal: "Variasi dari Katherine" },
  { nama: "Keira", jantina: "perempuan", bahasa: "International", makna: "Yang gelap dan cantik", asal: "Nama Ireland bermaksud gelap" },
  { nama: "Kelly", jantina: "perempuan", bahasa: "International", makna: "Pejuang yang berani", asal: "Nama Ireland bermaksud pejuang" },
  { nama: "Kennedy", jantina: "perempuan", bahasa: "International", makna: "Kepala yang berbentuk helm", asal: "Nama Ireland bermaksud ketua" },
  { nama: "Kiara", jantina: "perempuan", bahasa: "International", makna: "Yang terang dan jelas", asal: "Nama Italian bermaksud terang" },
  { nama: "Kira", jantina: "perempuan", bahasa: "International", makna: "Cahaya, yang bersinar", asal: "Nama Greek bermaksud cahaya" },
  { nama: "Laura", jantina: "perempuan", bahasa: "International", makna: "Yang dimahkota laurel", asal: "Nama Latin bermaksud laurel" },
  { nama: "Lauren", jantina: "perempuan", bahasa: "International", makna: "Yang dimahkota laurel", asal: "Variasi dari Laura bermaksud laurel" },
  { nama: "Layla", jantina: "perempuan", bahasa: "International", makna: "Malam yang indah", asal: "Nama Arab yang popular global" },
  { nama: "Lea", jantina: "perempuan", bahasa: "International", makna: "Singa betina, yang kuat", asal: "Nama Perancis bermaksud singa" },
  { nama: "Leah", jantina: "perempuan", bahasa: "International", makna: "Yang penat, yang lemah lembut", asal: "Nama Hebrew bermaksud lemah lembut" },
  { nama: "Leila", jantina: "perempuan", bahasa: "International", makna: "Malam yang indah dan cantik", asal: "Nama Persian bermaksud malam" },
  { nama: "Lena", jantina: "perempuan", bahasa: "International", makna: "Cahaya, yang bersinar terang", asal: "Nama Greek bermaksud cahaya" },
  { nama: "Leonora", jantina: "perempuan", bahasa: "International", makna: "Cahaya singa yang kuat", asal: "Gabungan Leon dan Nora bermaksud cahaya" },
  { nama: "Lexi", jantina: "perempuan", bahasa: "International", makna: "Pelindung manusia", asal: "Nama pendek dari Alexandra" },
  { nama: "Lia", jantina: "perempuan", bahasa: "International", makna: "Pembawa berita gembira", asal: "Nama Greek bermaksud berita" },
  { nama: "Lila", jantina: "perempuan", bahasa: "International", makna: "Bunga lilac, yang cantik", asal: "Nama Persian bermaksud lilac" },
  { nama: "Lilah", jantina: "perempuan", bahasa: "International", makna: "Malam, yang indah", asal: "Nama Hebrew bermaksud malam" },
  { nama: "Lillian", jantina: "perempuan", bahasa: "International", makna: "Bunga lily, yang suci", asal: "Nama Latin bermaksud lily" },
  { nama: "Lily", jantina: "perempuan", bahasa: "International", makna: "Bunga lily yang suci cantik", asal: "Nama English dari bunga lily" },
  { nama: "Lina", jantina: "perempuan", bahasa: "International", makna: "Yang lembut dan cantik", asal: "Nama Arabic-Latin bermaksud lembut" },
  { nama: "Linda", jantina: "perempuan", bahasa: "International", makna: "Yang cantik dan lembut", asal: "Nama Spanish bermaksud cantik" },
  { nama: "Lindsay", jantina: "perempuan", bahasa: "International", makna: "Pulau pokok linden", asal: "Nama Scotland bermaksud pulau" },
  { nama: "Lisa", jantina: "perempuan", bahasa: "International", makna: "Allah adalah sumpahku", asal: "Nama pendek dari Elizabeth" },
  { nama: "Lola", jantina: "perempuan", bahasa: "International", makna: "Kesedihan, yang kuat", asal: "Nama Spanish bermaksud kesedihan" },
  { nama: "Lottie", jantina: "perempuan", bahasa: "International", makna: "Wanita kecil yang bebas", asal: "Nama pendek dari Charlotte" },
  { nama: "Louisa", jantina: "perempuan", bahasa: "International", makna: "Pejuang yang terkenal", asal: "Nama German bermaksud pejuang" },
  { nama: "Louise", jantina: "perempuan", bahasa: "International", makna: "Pejuang yang terkenal", asal: "Nama Perancis bermaksud pejuang" },
  { nama: "Lucia", jantina: "perempuan", bahasa: "International", makna: "Cahaya, yang bercahaya terang", asal: "Nama Latin bermaksud cahaya" },
  { nama: "Lucy", jantina: "perempuan", bahasa: "International", makna: "Cahaya, yang bersinar", asal: "Nama English bermaksud cahaya" },
  { nama: "Luna", jantina: "perempuan", bahasa: "International", makna: "Bulan, yang bercahaya", asal: "Nama Latin bermaksud bulan", popular: true },
  { nama: "Lydia", jantina: "perempuan", bahasa: "International", makna: "Dari negeri Lydia", asal: "Nama Greek dari negeri Lydia" },
  { nama: "Lyla", jantina: "perempuan", bahasa: "International", makna: "Malam, yang indah", asal: "Variasi dari Layla bermaksud malam" },
  { nama: "Mabel", jantina: "perempuan", bahasa: "International", makna: "Yang dikasihi, yang manis", asal: "Nama Latin bermaksud dikasihi" },
  { nama: "Madeleine", jantina: "perempuan", bahasa: "International", makna: "Wanita dari Magdala", asal: "Nama Perancis bermaksud dari Magdala" },
  { nama: "Madison", jantina: "perempuan", bahasa: "International", makna: "Anak Matthew yang kuat", asal: "Nama English bermaksud anak Matthew" },
  { nama: "Maisie", jantina: "perempuan", bahasa: "International", makna: "Mutiara, yang berharga", asal: "Nama Scotland bermaksud mutiara" },
  { nama: "Margot", jantina: "perempuan", bahasa: "International", makna: "Mutiara yang berharga", asal: "Nama Perancis bermaksud mutiara" },
  { nama: "Maria", jantina: "perempuan", bahasa: "International", makna: "Yang dikasihi Allah", asal: "Nama Latin yang popular global" },
  { nama: "Mariam", jantina: "perempuan", bahasa: "International", makna: "Yang taat beribadah", asal: "Variasi dari Maryam" },
  { nama: "Marie", jantina: "perempuan", bahasa: "International", makna: "Yang dikasihi Allah", asal: "Nama Perancis bermaksud dikasihi" },
  { nama: "Marina", jantina: "perempuan", bahasa: "International", makna: "Dari laut, yang bebas", asal: "Nama Latin bermaksud laut" },
  { nama: "Marlowe", jantina: "perempuan", bahasa: "International", makna: "Sisa tasik, yang tenang", asal: "Nama English bermaksud sisa tasik" },
  { nama: "Martha", jantina: "perempuan", bahasa: "International", makna: "Suri rumah, yang kuat", asal: "Nama Aramaic bermaksud suri" },
  { nama: "Matilda", jantina: "perempuan", bahasa: "International", makna: "Pejuang yang kuat", asal: "Nama German bermaksud pejuang kuat" },
  { nama: "Maya", jantina: "perempuan", bahasa: "International", makna: "Ilusi, yang menakjubkan", asal: "Nama Sanskrit bermaksud ilusi" },
  { nama: "Megan", jantina: "perempuan", bahasa: "International", makna: "Mutiara yang besar", asal: "Nama Welsh bermaksud mutiara" },
  { nama: "Melody", jantina: "perempuan", bahasa: "International", makna: "Melodi yang indah", asal: "Nama Greek bermaksud lagu" },
  { nama: "Mia", jantina: "perempuan", bahasa: "International", makna: "Milikku, yang dikasihi", asal: "Nama Scandinavian bermaksud milik", popular: true },
  { nama: "Michelle", jantina: "perempuan", bahasa: "International", makna: "Siapakah seperti Allah", asal: "Nama Perancis dari Hebrew Mikail" },
  { nama: "Millie", jantina: "perempuan", bahasa: "International", makna: "Yang lembut, yang gigih", asal: "Nama pendek dari Millicent" },
  { nama: "Miranda", jantina: "perempuan", bahasa: "International", makna: "Yang patut dikagumi", asal: "Nama Latin bermaksud dikagumi" },
  { nama: "Molly", jantina: "perempuan", bahasa: "International", makna: "Bintang laut, yang cantik", asal: "Variasi dari Mary bermaksud dikasihi" },
  { nama: "Monica", jantina: "perempuan", bahasa: "International", makna: "Yang bersendirian, yang menasihat", asal: "Nama Latin bermaksud penasihat" },
  { nama: "Morgan", jantina: "perempuan", bahasa: "International", makna: "Pejuang laut yang kuat", asal: "Nama Welsh bermaksud laut" },
  { nama: "Nadia", jantina: "perempuan", bahasa: "International", makna: "Yang penuh harapan", asal: "Nama Slavic bermaksud harapan" },
  { nama: "Natalia", jantina: "perempuan", bahasa: "International", makna: "Hari lahir, yang dilahirkan", asal: "Nama Latin bermaksud hari lahir" },
  { nama: "Natalie", jantina: "perempuan", bahasa: "International", makna: "Hari Natal, yang dilahirkan", asal: "Nama Latin bermaksud lahir" },
  { nama: "Nicole", jantina: "perempuan", bahasa: "International", makna: "Kemenangan rakyat", asal: "Nama Greek bermaksud kemenangan" },
  { nama: "Nina", jantina: "perempuan", bahasa: "International", makna: "Yang cantik, yang kuat", asal: "Nama Spanish bermaksud cantik" },
  { nama: "Nora", jantina: "perempuan", bahasa: "International", makna: "Cahaya, yang bersinar", asal: "Nama Ireland bermaksud cahaya" },
  { nama: "Olivia", jantina: "perempuan", bahasa: "International", makna: "Pokok zaitun, keamanan", asal: "Nama Latin bermaksud zaitun", popular: true },
  { nama: "Paige", jantina: "perempuan", bahasa: "International", makna: "Pesuruh, yang membantu", asal: "Nama English bermaksud pesuruh" },
  { nama: "Penelope", jantina: "perempuan", bahasa: "International", makna: "Yang setia menunggu", asal: "Nama Greek bermaksud setia" },
  { nama: "Phoebe", jantina: "perempuan", bahasa: "International", makna: "Yang bersinar terang", asal: "Nama Greek bermaksud bersinar" },
  { nama: "Piper", jantina: "perempuan", bahasa: "International", makna: "Pemain paip, yang berbakat", asal: "Nama English bermaksud pemain" },
  { nama: "Poppy", jantina: "perempuan", bahasa: "International", makna: "Bunga poppy yang cantik", asal: "Nama English dari bunga poppy" },
  { nama: "Priya", jantina: "perempuan", bahasa: "International", makna: "Yang dikasihi, yang sayang", asal: "Nama Sanskrit bermaksud dikasihi" },
  { nama: "Quinn", jantina: "perempuan", bahasa: "International", makna: "Yang bijaksana, ketua", asal: "Nama Ireland bermaksud bijak" },
  { nama: "Rachel", jantina: "perempuan", bahasa: "International", makna: "Anak biri-biri, yang lembut", asal: "Nama Hebrew bermaksud lemah lembut" },
  { nama: "Rebecca", jantina: "perempuan", bahasa: "International", makna: "Yang menjerat, yang menarik", asal: "Nama Hebrew bermaksud menarik" },
  { nama: "Riley", jantina: "perempuan", bahasa: "International", makna: "Padang yang berani", asal: "Nama Ireland bermaksud berani" },
  { nama: "Rose", jantina: "perempuan", bahasa: "International", makna: "Bunga ros yang cantik", asal: "Nama Latin dari bunga ros" },
  { nama: "Rosie", jantina: "perempuan", bahasa: "International", makna: "Bunga ros yang manis", asal: "Nama pendek dari Rose" },
  { nama: "Ruby", jantina: "perempuan", bahasa: "International", makna: "Permata merah, yang berharga", asal: "Nama Latin dari permata ruby" },
  { nama: "Sadie", jantina: "perempuan", bahasa: "International", makna: "Puteri, yang mulia", asal: "Nama pendek dari Sarah" },
  { nama: "Samantha", jantina: "perempuan", bahasa: "International", makna: "Allah mendengar", asal: "Nama Hebrew bermaksud Allah mendengar" },
  { nama: "Sarah", jantina: "perempuan", bahasa: "International", makna: "Puteri, yang mulia", asal: "Nama Hebrew bermaksud puteri" },
  { nama: "Savannah", jantina: "perempuan", bahasa: "International", makna: "Padang rumput yang luas", asal: "Nama dari padang savannah" },
  { nama: "Scarlett", jantina: "perempuan", bahasa: "International", makna: "Merah yang cantik dan berani", asal: "Nama English bermaksud merah" },
  { nama: "Selena", jantina: "perempuan", bahasa: "International", makna: "Dewi bulan, yang bercahaya", asal: "Nama Greek bermaksud bulan" },
  { nama: "Seraphina", jantina: "perempuan", bahasa: "International", makna: "Malaikat yang menyala-nyala", asal: "Nama Hebrew bermaksud malaikat" },
  { nama: "Sienna", jantina: "perempuan", bahasa: "International", makna: "Warna tanah yang hangat", asal: "Nama Italian dari kota Siena" },
  { nama: "Skye", jantina: "perempuan", bahasa: "International", makna: "Langit, yang luas dan bebas", asal: "Nama Scotland bermaksud langit" },
  { nama: "Skyler", jantina: "perempuan", bahasa: "International", makna: "Cendekiawan, yang bijak", asal: "Nama Dutch bermaksud cendekiawan" },
  { nama: "Sophia", jantina: "perempuan", bahasa: "International", makna: "Kebijaksanaan yang sempurna", asal: "Nama Greek bermaksud bijak", popular: true },
  { nama: "Sophie", jantina: "perempuan", bahasa: "International", makna: "Kebijaksanaan, yang bijak", asal: "Nama Perancis bermaksud bijak" },
  { nama: "Stella", jantina: "perempuan", bahasa: "International", makna: "Bintang, yang bersinar terang", asal: "Nama Latin bermaksud bintang" },
  { nama: "Summer", jantina: "perempuan", bahasa: "International", makna: "Musim panas, yang ceria", asal: "Nama English bermaksud musim panas" },
  { nama: "Valentina", jantina: "perempuan", bahasa: "International", makna: "Yang kuat dan sihat", asal: "Nama Latin bermaksud kuat" },
  { nama: "Valeria", jantina: "perempuan", bahasa: "International", makna: "Yang kuat dan sihat", asal: "Nama Latin bermaksud kuat" },
  { nama: "Victoria", jantina: "perempuan", bahasa: "International", makna: "Kemenangan, yang menang", asal: "Nama Latin bermaksud kemenangan" },
  { nama: "Violet", jantina: "perempuan", bahasa: "International", makna: "Bunga violet yang cantik", asal: "Nama Latin dari bunga violet" },
  { nama: "Vivian", jantina: "perempuan", bahasa: "International", makna: "Yang hidup, yang bersemangat", asal: "Nama Latin bermaksud hidup" },
  { nama: "Willa", jantina: "perempuan", bahasa: "International", makna: "Yang berkehendak kuat", asal: "Nama German bermaksud berkehendak" },
  { nama: "Willow", jantina: "perempuan", bahasa: "International", makna: "Pokok willow, yang lembut", asal: "Nama English dari pokok willow" },
  { nama: "Wren", jantina: "perempuan", bahasa: "International", makna: "Burung kecil yang merdu", asal: "Nama English dari burung wren" },
  { nama: "Xanthe", jantina: "perempuan", bahasa: "International", makna: "Yang keemasan, yang bercahaya", asal: "Nama Greek bermaksud keemasan" },
  { nama: "Xiomara", jantina: "perempuan", bahasa: "International", makna: "Pejuang yang terkenal", asal: "Nama Spanish bermaksud pejuang" },
  { nama: "Yasmine", jantina: "perempuan", bahasa: "International", makna: "Bunga jasmine yang harum", asal: "Variasi dari Yasmin" },
  { nama: "Zara", jantina: "perempuan", bahasa: "International", makna: "Bunga, yang bersinar cantik", asal: "Nama Arab yang popular global" },
  { nama: "Zoe", jantina: "perempuan", bahasa: "International", makna: "Kehidupan, yang penuh hidup", asal: "Nama Greek bermaksud kehidupan" },
  { nama: "Zoey", jantina: "perempuan", bahasa: "International", makna: "Kehidupan yang indah", asal: "Variasi dari Zoe bermaksud hidup" },
  { nama: "Zola", jantina: "perempuan", bahasa: "International", makna: "Tanah, yang kukuh", asal: "Nama Afrika bermaksud tanah" },
];
