// MAMAEXPERT — nama-data-1.js
// Arab Lelaki — 300 nama

const namaArabLelaki = [
  { nama: "Muhammad", makna: "Yang terpuji, nama Nabi S.A.W", asal: "Dari kata hamd bermaksud pujian", popular: true },
  { nama: "Ahmad", makna: "Yang paling terpuji", asal: "Nama lain Nabi Muhammad S.A.W", popular: true },
  { nama: "Rayyan", makna: "Pintu syurga khas untuk orang yang berpuasa", asal: "Disebutkan dalam hadis Nabi S.A.W", popular: true },
  { nama: "Ali", makna: "Yang tinggi, mulia", asal: "Nama Khalifah Islam keempat", popular: true },
  { nama: "Umar", makna: "Umur panjang, berkembang maju", asal: "Nama Khalifah Islam kedua" },
  { nama: "Uthman", makna: "Yang lembut, yang penyayang", asal: "Nama Khalifah Islam ketiga" },
  { nama: "Abu Bakar", makna: "Bapa unta muda, yang mulia", asal: "Nama Khalifah Islam pertama" },
  { nama: "Irfan", makna: "Pengetahuan dan kebijaksanaan yang mendalam", asal: "Dari kata arafa bermaksud mengetahui" },
  { nama: "Hakim", makna: "Yang bijaksana, hakim yang adil", asal: "Salah satu nama Asmaul Husna" },
  { nama: "Zafran", makna: "Bunga kesturi yang harum", asal: "Nama bunga yang harum dalam bahasa Arab" },
  { nama: "Imran", makna: "Kemakmuran, nama bapa Nabi Musa A.S", asal: "Disebut dalam Al-Quran surah Ali Imran" },
  { nama: "Harith", makna: "Petani yang rajin, yang berjuang", asal: "Nama sahabat Nabi S.A.W" },
  { nama: "Qasim", makna: "Yang membahagi dengan adil", asal: "Nama putera Nabi Muhammad S.A.W" },
  { nama: "Hassan", makna: "Yang tampan, yang baik", asal: "Nama cucu Nabi Muhammad S.A.W" },
  { nama: "Hussain", makna: "Yang cantik, yang baik sekali", asal: "Nama cucu Nabi Muhammad S.A.W" },
  { nama: "Ibrahim", makna: "Bapa kepada banyak bangsa", asal: "Nama Nabi Ibrahim A.S" },
  { nama: "Ismail", makna: "Allah mendengar", asal: "Nama Nabi Ismail A.S" },
  { nama: "Idris", makna: "Yang tekun belajar, pintar", asal: "Nama Nabi Idris A.S" },
  { nama: "Luqman", makna: "Yang bijaksana", asal: "Disebut dalam Al-Quran sebagai orang yang diberi hikmah" },
  { nama: "Naufal", makna: "Yang pemurah, yang banyak memberi", asal: "Dari kata nafala bermaksud memberi lebih" },
  { nama: "Faris", makna: "Penunggang kuda, pahlawan", asal: "Gelaran kepada pahlawan yang gagah berani" },
  { nama: "Aiman", makna: "Yang bertuah, yang diberkati", asal: "Dari kata yumn bermaksud keberkatan" },
  { nama: "Syafiq", makna: "Yang penyayang, yang lembut hati", asal: "Dari kata syafaqa bermaksud belas kasihan" },
  { nama: "Fikri", makna: "Yang berfikiran, yang cerdas", asal: "Dari kata fikr bermaksud pemikiran" },
  { nama: "Hafiz", makna: "Penghafaz Al-Quran, yang memelihara", asal: "Salah satu nama Allah Al-Hafiz" },
  { nama: "Yusuf", makna: "Allah menambah, yang cantik", asal: "Nama Nabi Yusuf A.S" },
  { nama: "Musa", makna: "Diselamatkan dari air", asal: "Nama Nabi Musa A.S" },
  { nama: "Isa", makna: "Allah menyelamatkan", asal: "Nama Nabi Isa A.S" },
  { nama: "Yahya", makna: "Yang hidup, yang menghidupkan", asal: "Nama Nabi Yahya A.S" },
  { nama: "Daud", makna: "Yang dicintai", asal: "Nama Nabi Daud A.S" },
  { nama: "Sulaiman", makna: "Orang yang sejahtera", asal: "Nama Nabi Sulaiman A.S" },
  { nama: "Zakaria", makna: "Allah mengingatkan", asal: "Nama Nabi Zakaria A.S" },
  { nama: "Hud", makna: "Yang membimbing ke jalan benar", asal: "Nama Nabi Hud A.S" },
  { nama: "Saleh", makna: "Yang soleh, yang baik", asal: "Nama Nabi Saleh A.S" },
  { nama: "Yunus", makna: "Merpati, yang bersemangat", asal: "Nama Nabi Yunus A.S" },
  { nama: "Ilyas", makna: "Allah adalah Tuhanku", asal: "Nama Nabi Ilyas A.S" },
  { nama: "Zulkifli", makna: "Yang mempunyai keistimewaan", asal: "Nama Nabi Zulkifli A.S" },
  { nama: "Syuaib", makna: "Yang membara, yang bersemangat", asal: "Nama Nabi Syuaib A.S" },
  { nama: "Ridhwan", makna: "Keredhaan, nama penjaga syurga", asal: "Disebutkan dalam hadis sebagai penjaga syurga" },
  { nama: "Taufiq", makna: "Pertolongan Allah, kejayaan", asal: "Dari kata waffaqa bermaksud berjaya" },
  { nama: "Rashid", makna: "Yang bijaksana, yang mendapat hidayah", asal: "Salah satu nama Allah Al-Rashid" },
  { nama: "Khairul", makna: "Yang terbaik", asal: "Dari kata khayr bermaksud kebaikan" },
  { nama: "Furqan", makna: "Pembeza antara hak dan batil", asal: "Nama lain Al-Quran" },
  { nama: "Ihsan", makna: "Kebaikan, berbuat baik dengan sempurna", asal: "Dari hadis Nabi tentang ihsan" },
  { nama: "Zikri", makna: "Ingatanku, zikirku kepada Allah", asal: "Dari kata dhikr bermaksud mengingati Allah" },
  { nama: "Asyraf", makna: "Yang paling mulia dan terhormat", asal: "Dari kata sharafa bermaksud mulia" },
  { nama: "Haikal", makna: "Berbadan tegap dan gagah", asal: "Bermaksud badan yang besar dan tegap" },
  { nama: "Izzat", makna: "Kemuliaan, kehormatan, kewibawaan", asal: "Dari kata izza bermaksud kemuliaan" },
  { nama: "Ziyad", makna: "Pertambahan, kemajuan", asal: "Dari kata zada bermaksud bertambah" },
  { nama: "Sabri", makna: "Yang sabar, yang tabah", asal: "Dari kata sabr bermaksud kesabaran" },
  { nama: "Aqil", makna: "Yang berakal, yang bijak", asal: "Dari kata aql bermaksud akal" },
  { nama: "Syamil", makna: "Yang menyeluruh, yang lengkap sempurna", asal: "Dari kata shamala bermaksud meliputi semua" },
  { nama: "Haris", makna: "Penjaga, yang melindungi", asal: "Dari kata harasa bermaksud menjaga" },
  { nama: "Zakwan", makna: "Yang tajam fikiran, yang cerdas", asal: "Dari kata dhaka bermaksud cerdas" },
  { nama: "Ammar", makna: "Yang makmur, pembina peradaban", asal: "Nama sahabat Nabi yang terkenal" },
  { nama: "Sufian", makna: "Yang cepat bergerak, yang tangkas", asal: "Nama sahabat Nabi yang terkenal" },
  { nama: "Amir", makna: "Pemimpin, putera", asal: "Gelaran raja dan pemimpin dalam Islam" },
  { nama: "Bilal", makna: "Kelembapan, nama muazzin pertama Islam", asal: "Nama sahabat Nabi yang azan pertama kali" },
  { nama: "Talha", makna: "Pokok pisang, yang mulia", asal: "Nama sahabat Nabi yang dijanjikan syurga" },
  { nama: "Zubair", makna: "Yang kuat, yang bijaksana", asal: "Nama sahabat Nabi yang dijanjikan syurga" },
  { nama: "Saad", makna: "Kebahagiaan, yang bertuah", asal: "Nama sahabat Nabi yang terkenal" },
  { nama: "Khalid", makna: "Yang kekal, yang abadi", asal: "Nama panglima Islam yang terkenal" },
  { nama: "Walid", makna: "Yang baru lahir, yang muda", asal: "Dari kata walada bermaksud melahirkan" },
  { nama: "Tariq", makna: "Bintang pagi, yang mengetuk pintu", asal: "Dari Al-Quran surah At-Tariq" },
  { nama: "Rauf", makna: "Yang penyayang, penuh belas kasihan", asal: "Salah satu nama Allah Al-Rauf" },
  { nama: "Faruq", makna: "Yang membezakan hak dan batil", asal: "Gelaran Khalifah Umar bin Al-Khattab" },
  { nama: "Muaz", makna: "Yang dilindungi, yang dijaga", asal: "Nama sahabat Nabi yang alim" },
  { nama: "Salman", makna: "Yang selamat, yang sejahtera", asal: "Nama sahabat Nabi yang terkenal" },
  { nama: "Hamzah", makna: "Singa, yang gagah perkasa", asal: "Nama bapa saudara Nabi, Singa Allah" },
  { nama: "Abbas", makna: "Singa yang garang, yang berani", asal: "Nama bapa saudara Nabi Muhammad S.A.W" },
  { nama: "Zaid", makna: "Pertumbuhan, yang bertambah", asal: "Nama anak angkat Nabi Muhammad S.A.W" },
  { nama: "Uwais", makna: "Serigala kecil, yang setia", asal: "Nama wali Allah yang terkenal" },
  { nama: "Mahdi", makna: "Yang mendapat hidayah, yang dibimbing", asal: "Bermaksud pemimpin yang mendapat petunjuk" },
  { nama: "Nabil", makna: "Yang mulia, yang cerdas", asal: "Dari kata nabala bermaksud mulia" },
  { nama: "Sami", makna: "Yang mendengar, yang tinggi", asal: "Dari kata samia bermaksud mendengar" },
  { nama: "Talib", makna: "Pelajar, yang mencari ilmu", asal: "Dari kata talaba bermaksud mencari" },
  { nama: "Wafiq", makna: "Yang setia, yang berjaya", asal: "Dari kata wafaqa bermaksud bersetuju" },
  { nama: "Afiq", makna: "Yang suci, yang menahan diri", asal: "Dari kata affa bermaksud suci" },
  { nama: "Hazim", makna: "Yang tegas dan berhati-hati", asal: "Dari kata hazama bermaksud tegas" },
  { nama: "Ilham", makna: "Inspirasi, ilham dari Allah", asal: "Dari kata alhama bermaksud mengilhamkan" },
  { nama: "Kamil", makna: "Yang sempurna, yang lengkap", asal: "Dari kata kamula bermaksud sempurna" },
  { nama: "Amri", makna: "Perintahku, kekuasaanku", asal: "Dari kata amara bermaksud memerintah" },
  { nama: "Badr", makna: "Bulan purnama, yang bercahaya penuh", asal: "Nama bulan purnama dalam bahasa Arab" },
  { nama: "Fawwaz", makna: "Yang berjaya, yang menang", asal: "Dari kata faza bermaksud berjaya" },
  { nama: "Ghazi", makna: "Pejuang, yang berjuang di jalan Allah", asal: "Dari kata ghaza bermaksud berperang" },
  { nama: "Jauhar", makna: "Permata, yang berharga", asal: "Dari kata jawhar bermaksud inti dan permata" },
  { nama: "Kamal", makna: "Kesempurnaan, yang mencapai puncak", asal: "Dari kata kamula bermaksud sempurna" },
  { nama: "Lutfi", makna: "Yang lembut, yang penuh kasih", asal: "Dari kata latafa bermaksud lembut" },
  { nama: "Munir", makna: "Yang bercahaya, yang menerangi", asal: "Dari kata anara bermaksud bercahaya" },
  { nama: "Naim", makna: "Yang hidup senang, yang mewah", asal: "Dari kata naama bermaksud nikmat" },
  { nama: "Qayyum", makna: "Yang kekal berdiri, yang maha teguh", asal: "Salah satu nama Allah Al-Qayyum" },
  { nama: "Syukri", makna: "Yang bersyukur, penuh rasa terima kasih", asal: "Dari kata syakara bermaksud bersyukur" },
  { nama: "Tajuddin", makna: "Mahkota agama", asal: "Gabungan taj dan din bermaksud mahkota Islam" },
  { nama: "Wahid", makna: "Yang tunggal, yang unik", asal: "Salah satu nama Allah Al-Wahid" },
  { nama: "Yasin", makna: "Nama surah dalam Al-Quran, jantung Quran", asal: "Dari Al-Quran surah Yasin" },
  { nama: "Zafir", makna: "Yang menang, yang berjaya", asal: "Dari kata zafara bermaksud menang" },
  { nama: "Amin", makna: "Yang amanah, yang dipercayai", asal: "Gelaran Nabi Muhammad sebelum kenabian" },
  { nama: "Danial", makna: "Allah adalah hakimku", asal: "Nama nabi dalam tradisi Abrahamic" },
  { nama: "Fadli", makna: "Kelebihan, kurniaan Allah", asal: "Dari kata fadl bermaksud kelebihan" },
  { nama: "Ghufran", makna: "Keampunan Allah yang luas", asal: "Dari kata ghafara bermaksud mengampuni" },
  { nama: "Iqbal", makna: "Kemakmuran, yang menghadap ke depan", asal: "Dari kata aqbala bermaksud menghadap" },
  { nama: "Jamal", makna: "Kecantikan, yang cantik wajahnya", asal: "Dari kata jamala bermaksud cantik" },
  { nama: "Marwan", makna: "Batu karang, yang teguh", asal: "Nama khalifah Bani Umayyah" },
  { nama: "Riyad", makna: "Taman-taman yang indah", asal: "Dari kata rawdha bermaksud taman" },
  { nama: "Siraj", makna: "Pelita, yang menerangi jalan", asal: "Dari kata siraj bermaksud lampu" },
  { nama: "Uzair", makna: "Pertolongan Allah", asal: "Nama nabi yang disebutkan dalam Al-Quran" },
  { nama: "Izzuddin", makna: "Kemuliaan agama", asal: "Gabungan izza dan din" },
  { nama: "Nuruddin", makna: "Cahaya agama", asal: "Gabungan nur dan din" },
  { nama: "Tajul", makna: "Mahkota, yang bermahkota", asal: "Dari kata taj bermaksud mahkota" },
  { nama: "Fathullah", makna: "Kemenangan dari Allah", asal: "Gabungan fath dan Allah" },
  { nama: "Saifuddin", makna: "Pedang agama", asal: "Gabungan saif dan din bermaksud pedang Islam" },
  { nama: "Burhanuddin", makna: "Bukti agama", asal: "Gabungan burhan dan din bermaksud bukti Islam" },
  { nama: "Jamaluddin", makna: "Kecantikan agama", asal: "Gabungan jamal dan din bermaksud keindahan Islam" },
  { nama: "Nasruddin", makna: "Kemenangan agama", asal: "Gabungan nasr dan din bermaksud kemenangan Islam" },
  { nama: "Bahauddin", makna: "Keindahan agama", asal: "Gabungan baha dan din bermaksud keindahan agama" },
  { nama: "Salahudin", makna: "Kebaikan agama", asal: "Nama panglima Islam yang terkenal" },
  { nama: "Alauddin", makna: "Ketinggian agama", asal: "Gabungan ala dan din bermaksud tinggi agama" },
  { nama: "Aminuddin", makna: "Amanah agama", asal: "Gabungan amin dan din bermaksud kepercayaan agama" },
  { nama: "Fakhruddin", makna: "Kebanggaan agama", asal: "Gabungan fakhr dan din bermaksud kebanggaan agama" },
  { nama: "Qutbuddin", makna: "Tiang agama", asal: "Gabungan qutb dan din bermaksud paksi agama" },
  { nama: "Shihabuddin", makna: "Bintang agama", asal: "Gabungan shihab dan din bermaksud bintang Islam" },
  { nama: "Asadullah", makna: "Singa Allah", asal: "Gelaran Saidina Ali bin Abi Talib" },
  { nama: "Saifullah", makna: "Pedang Allah", asal: "Gelaran panglima Khalid bin Walid" },
  { nama: "Abdullah", makna: "Hamba Allah", asal: "Nama paling mulia dalam Islam" },
  { nama: "Abdurrahman", makna: "Hamba yang Maha Pengasih", asal: "Nama yang paling disukai Allah" },
  { nama: "Abdulaziz", makna: "Hamba yang Maha Perkasa", asal: "Dari nama Allah Al-Aziz" },
  { nama: "Abdulhakim", makna: "Hamba yang Maha Bijaksana", asal: "Dari nama Allah Al-Hakim" },
  { nama: "Abdulqadir", makna: "Hamba yang Maha Berkuasa", asal: "Dari nama Allah Al-Qadir" },
  { nama: "Abdulrahim", makna: "Hamba yang Maha Penyayang", asal: "Dari nama Allah Al-Rahim" },
  { nama: "Abdulkareem", makna: "Hamba yang Maha Mulia", asal: "Dari nama Allah Al-Karim" },
  { nama: "Abdullatif", makna: "Hamba yang Maha Lembut", asal: "Dari nama Allah Al-Latif" },
  { nama: "Abdulmalik", makna: "Hamba yang Maha Merajai", asal: "Dari nama Allah Al-Malik" },
  { nama: "Abdulmuhsin", makna: "Hamba yang Maha Memberi Kebaikan", asal: "Dari sifat Allah Al-Muhsin" },
  { nama: "Abdulwahab", makna: "Hamba yang Maha Pemberi", asal: "Dari nama Allah Al-Wahhab" },
  { nama: "Abduljalil", makna: "Hamba yang Maha Agung", asal: "Dari nama Allah Al-Jalil" },
  { nama: "Abdulhadi", makna: "Hamba yang Maha Memberi Petunjuk", asal: "Dari nama Allah Al-Hadi" },
  { nama: "Abdussalam", makna: "Hamba yang Maha Sejahtera", asal: "Dari nama Allah Al-Salam" },
  { nama: "Abdurahman", makna: "Hamba yang Maha Pengasih", asal: "Variasi dari Abdurrahman" },
  { nama: "Ubaidullah", makna: "Hamba kecil Allah", asal: "Dari kata abada bermaksud beribadah" },
  { nama: "Habibullah", makna: "Kekasih Allah", asal: "Gelaran Nabi Muhammad S.A.W" },
  { nama: "Nasrullah", makna: "Pertolongan Allah", asal: "Dari kata nasr bermaksud kemenangan" },
  { nama: "Rahmatullah", makna: "Rahmat Allah", asal: "Dari kata rahma bermaksud kasih sayang" },
  { nama: "Nurullah", makna: "Cahaya Allah", asal: "Gabungan nur dan Allah bermaksud cahaya Tuhan" },
  { nama: "Fadlullah", makna: "Kelebihan Allah", asal: "Dari kata fadl bermaksud kelebihan dan anugerah" },
  { nama: "Karamullah", makna: "Kemuliaan Allah", asal: "Dari kata karam bermaksud kemuliaan" },
  { nama: "Atiqullah", makna: "Yang dimerdekakan Allah", asal: "Dari kata atiqa bermaksud bebas" },
  { nama: "Tawfiqullah", makna: "Pertolongan dan taufiq dari Allah", asal: "Dari kata tawfiq bermaksud pertolongan" },
  { nama: "Hibbatullah", makna: "Hadiah dari Allah", asal: "Dari kata hibba bermaksud hadiah" },
  { nama: "Jibril", makna: "Malaikat utusan Allah", asal: "Nama malaikat yang membawa wahyu" },
  { nama: "Mikail", makna: "Malaikat yang mengurus rezeki", asal: "Nama malaikat yang disebutkan dalam Quran" },
  { nama: "Israfil", makna: "Malaikat peniup sangkakala", asal: "Nama malaikat akhir zaman" },
  { nama: "Aqib", makna: "Yang terakhir, yang terkemudian", asal: "Nama lain Nabi Muhammad S.A.W" },
  { nama: "Hasyim", makna: "Yang menghancurkan, yang memberi makan", asal: "Nama moyang Nabi Muhammad S.A.W" },
  { nama: "Muttalib", makna: "Yang mencari, yang menuntut", asal: "Nama moyang Nabi Muhammad S.A.W" },
  { nama: "Nawawi", makna: "Yang hidup subur, yang berkembang", asal: "Dinisbahkan kepada Imam Nawawi" },
  { nama: "Ghazali", makna: "Yang berkaitan dengan tenun atau kota Ghazalah", asal: "Dinisbahkan kepada Imam Al-Ghazali" },
  { nama: "Bukhari", makna: "Yang berasal dari Bukhara", asal: "Dinisbahkan kepada Imam Al-Bukhari" },
  { nama: "Tirmizi", makna: "Yang berasal dari Tirmiz", asal: "Dinisbahkan kepada Imam At-Tirmizi" },
  { nama: "Syafi", makna: "Yang memberi syafaat, yang menyembuhkan", asal: "Dinisbahkan kepada Imam Al-Syafii" },
  { nama: "Raif", makna: "Yang penuh kasih sayang", asal: "Dari kata rafa bermaksud belas kasihan" },
  { nama: "Mukhtar", makna: "Yang terpilih, yang dipilih", asal: "Dari kata ikhtara bermaksud memilih" },
  { nama: "Mukhlis", makna: "Yang ikhlas, yang tulus hati", asal: "Dari kata akhlasa bermaksud ikhlas" },
  { nama: "Mukhriz", makna: "Yang berjaya, yang lulus cemerlang", asal: "Dari kata akhraja bermaksud mengeluarkan" },
  { nama: "Mufid", makna: "Yang memberi manfaat, yang berguna", asal: "Dari kata afada bermaksud memberi faedah" },
  { nama: "Mufiz", makna: "Yang menang dengan cemerlang", asal: "Dari kata faza bermaksud menang" },
  { nama: "Murtada", makna: "Yang diredhai, yang dipilih", asal: "Dari kata irtada bermaksud redha" },
  { nama: "Musab", makna: "Yang kuat seperti batu, yang teguh", asal: "Nama sahabat Nabi yang terkenal" },
  { nama: "Musaid", makna: "Yang membantu, yang menolong", asal: "Dari kata saada bermaksud membantu" },
  { nama: "Mustafa", makna: "Yang terpilih, yang dipilih", asal: "Nama dan gelaran Nabi Muhammad S.A.W" },
  { nama: "Mutasim", makna: "Yang berpegang teguh kepada Allah", asal: "Dari kata itasama bermaksud berpegang" },
  { nama: "Muzaffar", makna: "Yang menang, yang berjaya", asal: "Dari kata zafara bermaksud menang" },
  { nama: "Nafis", makna: "Yang berharga, yang bernilai tinggi", asal: "Dari kata nafasa bermaksud berharga" },
  { nama: "Najih", makna: "Yang berjaya, yang lulus", asal: "Dari kata najaha bermaksud berjaya" },
  { nama: "Nasim", makna: "Angin sepoi-sepoi, yang segar", asal: "Dari kata nasama bermaksud angin lembut" },
  { nama: "Nasir", makna: "Yang menolong, yang membela", asal: "Dari kata nasara bermaksud menolong" },
  { nama: "Nawfal", makna: "Yang pemurah, yang memberi banyak", asal: "Variasi dari Naufal" },
  { nama: "Nazim", makna: "Yang teratur, yang menyusun", asal: "Dari kata nazama bermaksud menyusun" },
  { nama: "Nazir", makna: "Yang memberi amaran, yang mengawasi", asal: "Dari kata nadhara bermaksud mengawasi" },
  { nama: "Nouman", makna: "Darah, yang bersemangat", asal: "Dari kata naama bermaksud nikmat" },
  { nama: "Numan", makna: "Yang penuh nikmat dan kesenangan", asal: "Nama sahabat Nabi yang terkenal" },
  { nama: "Obaid", makna: "Hamba kecil, yang beribadah", asal: "Dari kata abada bermaksud beribadah" },
  { nama: "Omer", makna: "Umur panjang, kehidupan yang makmur", asal: "Variasi dari Umar" },
  { nama: "Osama", makna: "Singa, yang gagah berani", asal: "Dari kata asima bermaksud singa" },
  { nama: "Qays", makna: "Yang kuat, yang teguh", asal: "Nama pejuang Arab yang terkenal" },
  { nama: "Qudamah", makna: "Yang berani, yang maju ke hadapan", asal: "Nama sahabat Nabi yang terkenal" },
  { nama: "Rabih", makna: "Yang mendapat keuntungan, yang menang", asal: "Dari kata rabiha bermaksud untung" },
  { nama: "Radi", makna: "Yang redha, yang puas hati", asal: "Dari kata radha bermaksud redha" },
  { nama: "Rafi", makna: "Yang tinggi, yang mulia", asal: "Dari kata rafa bermaksud tinggi" },
  { nama: "Ragib", makna: "Yang berhasrat, yang berkeinginan", asal: "Dari kata ragiba bermaksud berkeinginan" },
  { nama: "Ramadan", makna: "Bulan puasa yang mulia", asal: "Nama bulan suci dalam Islam" },
  { nama: "Ramzi", makna: "Simbol, tanda yang bermakna", asal: "Dari kata ramaza bermaksud memberi isyarat" },
  { nama: "Razi", makna: "Yang redha, yang berpuas hati", asal: "Dari kata radha bermaksud redha" },
  { nama: "Rifaat", makna: "Ketinggian, kemuliaan darjat", asal: "Dari kata rafa bermaksud tinggi" },
  { nama: "Rif", makna: "Yang subur, yang makmur", asal: "Dari kata rafa bermaksud subur" },
  { nama: "Riyaz", makna: "Taman, yang subur dan indah", asal: "Dari kata rawdha bermaksud taman" },
  { nama: "Rukan", makna: "Yang teguh, yang stabil", asal: "Dari kata rakana bermaksud teguh" },
  { nama: "Rushdi", makna: "Kematangan, petunjuk yang benar", asal: "Dari kata rashada bermaksud matang" },
  { nama: "Saami", makna: "Yang mendengar, yang mulia", asal: "Dari kata samia bermaksud mendengar" },
  { nama: "Sabiq", makna: "Yang mendahului, yang terdepan", asal: "Dari kata sabaqa bermaksud mendahului" },
  { nama: "Sadiq", makna: "Yang jujur, yang benar", asal: "Dari kata sadaqa bermaksud jujur" },
  { nama: "Safir", makna: "Duta, utusan yang mulia", asal: "Dari kata safara bermaksud duta" },
  { nama: "Sahil", makna: "Pantai, yang mudah", asal: "Dari kata sahala bermaksud mudah" },
  { nama: "Saif", makna: "Pedang, yang tajam dan kuat", asal: "Dari kata saif bermaksud pedang" },
  { nama: "Sajid", makna: "Yang bersujud, yang taat beribadah", asal: "Dari kata sajada bermaksud bersujud" },
  { nama: "Salim", makna: "Yang sejahtera, yang sihat", asal: "Dari kata salima bermaksud sejahtera" },
  { nama: "Samih", makna: "Yang murah hati, yang memaafkan", asal: "Dari kata samaha bermaksud memaafkan" },
  { nama: "Saqib", makna: "Bintang yang bersinar terang", asal: "Dari kata thaqaba bermaksud bersinar" },
  { nama: "Sarhan", makna: "Serigala, yang bebas", asal: "Dari kata saraha bermaksud bebas" },
  { nama: "Sarwar", makna: "Ketua, pemimpin yang mulia", asal: "Dari bahasa Parsi bermaksud pemimpin" },
  { nama: "Shaban", makna: "Bulan kelapan dalam kalender Islam", asal: "Bulan mulia sebelum Ramadan" },
  { nama: "Shafiq", makna: "Yang penyayang, yang mengambil berat", asal: "Dari kata syafaqa bermaksud belas kasihan" },
  { nama: "Shaheen", makna: "Helang, yang gagah dan bebas", asal: "Dari bahasa Parsi bermaksud helang diraja" },
  { nama: "Shahid", makna: "Syahid, saksi, yang hadir", asal: "Dari kata shahida bermaksud menyaksi" },
  { nama: "Shahir", makna: "Yang masyhur, yang terkenal", asal: "Dari kata shahara bermaksud masyhur" },
  { nama: "Shahin", makna: "Helang putih, yang mulia", asal: "Dari bahasa Parsi bermaksud helang yang mulia" },
  { nama: "Shakir", makna: "Yang bersyukur", asal: "Dari kata syakara bermaksud bersyukur" },
  { nama: "Shamil", makna: "Yang menyeluruh, yang lengkap", asal: "Variasi dari Syamil" },
  { nama: "Shamsuddin", makna: "Matahari agama", asal: "Gabungan syams dan din bermaksud matahari Islam" },
  { nama: "Shareef", makna: "Yang mulia, yang terhormat", asal: "Dari kata sharafa bermaksud mulia" },
  { nama: "Shawqi", makna: "Rindu, yang dipenuhi kerinduan", asal: "Dari kata shawq bermaksud rindu" },
  { nama: "Siddiq", makna: "Yang sangat jujur, yang membenarkan", asal: "Gelaran Abu Bakar As-Siddiq" },
  { nama: "Subhan", makna: "Maha Suci, pujian kepada Allah", asal: "Dari kata subhana bermaksud maha suci" },
  { nama: "Suhaib", makna: "Rambut perang, yang kuat", asal: "Nama sahabat Nabi yang terkenal" },
  { nama: "Suhail", makna: "Mudah, bintang Canopus", asal: "Dari kata sahala bermaksud mudah" },
  { nama: "Sulayman", makna: "Orang yang sejahtera", asal: "Variasi dari Sulaiman" },
  { nama: "Sultan", makna: "Penguasa, yang berkuasa", asal: "Dari kata sultana bermaksud berkuasa" },
  { nama: "Syarif", makna: "Yang mulia, yang terhormat", asal: "Dari kata sharafa bermaksud mulia" },
  { nama: "Tabarak", makna: "Yang diberkati, yang penuh berkat", asal: "Dari kata baraka bermaksud berkat" },
  { nama: "Taha", makna: "Nama surah dalam Al-Quran", asal: "Dari Al-Quran surah Taha, panggilan kepada Nabi" },
  { nama: "Tahir", makna: "Yang suci, yang bersih", asal: "Dari kata tahara bermaksud suci" },
  { nama: "Talal", makna: "Hujan yang lebat, yang menyuburkan", asal: "Dari kata talla bermaksud hujan lebat" },
  { nama: "Tamim", makna: "Yang sempurna, yang kuat", asal: "Nama sahabat Nabi yang terkenal" },
  { nama: "Tarif", makna: "Yang mulia, yang unik", asal: "Dari kata tarafa bermaksud unik" },
  { nama: "Tawfeeq", makna: "Kejayaan, pertolongan Allah", asal: "Variasi dari Taufiq" },
  { nama: "Taysir", makna: "Kemudahan, yang memudahkan", asal: "Dari kata yasara bermaksud mudah" },
  { nama: "Thaabit", makna: "Yang teguh, yang stabil", asal: "Dari kata thabata bermaksud teguh" },
  { nama: "Thaqib", makna: "Bintang yang bersinar menembusi", asal: "Dari kata thaqaba bermaksud menembus" },
  { nama: "Thariq", makna: "Bintang pagi, yang mengetuk", asal: "Variasi dari Tariq" },
  { nama: "Ubay", makna: "Yang tinggi hati, yang mulia", asal: "Nama sahabat Nabi yang alim" },
  { nama: "Umayr", makna: "Yang berumur panjang", asal: "Nama sahabat Nabi yang terkenal" },
  { nama: "Uqbah", makna: "Bukit, yang tinggi dan kuat", asal: "Nama sahabat Nabi yang terkenal" },
  { nama: "Urwah", makna: "Pegangan, yang kuat berpegang", asal: "Nama sahabat Nabi yang terkenal" },
  { nama: "Usaid", makna: "Singa kecil, yang berani", asal: "Nama sahabat Nabi yang terkenal" },
  { nama: "Usamah", makna: "Singa, yang gagah berani", asal: "Dari kata asima bermaksud singa" },
  { nama: "Waseem", makna: "Yang tampan, yang elok rupa", asal: "Dari kata wasama bermaksud cantik" },
  { nama: "Wissam", makna: "Medal kehormatan, tanda mulia", asal: "Dari kata wasama bermaksud tanda mulia" },
  { nama: "Yahyaa", makna: "Yang hidup, yang memberi kehidupan", asal: "Variasi dari Yahya" },
  { nama: "Yaqub", makna: "Menggantikan, nama Nabi Yaakub A.S", asal: "Nama Nabi Yaakub A.S" },
  { nama: "Yasir", makna: "Yang mudah, yang kaya", asal: "Dari kata yasara bermaksud mudah" },
  { nama: "Yazdan", makna: "Tuhan, yang ilahi", asal: "Dari bahasa Parsi bermaksud yang ilahi" },
  { nama: "Yusri", makna: "Yang mudah, yang bertuah", asal: "Dari kata yasara bermaksud mudah" },
  { nama: "Zafarullah", makna: "Kemenangan Allah", asal: "Gabungan zafar dan Allah" },
  { nama: "Zahid", makna: "Yang zuhud, yang tidak tamak dunia", asal: "Dari kata zahada bermaksud zuhud" },
  { nama: "Zahran", makna: "Yang bersinar, yang cemerlang", asal: "Dari kata zahara bermaksud bersinar" },
  { nama: "Zain", makna: "Kecantikan, hiasan yang indah", asal: "Dari kata zana bermaksud cantik" },
  { nama: "Zainuddin", makna: "Hiasan agama, kecantikan agama", asal: "Gabungan zayn dan din" },
  { nama: "Zakiy", makna: "Yang suci, yang bijak", asal: "Dari kata zaka bermaksud suci" },
  { nama: "Zamil", makna: "Rakan, sahabat yang setia", asal: "Dari kata zamala bermaksud kawan" },
  { nama: "Ziaul", makna: "Cahaya, sinar yang menerangi", asal: "Dari kata dhiya bermaksud cahaya" },
  { nama: "Zubaidah", makna: "Mentega, yang terbaik", asal: "Dari kata zubd bermaksud mentega" },
  { nama: "Zuhair", makna: "Yang bersinar, bunga-bungaan", asal: "Dari kata zahara bermaksud bersinar" },
  { nama: "Zuhairi", makna: "Yang berkaitan dengan bunga", asal: "Dari kata zahara bermaksud bunga" },
  { nama: "Zuhri", makna: "Yang berkaitan dengan bunga, yang bersinar", asal: "Dinisbahkan kepada Imam Az-Zuhri" },
  { nama: "Zulfahmi", makna: "Yang memiliki kefahaman mendalam", asal: "Gabungan zul dan fahm bermaksud pemilik kefahaman" },
  { nama: "Zulhilmi", makna: "Yang memiliki kelembutan", asal: "Gabungan zul dan hilm" },
  { nama: "Zulhazmi", makna: "Yang memiliki ketegasan", asal: "Gabungan zul dan hazm" },
  { nama: "Zulqarnain", makna: "Yang bertanduk dua, raja yang agung", asal: "Disebutkan dalam Al-Quran surah Al-Kahfi" },
  { nama: "Thufail", makna: "Bayi yang baru lahir, yang lembut", asal: "Nama sahabat Nabi yang terkenal" },
  { nama: "Affan", makna: "Yang pemalu, yang menjaga kehormatan", asal: "Nama bapa Khalifah Uthman" },
  { nama: "Afnan", makna: "Dahan-dahan pokok yang rimbun", asal: "Dari Al-Quran surah Ar-Rahman" },
  { nama: "Ahsan", makna: "Yang terbaik, yang paling cantik", asal: "Dari kata husn bermaksud keindahan" },
  { nama: "Akhtar", makna: "Bintang, yang bersinar", asal: "Dari bahasa Parsi bermaksud bintang" },
  { nama: "Alif", makna: "Huruf pertama Arab, yang mula-mula", asal: "Dari huruf alif dalam abjad Arab" },
  { nama: "Ameen", makna: "Yang amanah, yang dipercayai", asal: "Variasi dari Amin" },
  { nama: "Amjad", makna: "Yang paling mulia, yang termulia", asal: "Dari kata majd bermaksud kemuliaan" },
  { nama: "Amr", makna: "Hidup, umur yang panjang", asal: "Nama sahabat Nabi yang terkenal" },
  { nama: "Anas", makna: "Yang mesra, yang ramah", asal: "Nama sahabat Nabi yang meriwayat hadis terbanyak" },
  { nama: "Anwar", makna: "Lebih bercahaya, yang paling terang", asal: "Dari kata nur bermaksud cahaya" },
  { nama: "Aqeel", makna: "Yang cerdas, yang berakal", asal: "Variasi dari Aqil" },
  { nama: "Arfan", makna: "Yang mengetahui, yang berpengetahuan", asal: "Variasi dari Irfan" },
  { nama: "Arham", makna: "Yang paling penyayang", asal: "Dari kata rahim bermaksud penyayang" },
  { nama: "Arif", makna: "Yang bijaksana, yang mengenal", asal: "Dari kata arafa bermaksud mengetahui" },
  { nama: "Arlan", makna: "Singa, yang gagah", asal: "Dari bahasa Turki bermaksud singa" },
  { nama: "Arslan", makna: "Singa, simbol keberanian", asal: "Nama Turki yang bermaksud singa" },
  { nama: "Asim", makna: "Yang menjaga, yang melindungi", asal: "Dari kata asama bermaksud menjaga" },
  { nama: "Asrar", makna: "Rahsia-rahsia, yang tersembunyi", asal: "Dari kata sirr bermaksud rahsia" },
  { nama: "Athar", makna: "Yang lebih suci, yang paling bersih", asal: "Dari kata tahara bermaksud suci" },
  { nama: "Athir", makna: "Yang disukai, yang dipilih", asal: "Dari kata athara bermaksud dipilih" },
  { nama: "Awad", makna: "Ganti rugi, yang memberi balasan", asal: "Dari kata awada bermaksud mengganti" },
  { nama: "Ayub", makna: "Yang kembali kepada Allah, nama Nabi", asal: "Nama Nabi Ayub A.S yang bersabar" },
  { nama: "Azam", makna: "Yang paling besar, yang agung", asal: "Dari kata azuma bermaksud agung" },
  { nama: "Azhar", makna: "Yang paling bersinar, yang paling terang", asal: "Dari kata zahara bermaksud bersinar" },
  { nama: "Azim", makna: "Yang agung, yang besar", asal: "Dari kata azuma bermaksud agung" },
  { nama: "Azizuddin", makna: "Kemuliaan agama yang perkasa", asal: "Gabungan aziz dan din" },
  { nama: "Azzam", makna: "Yang bersungguh-sungguh, yang bertekad", asal: "Dari kata azama bermaksud bertekad" },
];
