// MAMAEXPERT — nama-data-5.js
// Nama Melayu Perempuan — lengkap dan banyak

const namaMelayuPerempuanTambahan = [

  // ── HURUF A ──
  { nama: "Aarifah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mengetahui, yang arif", asal: "Dari kata Arab arafa bermaksud mengetahui" },
  { nama: "Aasiah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mengubati dan menyembuhkan", asal: "Variasi dari Asiah" },
  { nama: "Abidah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang tekun beribadah kepada Allah", asal: "Dari kata Arab abada bermaksud beribadah" },
  { nama: "Adibah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang bersopan santun dan beradab", asal: "Dari kata Arab aduba bermaksud beradab" },
  { nama: "Adila", jantina: "perempuan", bahasa: "Melayu", makna: "Yang adil dan saksama", asal: "Dari kata Arab adala bermaksud adil" },
  { nama: "Adilah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang adil, yang saksama", asal: "Dari kata Arab adala bermaksud adil" },
  { nama: "Adinda", jantina: "perempuan", bahasa: "Melayu", makna: "Adik yang disayangi", asal: "Kata Melayu bermaksud adik yang tersayang" },
  { nama: "Adira", jantina: "perempuan", bahasa: "Melayu", makna: "Yang kuat dan gagah", asal: "Dari kata Hebrew bermaksud kuat" },
  { nama: "Adlina", jantina: "perempuan", bahasa: "Melayu", makna: "Yang adil dan cantik", asal: "Dari kata Arab adala bermaksud adil" },
  { nama: "Adriana", jantina: "perempuan", bahasa: "Melayu", makna: "Yang gelap dan cantik", asal: "Variasi Melayu dari Latin Adriana" },
  { nama: "Afiqah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang suci dan menjaga kehormatan", asal: "Dari kata Arab affa bermaksud suci" },
  { nama: "Afiqha", jantina: "perempuan", bahasa: "Melayu", makna: "Yang suci, yang terpelihara", asal: "Variasi dari Afiqah bermaksud suci" },
  { nama: "Afiqhah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang suci hati dan terpelihara", asal: "Variasi dari Afiqah" },
  { nama: "Afiyah", jantina: "perempuan", bahasa: "Melayu", makna: "Kesihatan, yang sihat sejahtera", asal: "Dari kata Arab aafiya bermaksud sihat" },
  { nama: "Afizah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang menjaga dan memelihara", asal: "Dari kata Arab hafiza bermaksud menjaga" },
  { nama: "Afnan", jantina: "perempuan", bahasa: "Melayu", makna: "Dahan-dahan pokok yang rimbun", asal: "Dari Al-Quran surah Ar-Rahman" },
  { nama: "Afra", jantina: "perempuan", bahasa: "Melayu", makna: "Yang putih, yang bersih", asal: "Dari kata Arab afra bermaksud putih" },
  { nama: "Afrina", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan mengagumkan", asal: "Dari kata Arab afrina bermaksud cantik" },
  { nama: "Afwah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang harum baunya", asal: "Dari kata Arab fawh bermaksud harum" },
  { nama: "Aida", jantina: "perempuan", bahasa: "Melayu", makna: "Yang kembali, yang memberi manfaat", asal: "Dari kata Arab ada bermaksud kembali" },
  { nama: "Aidah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang memberi manfaat dan kebaikan", asal: "Dari kata Arab fada bermaksud manfaat" },
  { nama: "Aigerim", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik seperti bulan", asal: "Nama Kazakhstan bermaksud cantik" },
  { nama: "Aiman", jantina: "perempuan", bahasa: "Melayu", makna: "Yang bertuah dan diberkati", asal: "Dari kata Arab yumn bermaksud bertuah" },
  { nama: "Aimanah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang amanah dan dipercayai", asal: "Dari kata Arab amana bermaksud amanah" },
  { nama: "Aimy", jantina: "perempuan", bahasa: "Melayu", makna: "Yang dikasihi dan disayangi", asal: "Variasi Melayu dari Amy bermaksud dikasihi" },
  { nama: "Ain", jantina: "perempuan", bahasa: "Melayu", makna: "Mata yang indah, mata air", asal: "Dari kata Arab ain bermaksud mata" },
  { nama: "Ainaa", jantina: "perempuan", bahasa: "Melayu", makna: "Mata-mata yang cantik dan indah", asal: "Dari kata Arab ain bermaksud mata" },
  { nama: "Ainan", jantina: "perempuan", bahasa: "Melayu", makna: "Dua mata yang indah", asal: "Dari kata Arab ain bermaksud mata" },
  { nama: "Ainatul", jantina: "perempuan", bahasa: "Melayu", makna: "Mata yang indah bercahaya", asal: "Dari kata Arab ain bermaksud mata indah" },
  { nama: "Ainee", jantina: "perempuan", bahasa: "Melayu", makna: "Mataku, penyeri hatiku", asal: "Variasi Melayu dari Ain bermaksud mata" },
  { nama: "Aini", jantina: "perempuan", bahasa: "Melayu", makna: "Mataku, yang menjadi penyeri", asal: "Dari kata Arab ain bermaksud mata" },
  { nama: "Ainon", jantina: "perempuan", bahasa: "Melayu", makna: "Mata yang bersinar dan cantik", asal: "Variasi Melayu dari Ain bermaksud mata" },
  { nama: "Ainul Mardhiah", jantina: "perempuan", bahasa: "Melayu", makna: "Mata yang diredhai Allah", asal: "Gabungan ainul dan mardhiah" },
  { nama: "Ainur", jantina: "perempuan", bahasa: "Melayu", makna: "Mata cahaya, yang bersinar", asal: "Gabungan ain dan nur bermaksud cahaya" },
  { nama: "Aira", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan bersinar", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Airah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan menawan", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Aireen", jantina: "perempuan", bahasa: "Melayu", makna: "Yang damai dan tenang", asal: "Variasi Melayu bermaksud ketenangan" },
  { nama: "Airein", jantina: "perempuan", bahasa: "Melayu", makna: "Yang indah dan menyenangkan", asal: "Variasi Melayu bermaksud keindahan" },
  { nama: "Airena", jantina: "perempuan", bahasa: "Melayu", makna: "Yang damai dan cantik", asal: "Variasi Melayu bermaksud kedamaian" },
  { nama: "Airin", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan segar", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Aisha", jantina: "perempuan", bahasa: "Melayu", makna: "Yang hidup dan ceria", asal: "Variasi dari Aisyah bermaksud hidup" },
  { nama: "Aishabanu", jantina: "perempuan", bahasa: "Melayu", makna: "Puteri yang hidup dan ceria", asal: "Gabungan Aisyah dan banu bermaksud puteri" },
  { nama: "Aishath", jantina: "perempuan", bahasa: "Melayu", makna: "Yang hidup, yang ceria", asal: "Variasi Maladewa dari Aisyah" },
  { nama: "Aisya", jantina: "perempuan", bahasa: "Melayu", makna: "Yang hidup dan bahagia", asal: "Variasi Melayu dari Aisyah" },
  { nama: "Aisyah Humaira", jantina: "perempuan", bahasa: "Melayu", makna: "Yang hidup dan cantik kemerah-merahan", asal: "Gabungan Aisyah dan Humaira" },
  { nama: "Aizah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mulia dan terhormat", asal: "Dari kata Arab azza bermaksud mulia" },
  { nama: "Aizatul", jantina: "perempuan", bahasa: "Melayu", makna: "Kemuliaan yang tinggi", asal: "Dari kata Arab izza bermaksud mulia" },
  { nama: "Aizrin", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mulia dan cantik", asal: "Variasi Melayu bermaksud kemuliaan" },
  { nama: "Aizzah", jantina: "perempuan", bahasa: "Melayu", makna: "Kemuliaan dan kehormatan", asal: "Dari kata Arab izza bermaksud mulia" },
  { nama: "Akhyar", jantina: "perempuan", bahasa: "Melayu", makna: "Yang paling baik dan terpilih", asal: "Dari kata Arab khayr bermaksud kebaikan" },
  { nama: "Aleesya", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mulia dan bahagia", asal: "Variasi Melayu bermaksud kemuliaan" },
  { nama: "Aleya", jantina: "perempuan", bahasa: "Melayu", makna: "Yang tinggi dan mulia", asal: "Variasi Melayu dari Alya bermaksud tinggi" },
  { nama: "Aliah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang tinggi darjatnya", asal: "Dari kata Arab ala bermaksud tinggi" },
  { nama: "Aliaa", jantina: "perempuan", bahasa: "Melayu", makna: "Yang sangat tinggi dan mulia", asal: "Dari kata Arab ala bermaksud tinggi" },
  { nama: "Alif Sya", jantina: "perempuan", bahasa: "Melayu", makna: "Permulaan yang indah", asal: "Gabungan alif dan sya bermaksud mula" },
  { nama: "Alina", jantina: "perempuan", bahasa: "Melayu", makna: "Yang lembut dan cantik", asal: "Dari bahasa Arab bermaksud lembut" },
  { nama: "Alisa", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mulia dan baik hati", asal: "Variasi Melayu bermaksud kemuliaan" },
  { nama: "Alisya", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mulia dan cantik", asal: "Variasi Melayu bermaksud kemuliaan" },
  { nama: "Alisyah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mulia dan bahagia", asal: "Variasi Melayu bermaksud kemuliaan" },
  { nama: "Aliya", jantina: "perempuan", bahasa: "Melayu", makna: "Yang tinggi dan mulia", asal: "Dari kata Arab ala bermaksud tinggi" },
  { nama: "Aliyah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang tinggi darjatnya", asal: "Dari kata Arab ala bermaksud tinggi" },
  { nama: "Aliyya", jantina: "perempuan", bahasa: "Melayu", makna: "Yang sangat mulia dan tinggi", asal: "Dari kata Arab ala bermaksud tinggi" },
  { nama: "Aliyyah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang tinggi dan mulia darjatnya", asal: "Dari kata Arab ala bermaksud tinggi" },
  { nama: "Aliza", jantina: "perempuan", bahasa: "Melayu", makna: "Yang gembira dan bahagia", asal: "Dari kata Hebrew bermaksud gembira" },
  { nama: "Alizah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang gembira dan ceria", asal: "Dari kata Hebrew bermaksud gembira" },
  { nama: "Almas", jantina: "perempuan", bahasa: "Melayu", makna: "Berlian, yang keras dan berharga", asal: "Dari bahasa Parsi bermaksud berlian" },
  { nama: "Alya", jantina: "perempuan", bahasa: "Melayu", makna: "Yang tinggi dan mulia", asal: "Dari kata Arab ala bermaksud tinggi" },
  { nama: "Alyaa", jantina: "perempuan", bahasa: "Melayu", makna: "Yang sangat tinggi dan mulia", asal: "Dari kata Arab ala bermaksud tinggi" },
  { nama: "Alyssa", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mulia dan cantik", asal: "Variasi Melayu bermaksud kemuliaan" },
  { nama: "Amalina", jantina: "perempuan", bahasa: "Melayu", makna: "Harapan yang indah dan cantik", asal: "Gabungan amal dan lina bermaksud harapan" },
  { nama: "Amanah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang amanah dan boleh dipercayai", asal: "Dari kata Arab amana bermaksud amanah" },
  { nama: "Amani", jantina: "perempuan", bahasa: "Melayu", makna: "Harapan-harapan yang indah", asal: "Dari kata Arab tamanna bermaksud harapan" },
  { nama: "Amara", jantina: "perempuan", bahasa: "Melayu", makna: "Yang kekal dan abadi", asal: "Dari kata Arab amara bermaksud kekal" },
  { nama: "Amielia", jantina: "perempuan", bahasa: "Melayu", makna: "Yang rajin dan gigih", asal: "Variasi Melayu dari Amelia" },
  { nama: "Amierah", jantina: "perempuan", bahasa: "Melayu", makna: "Puteri, pemimpin wanita", asal: "Variasi Melayu dari Amira" },
  { nama: "Amiera", jantina: "perempuan", bahasa: "Melayu", makna: "Puteri yang mulia", asal: "Variasi Melayu dari Amira" },
  { nama: "Amilin", jantina: "perempuan", bahasa: "Melayu", makna: "Yang amanah dalam tugasnya", asal: "Dari kata Arab amila bermaksud bekerja" },
  { nama: "Amina", jantina: "perempuan", bahasa: "Melayu", makna: "Yang aman dan dipercayai", asal: "Dari kata Arab amn bermaksud aman" },
  { nama: "Aminah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang amanah dan boleh dipercayai", asal: "Nama ibu Nabi Muhammad S.A.W" },
  { nama: "Amira", jantina: "perempuan", bahasa: "Melayu", makna: "Puteri, pemimpin wanita", asal: "Dari kata Arab amir bermaksud pemimpin" },
  { nama: "Amirah", jantina: "perempuan", bahasa: "Melayu", makna: "Puteri raja yang mulia", asal: "Dari kata Arab amir bermaksud pemimpin" },
  { nama: "Amira Zahra", jantina: "perempuan", bahasa: "Melayu", makna: "Puteri yang bersinar cantik", asal: "Gabungan Amira dan Zahra" },
  { nama: "Amirul", jantina: "perempuan", bahasa: "Melayu", makna: "Pemimpin yang mulia", asal: "Dari kata Arab amir bermaksud pemimpin" },
  { nama: "Amiza", jantina: "perempuan", bahasa: "Melayu", makna: "Yang istimewa dan cantik", asal: "Variasi Melayu bermaksud keistimewaan" },
  { nama: "Amni", jantina: "perempuan", bahasa: "Melayu", makna: "Yang aman dan selamat", asal: "Dari kata Arab amn bermaksud aman" },
  { nama: "Amrina", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan aman", asal: "Gabungan amr dan rina bermaksud cantik" },
  { nama: "Amylea", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan segar", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Anasuha", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mesra dan menyenangkan", asal: "Dari kata Arab anisa bermaksud mesra" },
  { nama: "Anati", jantina: "perempuan", bahasa: "Melayu", makna: "Yang penuh perhatian", asal: "Dari kata Arab inaya bermaksud perhatian" },
  { nama: "Anggun", jantina: "perempuan", bahasa: "Melayu", makna: "Yang anggun dan elok", asal: "Kata Melayu asli bermaksud anggun" },
  { nama: "Aniera", jantina: "perempuan", bahasa: "Melayu", makna: "Yang bercahaya dan cantik", asal: "Dari kata Arab anara bermaksud bercahaya" },
  { nama: "Anis", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mesra dan ramah", asal: "Dari kata Arab anisa bermaksud mesra" },
  { nama: "Anisa", jantina: "perempuan", bahasa: "Melayu", makna: "Yang ramah dan menyenangkan", asal: "Dari kata Arab anisa bermaksud mesra" },
  { nama: "Anisah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang ramah dan mesra", asal: "Dari kata Arab anisa bermaksud mesra" },
  { nama: "Anisatun", jantina: "perempuan", bahasa: "Melayu", makna: "Yang paling mesra dan ramah", asal: "Dari kata Arab anisa bermaksud mesra" },
  { nama: "Anisyah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mesra dan bersopan", asal: "Variasi dari Anisah bermaksud mesra" },
  { nama: "Aniqa", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan menarik", asal: "Dari kata Arab aniqa bermaksud cantik" },
  { nama: "Aniqah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik jelita", asal: "Dari kata Arab aniqa bermaksud cantik" },
  { nama: "Annur", jantina: "perempuan", bahasa: "Melayu", makna: "Cahaya yang menerangi", asal: "Dari kata Arab nur bermaksud cahaya" },
  { nama: "Annurul", jantina: "perempuan", bahasa: "Melayu", makna: "Cahaya yang terang benderang", asal: "Dari kata Arab nur bermaksud cahaya" },
  { nama: "Aqeela", jantina: "perempuan", bahasa: "Melayu", makna: "Yang berakal dan bijaksana", asal: "Dari kata Arab aql bermaksud akal" },
  { nama: "Aqila", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cerdas dan berakal", asal: "Dari kata Arab aqala bermaksud berfikir" },
  { nama: "Aqilah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang bijaksana dan berakal", asal: "Dari kata Arab aqala bermaksud berfikir" },
  { nama: "Aqisha", jantina: "perempuan", bahasa: "Melayu", makna: "Yang berakal dan cantik", asal: "Gabungan aqil dan isha bermaksud bijak" },
  { nama: "Arfa", jantina: "perempuan", bahasa: "Melayu", makna: "Yang tinggi dan mulia", asal: "Dari kata Arab rafa bermaksud tinggi" },
  { nama: "Arfah", jantina: "perempuan", bahasa: "Melayu", makna: "Bukit Arafah yang suci", asal: "Nama bukit dalam Islam" },
  { nama: "Arina", jantina: "perempuan", bahasa: "Melayu", makna: "Yang damai dan tenang", asal: "Variasi Melayu bermaksud kedamaian" },
  { nama: "Arini", jantina: "perempuan", bahasa: "Melayu", makna: "Yang tenang dan indah", asal: "Variasi Melayu bermaksud keindahan" },
  { nama: "Arisa", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mulia dan cantik", asal: "Variasi Melayu bermaksud kemuliaan" },
  { nama: "Arisha", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mulia dan bersinar", asal: "Variasi Melayu bermaksud kemuliaan" },
  { nama: "Arissa", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mulia cantik jelita", asal: "Variasi Melayu bermaksud kemuliaan" },
  { nama: "Ariza", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan bersinar", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Armiza", jantina: "perempuan", bahasa: "Melayu", makna: "Yang bermakna dan cantik", asal: "Variasi Melayu bermaksud bermakna" },
  { nama: "Arniza", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan bersih", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Arsyiah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang agung seperti arasy", asal: "Dari kata Arab arsy bermaksud singgahsana" },
  { nama: "Artika", jantina: "perempuan", bahasa: "Melayu", makna: "Yang bermakna dan indah", asal: "Variasi Melayu bermaksud bermakna" },
  { nama: "Arwa", jantina: "perempuan", bahasa: "Melayu", makna: "Kambing gunung, yang lincah", asal: "Nama sahabiyah Nabi yang terkenal" },
  { nama: "Aryani", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mulia dan peramah", asal: "Variasi Melayu bermaksud kemuliaan" },
  { nama: "Aryssa", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mulia dan cantik", asal: "Variasi Melayu bermaksud kemuliaan" },
  { nama: "Asiyah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mengubati dan menyembuhkan", asal: "Nama isteri Firaun yang beriman" },
  { nama: "Asma", jantina: "perempuan", bahasa: "Melayu", makna: "Nama-nama, yang mulia", asal: "Nama puteri Abu Bakar As-Siddiq" },
  { nama: "Asmaa", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mulia, yang tinggi darjat", asal: "Variasi dari Asma" },
  { nama: "Asmahan", jantina: "perempuan", bahasa: "Melayu", makna: "Nama-nama yang mulia", asal: "Dari kata Arab asma bermaksud nama" },
  { nama: "Asmaul", jantina: "perempuan", bahasa: "Melayu", makna: "Nama-nama yang indah", asal: "Dari kata Arab asma bermaksud nama" },
  { nama: "Asna", jantina: "perempuan", bahasa: "Melayu", makna: "Yang terpuji dan termulia", asal: "Dari kata Arab asna bermaksud terpuji" },
  { nama: "Asni", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan bersinar", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Asra", jantina: "perempuan", bahasa: "Melayu", makna: "Perjalanan malam yang suci", asal: "Dari kata Arab asra bermaksud perjalanan malam" },
  { nama: "Assyifa", jantina: "perempuan", bahasa: "Melayu", makna: "Ubat, penyembuhan yang mulia", asal: "Dari kata Arab shifa bermaksud ubat" },
  { nama: "Asya", jantina: "perempuan", bahasa: "Melayu", makna: "Yang hidup dan ceria", asal: "Variasi Melayu bermaksud kehidupan" },
  { nama: "Asyikin", jantina: "perempuan", bahasa: "Melayu", makna: "Yang penuh cinta dan kasih", asal: "Dari kata Arab ashiqa bermaksud cinta" },
  { nama: "Asyiqin", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mencintai dengan tulus", asal: "Dari kata Arab ashiqa bermaksud mencintai" },
  { nama: "Asyraf", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mulia dan terhormat", asal: "Dari kata Arab sharafa bermaksud mulia" },
  { nama: "Asyura", jantina: "perempuan", bahasa: "Melayu", makna: "Hari kesepuluh yang mulia", asal: "Dari kata Arab ashura bermaksud sepuluh" },
  { nama: "Athirah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang wangi dan harum", asal: "Dari kata Arab athira bermaksud harum" },
  { nama: "Atika", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan muda", asal: "Dari kata Arab atiqa bermaksud cantik" },
  { nama: "Atikah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang bebas dan mulia", asal: "Dari kata Arab atiqa bermaksud bebas" },
  { nama: "Atiqah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang dimerdekakan dan mulia", asal: "Dari kata Arab atiqa bermaksud merdeka" },
  { nama: "Atira", jantina: "perempuan", bahasa: "Melayu", makna: "Yang wangi dan harum semerbak", asal: "Dari kata Arab athira bermaksud harum" },
  { nama: "Aufa", jantina: "perempuan", bahasa: "Melayu", makna: "Yang paling sempurna dan lengkap", asal: "Dari kata Arab awfa bermaksud sempurna" },
  { nama: "Auliya", jantina: "perempuan", bahasa: "Melayu", makna: "Para wali yang dilindungi Allah", asal: "Dari kata Arab wali bermaksud pelindung" },
  { nama: "Auni", jantina: "perempuan", bahasa: "Melayu", makna: "Bantuanku, pertolonganku", asal: "Dari kata Arab awn bermaksud bantuan" },
  { nama: "Aura", jantina: "perempuan", bahasa: "Melayu", makna: "Cahaya, pancaran yang indah", asal: "Dari bahasa Latin bermaksud cahaya" },
  { nama: "Aurel", jantina: "perempuan", bahasa: "Melayu", makna: "Yang keemasan dan bersinar", asal: "Variasi Melayu bermaksud emas" },
  { nama: "Aurelia", jantina: "perempuan", bahasa: "Melayu", makna: "Yang keemasan dan mulia", asal: "Dari bahasa Latin bermaksud emas" },
  { nama: "Ayasha", jantina: "perempuan", bahasa: "Melayu", makna: "Yang hidup dan gembira", asal: "Variasi dari Aisyah bermaksud hidup" },
  { nama: "Ayesha", jantina: "perempuan", bahasa: "Melayu", makna: "Yang hidup dan ceria", asal: "Variasi dari Aisyah bermaksud hidup" },
  { nama: "Ayra", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mulia dan cantik", asal: "Variasi Melayu bermaksud kemuliaan" },
  { nama: "Ayreen", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan damai", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Aysha", jantina: "perempuan", bahasa: "Melayu", makna: "Yang hidup dan bahagia", asal: "Variasi dari Aisyah bermaksud hidup" },
  { nama: "Ayu", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik jelita", asal: "Kata Melayu asli bermaksud cantik" },
  { nama: "Ayufarhana", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan gembira", asal: "Gabungan ayu dan farhana" },
  { nama: "Ayuni", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan manis", asal: "Gabungan ayu dan ni bermaksud cantik" },
  { nama: "Azah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan indah", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Azalia", jantina: "perempuan", bahasa: "Melayu", makna: "Bunga azalea yang cantik", asal: "Dari nama bunga azalea" },
  { nama: "Azean", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mulia dan cantik", asal: "Variasi Melayu bermaksud kemuliaan" },
  { nama: "Azeera", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mulia dan berharga", asal: "Variasi Melayu bermaksud kemuliaan" },
  { nama: "Aziera", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mulia dan cantik", asal: "Variasi Melayu bermaksud kemuliaan" },
  { nama: "Azila", jantina: "perempuan", bahasa: "Melayu", makna: "Yang jauh, yang istimewa", asal: "Variasi Melayu bermaksud keistimewaan" },
  { nama: "Azimah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang agung dan mulia", asal: "Dari kata Arab azuma bermaksud agung" },
  { nama: "Azira", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mulia dan cantik", asal: "Variasi Melayu bermaksud kemuliaan" },
  { nama: "Aziraa", jantina: "perempuan", bahasa: "Melayu", makna: "Yang sangat mulia dan cantik", asal: "Variasi Melayu bermaksud kemuliaan" },
  { nama: "Azizah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mulia dan perkasa", asal: "Dari kata Arab aziza bermaksud mulia" },
  { nama: "Azleen", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan menarik", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Azlina", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan bersinar", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Azlinda", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan indah", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Azma", jantina: "perempuan", bahasa: "Melayu", makna: "Yang bercita-cita tinggi", asal: "Dari kata Arab azm bermaksud cita-cita" },
  { nama: "Azmah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang berkeazaman tinggi", asal: "Dari kata Arab azm bermaksud azam" },
  { nama: "Aznida", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan mulia", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Aznin", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan manis", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Azra", jantina: "perempuan", bahasa: "Melayu", makna: "Yang suci dan murni", asal: "Dari kata Arab azra bermaksud suci" },
  { nama: "Azreen", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan bersinar", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Azri", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan menarik", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Azrina", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik jelita", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Azrini", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan manis", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Azua", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan berseri", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Azuin", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan menarik", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Azurin", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik bagai batu lazurit", asal: "Dari kata lazurite bermaksud biru cantik" },
  { nama: "Azuwa", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan berseri-seri", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Azwa", jantina: "perempuan", bahasa: "Melayu", makna: "Cahaya-cahaya yang bersinar", asal: "Dari kata Arab dhaw bermaksud cahaya" },
  { nama: "Azwani", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan elok parasnya", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Azwany", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan menarik", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Azyan", jantina: "perempuan", bahasa: "Melayu", makna: "Yang indah dan bersinar", asal: "Variasi Melayu bermaksud keindahan" },
  { nama: "Azydha", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan berseri", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Azzahra", jantina: "perempuan", bahasa: "Melayu", makna: "Yang bersinar dan cantik", asal: "Dari kata Arab zahara bermaksud bersinar" },
  { nama: "Azzatul", jantina: "perempuan", bahasa: "Melayu", makna: "Kemuliaan yang tinggi", asal: "Dari kata Arab izza bermaksud kemuliaan" },

  // ── HURUF B ──
  { nama: "Bahiyah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan berseri", asal: "Dari kata Arab bahiya bermaksud cantik" },
  { nama: "Balkis", jantina: "perempuan", bahasa: "Melayu", makna: "Ratu Saba yang bijaksana", asal: "Variasi dari Bilqis" },
  { nama: "Barirah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang salih dan taat", asal: "Dari kata Arab barra bermaksud salih" },
  { nama: "Basyirah", jantina: "perempuan", bahasa: "Melayu", makna: "Pembawa berita gembira", asal: "Dari kata Arab bashshara bermaksud berita" },
  { nama: "Batrisyia", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mulia dan terhormat", asal: "Variasi Arab bermaksud mulia" },
  { nama: "Bazlina", jantina: "perempuan", bahasa: "Melayu", makna: "Yang memberi dengan tulus", asal: "Dari kata Arab bazala bermaksud memberi" },
  { nama: "Bazlynn", jantina: "perempuan", bahasa: "Melayu", makna: "Yang memberi kebaikan", asal: "Variasi dari Bazlina" },

  // ── HURUF D ──
  { nama: "Daania", jantina: "perempuan", bahasa: "Melayu", makna: "Yang dekat kepada Allah", asal: "Dari kata Arab dana bermaksud dekat" },
  { nama: "Dahlia", jantina: "perempuan", bahasa: "Melayu", makna: "Bunga dahlia yang cantik", asal: "Nama dari bunga dahlia" },
  { nama: "Damia", jantina: "perempuan", bahasa: "Melayu", makna: "Yang tenang dan damai", asal: "Variasi Melayu bermaksud ketenangan" },
  { nama: "Dania", jantina: "perempuan", bahasa: "Melayu", makna: "Yang dekat, yang hampir", asal: "Dari kata Arab dana bermaksud dekat" },
  { nama: "Daniah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang dekat kepada kebaikan", asal: "Dari kata Arab dana bermaksud dekat" },
  { nama: "Daniella", jantina: "perempuan", bahasa: "Melayu", makna: "Allah adalah hakimku", asal: "Variasi Melayu dari Danial" },
  { nama: "Danya", jantina: "perempuan", bahasa: "Melayu", makna: "Yang dekat dan dikasihi", asal: "Variasi dari Dania bermaksud dekat" },
  { nama: "Darina", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan bersinar", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Darwisyah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang sufi, yang zuhud", asal: "Dari kata Arab darwish bermaksud sufi" },
  { nama: "Dawiyah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang jernih seperti air telaga", asal: "Dari kata Arab daawa bermaksud jernih" },
  { nama: "Delisha", jantina: "perempuan", bahasa: "Melayu", makna: "Yang menyenangkan dan cantik", asal: "Variasi Melayu bermaksud menyenangkan" },
  { nama: "Delysa", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan manis", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Dhia", jantina: "perempuan", bahasa: "Melayu", makna: "Cahaya yang menerangi", asal: "Dari kata Arab dhiya bermaksud cahaya" },
  { nama: "Dhiya", jantina: "perempuan", bahasa: "Melayu", makna: "Cahaya, sinar yang terang", asal: "Dari kata Arab dhiya bermaksud cahaya" },
  { nama: "Dhuha", jantina: "perempuan", bahasa: "Melayu", makna: "Waktu pagi yang cerah", asal: "Dari Al-Quran surah Ad-Dhuha" },
  { nama: "Diana", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan bersinar", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Diyana", jantina: "perempuan", bahasa: "Melayu", makna: "Agama, yang taat beragama", asal: "Dari kata Arab din bermaksud agama" },
  { nama: "Diyanah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang taat dan patuh", asal: "Dari kata Arab din bermaksud agama" },
  { nama: "Durriyyah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang seperti mutiara, berharga", asal: "Dari kata Arab durr bermaksud mutiara" },

  // ── HURUF E ──
  { nama: "Eiman", jantina: "perempuan", bahasa: "Melayu", makna: "Keimanan, kepercayaan kepada Allah", asal: "Variasi dari Iman bermaksud keimanan" },
  { nama: "Eliani", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan bersinar", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Elianna", jantina: "perempuan", bahasa: "Melayu", makna: "Allah telah menjawab", asal: "Variasi Melayu bermaksud jawapan Allah" },
  { nama: "Elida", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan menawan", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Elina", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan bercahaya", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Elisa", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mulia dan suci", asal: "Variasi Melayu bermaksud kemuliaan" },
  { nama: "Elisha", jantina: "perempuan", bahasa: "Melayu", makna: "Allah adalah penyelamatku", asal: "Dari kata Hebrew bermaksud selamat" },
  { nama: "Elissa", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mulia dan cantik", asal: "Variasi Melayu bermaksud kemuliaan" },
  { nama: "Elliya", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan indah", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Ellysa", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan mulia", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Elmia", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan berseri", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Elyana", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan bersinar", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Elysha", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mulia dan cantik", asal: "Variasi Melayu bermaksud kemuliaan" },
  { nama: "Emilia", jantina: "perempuan", bahasa: "Melayu", makna: "Yang gigih dan bersemangat", asal: "Variasi Melayu bermaksud gigih" },
  { nama: "Emillia", jantina: "perempuan", bahasa: "Melayu", makna: "Yang rajin dan tekun", asal: "Variasi Melayu bermaksud rajin" },
  { nama: "Emma", jantina: "perempuan", bahasa: "Melayu", makna: "Yang utuh dan universal", asal: "Variasi Melayu bermaksud utuh" },
  { nama: "Eriana", jantina: "perempuan", bahasa: "Melayu", makna: "Yang damai dan cantik", asal: "Variasi Melayu bermaksud kedamaian" },
  { nama: "Erina", jantina: "perempuan", bahasa: "Melayu", makna: "Yang damai dan tenang", asal: "Variasi Melayu bermaksud kedamaian" },
  { nama: "Erma", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan elok", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Ernie", jantina: "perempuan", bahasa: "Melayu", makna: "Yang serius dan bersungguh", asal: "Variasi Melayu bermaksud kesungguhan" },
  { nama: "Erysa", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan berseri", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Esya", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan menawan", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Eyrna", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan damai", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Ezreen", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan bersinar", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Ezura", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan menawan", asal: "Variasi Melayu bermaksud kecantikan" },

  // ── HURUF F ──
  { nama: "Fadhilah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mempunyai kelebihan dan mulia", asal: "Dari kata Arab fadl bermaksud kelebihan" },
  { nama: "Fadwa", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mengorbankan diri", asal: "Dari kata Arab fada bermaksud pengorbanan" },
  { nama: "Fahana", jantina: "perempuan", bahasa: "Melayu", makna: "Yang faham dan bijaksana", asal: "Dari kata Arab fahima bermaksud faham" },
  { nama: "Faiqah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang unggul dan terbaik", asal: "Dari kata Arab faaqa bermaksud unggul" },
  { nama: "Faisa", jantina: "perempuan", bahasa: "Melayu", makna: "Yang memutuskan dengan adil", asal: "Dari kata Arab fasala bermaksud memutus" },
  { nama: "Faisyah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang luas dan mulia", asal: "Variasi Melayu bermaksud keluasan" },
  { nama: "Faizah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang berjaya dan menang", asal: "Dari kata Arab faza bermaksud berjaya" },
  { nama: "Faizatul", jantina: "perempuan", bahasa: "Melayu", makna: "Kemenangan yang indah", asal: "Dari kata Arab faza bermaksud menang" },
  { nama: "Fajar", jantina: "perempuan", bahasa: "Melayu", makna: "Cahaya fajar, awal yang baru", asal: "Dari kata Arab fajr bermaksud fajar" },
  { nama: "Falisha", jantina: "perempuan", bahasa: "Melayu", makna: "Yang bahagia dan berjaya", asal: "Variasi Melayu bermaksud kebahagiaan" },
  { nama: "Farahin", jantina: "perempuan", bahasa: "Melayu", makna: "Kegembiraan-kegembiraan yang indah", asal: "Dari kata Arab farah bermaksud gembira" },
  { nama: "Farahiyah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang penuh kegembiraan", asal: "Dari kata Arab farah bermaksud gembira" },
  { nama: "Farahwahida", jantina: "perempuan", bahasa: "Melayu", makna: "Kegembiraan yang tunggal", asal: "Gabungan farah dan wahida" },
  { nama: "Farazana", jantina: "perempuan", bahasa: "Melayu", makna: "Yang bijaksana dan cerdas", asal: "Dari bahasa Parsi bermaksud bijak" },
  { nama: "Farida", jantina: "perempuan", bahasa: "Melayu", makna: "Yang unik dan tiada tandingan", asal: "Dari kata Arab farid bermaksud unik" },
  { nama: "Faridah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang istimewa dan unik", asal: "Dari kata Arab farid bermaksud unik" },
  { nama: "Farihan", jantina: "perempuan", bahasa: "Melayu", makna: "Yang gembira dan bahagia", asal: "Dari kata Arab farih bermaksud gembira" },
  { nama: "Fathin", jantina: "perempuan", bahasa: "Melayu", makna: "Yang memikat dan menarik hati", asal: "Dari kata Arab fatana bermaksud memikat" },
  { nama: "Fatiha", jantina: "perempuan", bahasa: "Melayu", makna: "Yang membuka, permulaan yang baik", asal: "Dari kata Arab fataha bermaksud membuka" },
  { nama: "Fatihah", jantina: "perempuan", bahasa: "Melayu", makna: "Pembuka, Al-Fatihah yang mulia", asal: "Dari Al-Quran surah Al-Fatihah" },
  { nama: "Fawwazah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang berjaya dengan cemerlang", asal: "Dari kata Arab faza bermaksud berjaya" },
  { nama: "Fayadhah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang murah hati, yang melimpah", asal: "Dari kata Arab fayadha bermaksud melimpah" },
  { nama: "Fazlina", jantina: "perempuan", bahasa: "Melayu", makna: "Kelebihan yang cantik", asal: "Dari kata Arab fadl bermaksud kelebihan" },
  { nama: "Fharahdina", jantina: "perempuan", bahasa: "Melayu", makna: "Kegembiraan agama", asal: "Gabungan farah dan din bermaksud gembira" },
  { nama: "Fikrah", jantina: "perempuan", bahasa: "Melayu", makna: "Pemikiran, yang berfikir jauh", asal: "Dari kata Arab fikr bermaksud fikiran" },
  { nama: "Firas", jantina: "perempuan", bahasa: "Melayu", makna: "Yang bijak dan proaktif", asal: "Dari kata Arab firasat bermaksud kebijakan" },
  { nama: "Firdaus", jantina: "perempuan", bahasa: "Melayu", makna: "Syurga tertinggi yang indah", asal: "Dari kata Arab firdaws bermaksud syurga" },
  { nama: "Firdausi", jantina: "perempuan", bahasa: "Melayu", makna: "Yang bersifat syurga", asal: "Dari kata Arab firdaws bermaksud syurga" },
  { nama: "Firzanah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang bijaksana dan cerdas", asal: "Dari bahasa Parsi bermaksud bijak" },
  { nama: "Fitrah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang fitrah, yang suci semula jadi", asal: "Dari kata Arab fitra bermaksud kejadian asal" },
  { nama: "Fitriani", jantina: "perempuan", bahasa: "Melayu", makna: "Yang fitrah dan cantik", asal: "Gabungan fitrah dan ani" },
  { nama: "Fouziah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang berjaya dan menang", asal: "Dari kata Arab faza bermaksud berjaya" },

  // ── HURUF H ──
  { nama: "Hafeeza", jantina: "perempuan", bahasa: "Melayu", makna: "Yang memelihara dan menjaga", asal: "Variasi dari Hafizah bermaksud penjaga" },
  { nama: "Hafizah", jantina: "perempuan", bahasa: "Melayu", makna: "Penghafaz Al-Quran yang mulia", asal: "Bentuk feminin dari hafiz" },
  { nama: "Haidatul", jantina: "perempuan", bahasa: "Melayu", makna: "Petunjuk yang mulia", asal: "Dari kata Arab huda bermaksud petunjuk" },
  { nama: "Haikal", jantina: "perempuan", bahasa: "Melayu", makna: "Yang berbadan tegap dan cantik", asal: "Dari bahasa Arab bermaksud tegap" },
  { nama: "Hajar", jantina: "perempuan", bahasa: "Melayu", makna: "Yang tabah dan kuat hati", asal: "Nama isteri Nabi Ibrahim A.S" },
  { nama: "Hajaratul", jantina: "perempuan", bahasa: "Melayu", makna: "Batu yang istimewa", asal: "Dari kata Arab hajar bermaksud batu" },
  { nama: "Hakeemah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang bijaksana dan arif", asal: "Dari kata Arab hakama bermaksud bijak" },
  { nama: "Halimah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang sabar dan lemah lembut", asal: "Nama ibu susuan Nabi Muhammad S.A.W" },
  { nama: "Hanaa", jantina: "perempuan", bahasa: "Melayu", makna: "Kebahagiaan yang melimpah", asal: "Dari kata Arab hana bermaksud gembira" },
  { nama: "Hanani", jantina: "perempuan", bahasa: "Melayu", makna: "Yang penyayang dan berbelas kasih", asal: "Dari kata Arab hanan bermaksud kasih" },
  { nama: "Hanifah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang lurus beragama Islam", asal: "Dari kata Arab hanifa bermaksud lurus" },
  { nama: "Hanisah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang gembira dan bahagia", asal: "Dari kata Arab hanisa bermaksud gembira" },
  { nama: "Hannani", jantina: "perempuan", bahasa: "Melayu", makna: "Yang penuh kasih sayang", asal: "Dari kata Arab hanan bermaksud kasih" },
  { nama: "Hasanah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang baik dan cantik", asal: "Dari kata Arab husn bermaksud kebaikan" },
  { nama: "Haura", jantina: "perempuan", bahasa: "Melayu", makna: "Bidadari syurga, mata yang indah", asal: "Dari kata Arab hawra bermaksud mata indah" },
  { nama: "Hayati", jantina: "perempuan", bahasa: "Melayu", makna: "Kehidupanku, yang bermakna", asal: "Dari kata Arab hayat bermaksud kehidupan" },
  { nama: "Haziqah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mahir dan cerdik", asal: "Dari kata Arab hazaqa bermaksud mahir" },
  { nama: "Hazwani", jantina: "perempuan", bahasa: "Melayu", makna: "Yang berhati-hati dan teliti", asal: "Dari kata Arab hazm bermaksud teliti" },
  { nama: "Huda", jantina: "perempuan", bahasa: "Melayu", makna: "Petunjuk Allah yang benar", asal: "Dari kata Arab hada bermaksud petunjuk" },
  { nama: "Humaira", jantina: "perempuan", bahasa: "Melayu", makna: "Yang kemerahan dan cantik", asal: "Gelaran Nabi kepada Saidatina Aisyah" },
  { nama: "Husna", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan baik", asal: "Dari kata Arab husn bermaksud cantik" },
  { nama: "Husnul", jantina: "perempuan", bahasa: "Melayu", makna: "Kecantikan yang tinggi", asal: "Dari kata Arab husn bermaksud cantik" },
  { nama: "Huwaida", jantina: "perempuan", bahasa: "Melayu", makna: "Yang lembut dan perlahan", asal: "Dari kata Arab hawida bermaksud lembut" },

  // ── HURUF I ──
  { nama: "Idayu", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan bertuah", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Ilham", jantina: "perempuan", bahasa: "Melayu", makna: "Inspirasi dari Allah", asal: "Dari kata Arab alhama bermaksud ilham" },
  { nama: "Iliya", jantina: "perempuan", bahasa: "Melayu", makna: "Yang tinggi dan mulia", asal: "Variasi Melayu bermaksud ketinggian" },
  { nama: "Ilyana", jantina: "perempuan", bahasa: "Melayu", makna: "Cahaya yang lembut dan cantik", asal: "Variasi Melayu bermaksud cahaya lembut" },
  { nama: "Ilyani", jantina: "perempuan", bahasa: "Melayu", makna: "Cahaya yang indah dan cantik", asal: "Variasi Melayu bermaksud cahaya" },
  { nama: "Imaan", jantina: "perempuan", bahasa: "Melayu", makna: "Keimanan yang kuat kepada Allah", asal: "Dari kata Arab amana bermaksud percaya" },
  { nama: "Imanina", jantina: "perempuan", bahasa: "Melayu", makna: "Keimananku yang cantik", asal: "Gabungan iman dan nina" },
  { nama: "Insyirah", jantina: "perempuan", bahasa: "Melayu", makna: "Kelapangan dada dan ketenangan", asal: "Dari Al-Quran surah Al-Insyirah" },
  { nama: "Iqamah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang teguh dan berpendirian", asal: "Dari kata Arab aqama bermaksud teguh" },
  { nama: "Irda", jantina: "perempuan", bahasa: "Melayu", makna: "Yang diredhai Allah", asal: "Dari kata Arab radha bermaksud redha" },
  { nama: "Irdawani", jantina: "perempuan", bahasa: "Melayu", makna: "Keredhaan yang cantik", asal: "Dari kata Arab ridwan bermaksud redha" },
  { nama: "Irdina", jantina: "perempuan", bahasa: "Melayu", makna: "Agamaku, keislamanku", asal: "Dari kata Arab din bermaksud agama" },
  { nama: "Irdinah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang beragama dengan teguh", asal: "Dari kata Arab din bermaksud agama" },
  { nama: "Isfaraini", jantina: "perempuan", bahasa: "Melayu", makna: "Cahaya yang menerangi", asal: "Dari kata Arab isfar bermaksud cahaya" },
  { nama: "Isma", jantina: "perempuan", bahasa: "Melayu", makna: "Yang memelihara dan menjaga", asal: "Dari kata Arab asama bermaksud menjaga" },
  { nama: "Ismah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang terpelihara dan suci", asal: "Dari kata Arab isma bermaksud terpelihara" },
  { nama: "Isnani", jantina: "perempuan", bahasa: "Melayu", makna: "Yang kedua, yang istimewa", asal: "Dari kata Arab ithnan bermaksud dua" },
  { nama: "Izzati", jantina: "perempuan", bahasa: "Melayu", makna: "Kemuliaanku, kehormatanku", asal: "Dari kata Arab izza bermaksud mulia" },
  { nama: "Izzatul", jantina: "perempuan", bahasa: "Melayu", makna: "Kemuliaan yang tinggi", asal: "Dari kata Arab izza bermaksud mulia" },
  { nama: "Izzatunnisa", jantina: "perempuan", bahasa: "Melayu", makna: "Kemuliaan wanita", asal: "Gabungan izzat dan nisa bermaksud mulia" },
  { nama: "Izzaty", jantina: "perempuan", bahasa: "Melayu", makna: "Kemuliaanku yang indah", asal: "Variasi dari Izzati bermaksud mulia" },
  { nama: "Izzrah", jantina: "perempuan", bahasa: "Melayu", makna: "Kemuliaan dan kehormatan", asal: "Dari kata Arab izza bermaksud mulia" },

  // ── HURUF J ──
  { nama: "Jamiela", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik jelita", asal: "Dari kata Arab jamila bermaksud cantik" },
  { nama: "Jamilah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan indah", asal: "Dari kata Arab jamala bermaksud cantik" },
  { nama: "Jannatul", jantina: "perempuan", bahasa: "Melayu", makna: "Taman syurga yang indah", asal: "Dari kata Arab janna bermaksud syurga" },
  { nama: "Jasmin", jantina: "perempuan", bahasa: "Melayu", makna: "Bunga jasmin yang harum", asal: "Nama bunga harum dalam bahasa Arab" },
  { nama: "Jauhara", jantina: "perempuan", bahasa: "Melayu", makna: "Permata yang berharga", asal: "Dari kata Arab jawhar bermaksud permata" },
  { nama: "Jayda", jantina: "perempuan", bahasa: "Melayu", makna: "Yang baik dan cantik", asal: "Dari kata Arab jayid bermaksud baik" },
  { nama: "Jazlina", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan menarik", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Jazmin", jantina: "perempuan", bahasa: "Melayu", makna: "Bunga jasmin yang cantik", asal: "Variasi dari Jasmin bermaksud bunga" },
  { nama: "Jiha", jantina: "perempuan", bahasa: "Melayu", makna: "Arah yang benar dan tepat", asal: "Dari kata Arab jiha bermaksud arah" },
  { nama: "Jihan", jantina: "perempuan", bahasa: "Melayu", makna: "Arah yang indah, dunia", asal: "Dari kata Arab jiha bermaksud arah" },
  { nama: "Jihanah", jantina: "perempuan", bahasa: "Melayu", makna: "Arah yang benar dan cantik", asal: "Dari kata Arab jiha bermaksud arah" },
  { nama: "Juwairiah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang muda dan cantik", asal: "Nama isteri Nabi Muhammad S.A.W" },
  { nama: "Juwariyah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang muda dan berseri", asal: "Variasi dari Juwairiah" },

  // ── HURUF K ──
  { nama: "Khadijah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang lahir pramatang, yang mulia", asal: "Nama isteri pertama Nabi Muhammad S.A.W" },
  { nama: "Khairiah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang baik dan penuh kebaikan", asal: "Dari kata Arab khayr bermaksud kebaikan" },
  { nama: "Khairiyyah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang penuh kebaikan dan mulia", asal: "Dari kata Arab khayr bermaksud kebaikan" },
  { nama: "Khairunnisa", jantina: "perempuan", bahasa: "Melayu", makna: "Sebaik-baik wanita", asal: "Gabungan khair dan nisa bermaksud wanita terbaik" },
  { nama: "Khalisa", jantina: "perempuan", bahasa: "Melayu", makna: "Yang tulen dan ikhlas", asal: "Dari kata Arab khalasa bermaksud tulen" },
  { nama: "Khaulah", jantina: "perempuan", bahasa: "Melayu", makna: "Rusa betina, yang lincah", asal: "Nama sahabiyah Nabi yang terkenal" },

  // ── HURUF L ──
  { nama: "Laila", jantina: "perempuan", bahasa: "Melayu", makna: "Malam yang indah dan cantik", asal: "Nama popular dalam sastera Arab" },
  { nama: "Lailatul", jantina: "perempuan", bahasa: "Melayu", makna: "Malam yang istimewa", asal: "Dari kata Arab laylat bermaksud malam" },
  { nama: "Lailieysha", jantina: "perempuan", bahasa: "Melayu", makna: "Malam yang mulia dan cantik", asal: "Gabungan laila dan aisyah" },
  { nama: "Lamya", jantina: "perempuan", bahasa: "Melayu", makna: "Yang berkulit gelap dan cantik", asal: "Dari kata Arab lama bermaksud gelap manis" },
  { nama: "Latifah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang lembut dan halus budi", asal: "Salah satu nama Allah Al-Latif" },
  { nama: "Layla", jantina: "perempuan", bahasa: "Melayu", makna: "Malam, yang indah", asal: "Variasi dari Laila bermaksud malam" },
  { nama: "Layna", jantina: "perempuan", bahasa: "Melayu", makna: "Yang lembut dan menyenangkan", asal: "Dari kata Arab layn bermaksud lembut" },
  { nama: "Liyana", jantina: "perempuan", bahasa: "Melayu", makna: "Yang lembut dan mudah bergaul", asal: "Dari bahasa Arab layn bermaksud lembut" },
  { nama: "Lyana", jantina: "perempuan", bahasa: "Melayu", makna: "Yang lembut dan cantik", asal: "Variasi dari Liyana bermaksud lembut" },

  // ── HURUF M ──
  { nama: "Madihah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang terpuji dan mulia", asal: "Dari kata Arab madaha bermaksud memuji" },
  { nama: "Maisarah", jantina: "perempuan", bahasa: "Melayu", makna: "Kemudahan, yang serba senang", asal: "Dari kata Arab yasara bermaksud mudah" },
  { nama: "Maizatul", jantina: "perempuan", bahasa: "Melayu", makna: "Pembeza yang mulia", asal: "Dari kata Arab mayaza bermaksud membeza" },
  { nama: "Malak", jantina: "perempuan", bahasa: "Melayu", makna: "Malaikat, yang cantik", asal: "Dari kata Arab malak bermaksud malaikat" },
  { nama: "Malia", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan menyenangkan", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Malihah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan manis", asal: "Dari kata Arab malaha bermaksud cantik" },
  { nama: "Mardhiah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang diredhai Allah", asal: "Dari kata Arab radha bermaksud redha" },
  { nama: "Mariam", jantina: "perempuan", bahasa: "Melayu", makna: "Yang taat beribadah", asal: "Variasi dari Maryam" },
  { nama: "Marina", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan berseri", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Marini", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan elok", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Marsya", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan menawan", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Maryam", jantina: "perempuan", bahasa: "Melayu", makna: "Yang taat beribadah, bunga", asal: "Nama ibu Nabi Isa A.S" },
  { nama: "Mastura", jantina: "perempuan", bahasa: "Melayu", makna: "Yang terpelihara dan suci", asal: "Dari kata Arab satara bermaksud terpelihara" },
  { nama: "Maziah", jantina: "perempuan", bahasa: "Melayu", makna: "Kelebihan dan keistimewaan", asal: "Dari kata Arab mayaza bermaksud lebih" },
  { nama: "Mimi", jantina: "perempuan", bahasa: "Melayu", makna: "Yang dicintai dan disayangi", asal: "Nama comel Melayu bermaksud sayang" },
  { nama: "Mizatul", jantina: "perempuan", bahasa: "Melayu", makna: "Kelebihan yang mulia", asal: "Dari kata Arab miza bermaksud kelebihan" },
  { nama: "Munirah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang bercahaya dan menerangi", asal: "Dari kata Arab anara bermaksud cahaya" },
  { nama: "Murni", jantina: "perempuan", bahasa: "Melayu", makna: "Yang murni dan suci", asal: "Kata Melayu asli bermaksud murni" },

  // ── HURUF N ──
  { nama: "Nabihah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cerdas dan bijaksana", asal: "Dari kata Arab nabaha bermaksud cerdas" },
  { nama: "Nabilah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mulia dan cerdas", asal: "Dari kata Arab nabala bermaksud mulia" },
  { nama: "Nadhirah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang berseri dan cantik", asal: "Dari kata Arab nadhara bermaksud bersinar" },
  { nama: "Nadiah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang lembut dan berembun", asal: "Dari kata Arab nada bermaksud embun" },
  { nama: "Nadiatul", jantina: "perempuan", bahasa: "Melayu", makna: "Embun yang indah", asal: "Dari kata Arab nada bermaksud embun" },
  { nama: "Naelofar", jantina: "perempuan", bahasa: "Melayu", makna: "Bunga teratai yang cantik", asal: "Dari bahasa Parsi bermaksud teratai" },
  { nama: "Nafisah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang berharga dan bernilai", asal: "Dari kata Arab nafasa bermaksud berharga" },
  { nama: "Nafishah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang bernilai dan berharga tinggi", asal: "Variasi dari Nafisah" },
  { nama: "Najah", jantina: "perempuan", bahasa: "Melayu", makna: "Kejayaan dan kemenangan", asal: "Dari kata Arab najaha bermaksud berjaya" },
  { nama: "Najihah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang berjaya dan lulus", asal: "Dari kata Arab najaha bermaksud berjaya" },
  { nama: "Najiyah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang selamat dan terpelihara", asal: "Dari kata Arab naja bermaksud selamat" },
  { nama: "Najla", jantina: "perempuan", bahasa: "Melayu", makna: "Yang bermata indah dan besar", asal: "Dari kata Arab najla bermaksud bermata indah" },
  { nama: "Najmah", jantina: "perempuan", bahasa: "Melayu", makna: "Bintang yang bersinar", asal: "Dari kata Arab najm bermaksud bintang" },
  { nama: "Najwa", jantina: "perempuan", bahasa: "Melayu", makna: "Bisikan mesra yang indah", asal: "Dari kata Arab naja bermaksud berbisik" },
  { nama: "Nasiha", jantina: "perempuan", bahasa: "Melayu", makna: "Yang memberi nasihat yang baik", asal: "Dari kata Arab nasaha bermaksud nasihat" },
  { nama: "Nasihah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang ikhlas memberi nasihat", asal: "Dari kata Arab nasaha bermaksud nasihat" },
  { nama: "Nawal", jantina: "perempuan", bahasa: "Melayu", makna: "Yang memberi, yang pemurah", asal: "Dari kata Arab nawwala bermaksud memberi" },
  { nama: "Nayra", jantina: "perempuan", bahasa: "Melayu", makna: "Yang bersinar seperti matahari", asal: "Dari kata Arab nayyir bermaksud bersinar" },
  { nama: "Nazihah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang jujur dan bersih hati", asal: "Dari kata Arab nazaha bermaksud bersih" },
  { nama: "Nazira", jantina: "perempuan", bahasa: "Melayu", makna: "Yang sederajat dan setara", asal: "Dari kata Arab nazira bermaksud setara" },
  { nama: "Nazirah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang memerhati dan mengawas", asal: "Dari kata Arab nadhara bermaksud memerhatikan" },
  { nama: "Niesa", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan manis", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Nisa", jantina: "perempuan", bahasa: "Melayu", makna: "Wanita, kaum hawa yang mulia", asal: "Dari kata Arab nisa bermaksud wanita" },
  { nama: "Nisha", jantina: "perempuan", bahasa: "Melayu", makna: "Malam yang cantik", asal: "Dari bahasa Sanskrit bermaksud malam" },
  { nama: "Noor", jantina: "perempuan", bahasa: "Melayu", makna: "Cahaya yang menerangi", asal: "Variasi dari Nur bermaksud cahaya" },
  { nama: "Noorhanim", jantina: "perempuan", bahasa: "Melayu", makna: "Cahaya yang lemah lembut", asal: "Gabungan nur dan hanim bermaksud lembut" },
  { nama: "Noorizan", jantina: "perempuan", bahasa: "Melayu", makna: "Cahaya keseimbangan", asal: "Gabungan nur dan izan bermaksud cahaya" },
  { nama: "Nora", jantina: "perempuan", bahasa: "Melayu", makna: "Cahaya, yang bersinar", asal: "Variasi dari Nur bermaksud cahaya" },
  { nama: "Norain", jantina: "perempuan", bahasa: "Melayu", makna: "Dua cahaya yang bersinar", asal: "Gabungan nur dan ain bermaksud cahaya" },
  { nama: "Noraishah", jantina: "perempuan", bahasa: "Melayu", makna: "Cahaya yang hidup dan ceria", asal: "Gabungan nur dan Aisyah" },
  { nama: "Norazmah", jantina: "perempuan", bahasa: "Melayu", makna: "Cahaya berkeazaman tinggi", asal: "Gabungan nur dan azm bermaksud azam" },
  { nama: "Norhanim", jantina: "perempuan", bahasa: "Melayu", makna: "Cahaya yang lemah lembut", asal: "Gabungan nur dan hanim" },
  { nama: "Norhayati", jantina: "perempuan", bahasa: "Melayu", makna: "Cahaya kehidupan yang indah", asal: "Gabungan nur dan hayat bermaksud hidup" },
  { nama: "Norjannah", jantina: "perempuan", bahasa: "Melayu", makna: "Cahaya syurga yang indah", asal: "Gabungan nur dan jannah bermaksud syurga" },
  { nama: "Norlia", jantina: "perempuan", bahasa: "Melayu", makna: "Cahaya yang indah", asal: "Gabungan nur dan lia" },
  { nama: "Norlinah", jantina: "perempuan", bahasa: "Melayu", makna: "Cahaya yang lembut", asal: "Gabungan nur dan linah bermaksud lembut" },
  { nama: "Norlinda", jantina: "perempuan", bahasa: "Melayu", makna: "Cahaya yang cantik", asal: "Gabungan nur dan linda bermaksud cantik" },
  { nama: "Normah", jantina: "perempuan", bahasa: "Melayu", makna: "Cahaya kemuliaan", asal: "Gabungan nur dan mah bermaksud cahaya" },
  { nama: "Norzahra", jantina: "perempuan", bahasa: "Melayu", makna: "Cahaya bunga yang cantik", asal: "Gabungan nur dan zahra" },
  { nama: "Norzalifah", jantina: "perempuan", bahasa: "Melayu", makna: "Cahaya yang dekat", asal: "Gabungan nur dan zalifah" },
  { nama: "Nurnajwa", jantina: "perempuan", bahasa: "Melayu", makna: "Cahaya bisikan yang indah", asal: "Gabungan nur dan najwa" },
  { nama: "Nurnisa", jantina: "perempuan", bahasa: "Melayu", makna: "Cahaya wanita yang mulia", asal: "Gabungan nur dan nisa" },
  { nama: "Nursabrina", jantina: "perempuan", bahasa: "Melayu", makna: "Cahaya kesabaran", asal: "Gabungan nur dan sabrina" },
  { nama: "Nursyafiqah", jantina: "perempuan", bahasa: "Melayu", makna: "Cahaya kasih sayang", asal: "Gabungan nur dan syafiqah" },
  { nama: "Nursyahirah", jantina: "perempuan", bahasa: "Melayu", makna: "Cahaya yang terkenal", asal: "Gabungan nur dan syahirah" },
  { nama: "Nurulain", jantina: "perempuan", bahasa: "Melayu", makna: "Cahaya mata yang indah", asal: "Gabungan nurul dan ain" },
  { nama: "Nurulhuda", jantina: "perempuan", bahasa: "Melayu", makna: "Cahaya petunjuk Allah", asal: "Gabungan nurul dan huda" },
  { nama: "Nuruliman", jantina: "perempuan", bahasa: "Melayu", makna: "Cahaya keimanan", asal: "Gabungan nurul dan iman" },
  { nama: "Nuruljannah", jantina: "perempuan", bahasa: "Melayu", makna: "Cahaya syurga yang indah", asal: "Gabungan nurul dan jannah" },
  { nama: "Nurulnajwa", jantina: "perempuan", bahasa: "Melayu", makna: "Cahaya bisikan yang cantik", asal: "Gabungan nurul dan najwa" },
  { nama: "Nurzahirah", jantina: "perempuan", bahasa: "Melayu", makna: "Cahaya yang berseri-seri", asal: "Gabungan nur dan zahirah" },

  // ── HURUF Q ──
  { nama: "Qaisarah", jantina: "perempuan", bahasa: "Melayu", makna: "Permaisuri, yang memerintah", asal: "Dari kata Arab qaysar bermaksud permaisuri" },
  { nama: "Qamarul", jantina: "perempuan", bahasa: "Melayu", makna: "Bulan yang indah bercahaya", asal: "Dari kata Arab qamar bermaksud bulan" },
  { nama: "Qistina", jantina: "perempuan", bahasa: "Melayu", makna: "Yang adil dan saksama", asal: "Dari kata Arab qist bermaksud keadilan" },
  { nama: "Qurrata", jantina: "perempuan", bahasa: "Melayu", makna: "Penyejuk mata, penyeri hati", asal: "Dari kata Arab qurrat bermaksud kesejukan" },

  // ── HURUF R ──
  { nama: "Rabiatul", jantina: "perempuan", bahasa: "Melayu", makna: "Musim bunga yang indah", asal: "Dari kata Arab rabi bermaksud musim bunga" },
  { nama: "Radiah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang redha dan puas hati", asal: "Dari kata Arab radha bermaksud redha" },
  { nama: "Rafeah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang tinggi dan mulia", asal: "Dari kata Arab rafa bermaksud tinggi" },
  { nama: "Rafiatul", jantina: "perempuan", bahasa: "Melayu", makna: "Ketinggian yang mulia", asal: "Dari kata Arab rafa bermaksud tinggi" },
  { nama: "Rafidah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang membantu dan menolong", asal: "Dari kata Arab rafada bermaksud membantu" },
  { nama: "Rahimah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang penuh belas kasihan", asal: "Dari kata Arab rahima bermaksud kasih" },
  { nama: "Raihanah", jantina: "perempuan", bahasa: "Melayu", makna: "Bunga yang harum dan wangi", asal: "Nama sahabiyah Nabi yang terkenal" },
  { nama: "Raisah", jantina: "perempuan", bahasa: "Melayu", makna: "Pemimpin wanita yang mulia", asal: "Dari kata Arab raasa bermaksud memimpin" },
  { nama: "Ramlah", jantina: "perempuan", bahasa: "Melayu", makna: "Pasir, yang lembut dan halus", asal: "Nama isteri Nabi Muhammad S.A.W" },
  { nama: "Rania", jantina: "perempuan", bahasa: "Melayu", makna: "Yang memandang dengan penuh kasih", asal: "Dari kata Arab rana bermaksud memandang" },
  { nama: "Raniyah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang memandang dengan mata indah", asal: "Dari kata Arab rana bermaksud memandang" },
  { nama: "Rashidah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang bijaksana dan mendapat hidayah", asal: "Dari kata Arab rashada bermaksud bijak" },
  { nama: "Raudhah", jantina: "perempuan", bahasa: "Melayu", makna: "Taman bunga syurga yang indah", asal: "Dari kata Arab rawdha bermaksud taman" },
  { nama: "Raudhatul", jantina: "perempuan", bahasa: "Melayu", makna: "Taman syurga yang cantik", asal: "Dari kata Arab rawdha bermaksud taman" },
  { nama: "Rawdha", jantina: "perempuan", bahasa: "Melayu", makna: "Taman yang indah dan subur", asal: "Dari kata Arab rawdha bermaksud taman" },
  { nama: "Raya", jantina: "perempuan", bahasa: "Melayu", makna: "Yang menyenangkan dan cantik", asal: "Variasi Melayu bermaksud kesenangan" },
  { nama: "Razanah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang tenang dan berwibawa", asal: "Dari kata Arab razana bermaksud tenang" },
  { nama: "Ridhwanah", jantina: "perempuan", bahasa: "Melayu", makna: "Keredhaan Allah", asal: "Dari kata Arab ridwan bermaksud redha" },
  { nama: "Rifqah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang lemah lembut dan baik hati", asal: "Dari kata Arab rafaqa bermaksud lembut" },
  { nama: "Rikza", jantina: "perempuan", bahasa: "Melayu", makna: "Rezeki, yang diberkati", asal: "Dari kata Arab rizq bermaksud rezeki" },
  { nama: "Rizqiah", jantina: "perempuan", bahasa: "Melayu", makna: "Rezeki yang melimpah", asal: "Dari kata Arab rizq bermaksud rezeki" },
  { nama: "Rohani", jantina: "perempuan", bahasa: "Melayu", makna: "Yang bersifat rohani dan suci", asal: "Dari kata Arab ruh bermaksud roh" },
  { nama: "Rozita", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik seperti mawar", asal: "Variasi Melayu bermaksud bunga mawar" },
  { nama: "Rufaidah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang membantu orang sakit", asal: "Nama sahabiyah pakar perubatan Islam" },
  { nama: "Ruqayyah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang meningkat darjatnya", asal: "Nama puteri Nabi Muhammad S.A.W" },

  // ── HURUF S ──
  { nama: "Saadiah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang bahagia dan bertuah", asal: "Dari kata Arab saida bermaksud bahagia" },
  { nama: "Sabihah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik bersinar pagi", asal: "Dari kata Arab sabaha bermaksud cantik" },
  { nama: "Sabirah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang sabar dan tabah", asal: "Dari kata Arab sabara bermaksud sabar" },
  { nama: "Safiah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang suci dan bersih hati", asal: "Dari kata Arab safa bermaksud jernih" },
  { nama: "Safura", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan bersinar", asal: "Nama isteri Nabi Musa A.S" },
  { nama: "Sakinah", jantina: "perempuan", bahasa: "Melayu", makna: "Ketenangan dan kedamaian", asal: "Dari kata Arab sakana bermaksud tenang" },
  { nama: "Sakura", jantina: "perempuan", bahasa: "Melayu", makna: "Bunga ceri yang cantik", asal: "Nama Jepun bermaksud bunga ceri" },
  { nama: "Saleha", jantina: "perempuan", bahasa: "Melayu", makna: "Yang solehah dan baik", asal: "Dari kata Arab salaha bermaksud baik" },
  { nama: "Salma", jantina: "perempuan", bahasa: "Melayu", makna: "Yang selamat dan sejahtera", asal: "Dari kata Arab salima bermaksud selamat" },
  { nama: "Salsabila", jantina: "perempuan", bahasa: "Melayu", makna: "Mata air syurga yang jernih", asal: "Dari Al-Quran surah Al-Insan" },
  { nama: "Saminah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang berharga dan bernilai tinggi", asal: "Dari kata Arab samana bermaksud berharga" },
  { nama: "Sara", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mulia, puteri", asal: "Nama isteri Nabi Ibrahim A.S" },
  { nama: "Sarah", jantina: "perempuan", bahasa: "Melayu", makna: "Puteri yang mulia", asal: "Variasi dari Sara bermaksud puteri" },
  { nama: "Sharifah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mulia berketurunan baik", asal: "Dari kata Arab sharafa bermaksud mulia" },
  { nama: "Shazana", jantina: "perempuan", bahasa: "Melayu", makna: "Yang harum dan wangi", asal: "Variasi Melayu bermaksud keharuman" },
  { nama: "Shazwani", jantina: "perempuan", bahasa: "Melayu", makna: "Yang harum semerbak", asal: "Variasi Melayu bermaksud keharuman" },
  { nama: "Siti", jantina: "perempuan", bahasa: "Melayu", makna: "Puan yang mulia dan terhormat", asal: "Gelaran wanita mulia dalam Melayu" },
  { nama: "Sofea", jantina: "perempuan", bahasa: "Melayu", makna: "Yang suci dan jernih hatinya", asal: "Dari kata Arab safa bermaksud jernih" },
  { nama: "Sumayyah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang tinggi dan mulia", asal: "Nama syahidah pertama dalam Islam" },
  { nama: "Suraya", jantina: "perempuan", bahasa: "Melayu", makna: "Bintang Pleiades yang cantik", asal: "Nama kumpulan bintang dalam Arab" },
  { nama: "Suriani", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan berseri", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Suriyah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang bersinar seperti matahari", asal: "Dari kata Arab surya bermaksud matahari" },
  { nama: "Syafiqah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang penyayang dan berbelas kasih", asal: "Dari kata Arab syafaqa bermaksud kasih" },
  { nama: "Syahirah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang terkenal dengan kebaikan", asal: "Dari kata Arab syuhrah bermaksud masyhur" },
  { nama: "Syakirah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang bersyukur kepada Allah", asal: "Dari kata Arab syakara bermaksud syukur" },
  { nama: "Syamimi", jantina: "perempuan", bahasa: "Melayu", makna: "Angin lembut yang wangi", asal: "Dari kata Arab syamim bermaksud angin wangi" },
  { nama: "Syarafina", jantina: "perempuan", bahasa: "Melayu", makna: "Yang mulia dan cantik", asal: "Dari kata Arab syarafa bermaksud mulia" },
  { nama: "Syazana", jantina: "perempuan", bahasa: "Melayu", makna: "Yang harum baunya", asal: "Variasi Melayu bermaksud keharuman" },
  { nama: "Syazlin", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan menarik", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Syazwana", jantina: "perempuan", bahasa: "Melayu", makna: "Yang harum dan wangi semerbak", asal: "Variasi Melayu bermaksud keharuman" },
  { nama: "Syazwani", jantina: "perempuan", bahasa: "Melayu", makna: "Yang harum seperti bunga", asal: "Variasi Melayu bermaksud keharuman" },

  // ── HURUF T ──
  { nama: "Tasneem", jantina: "perempuan", bahasa: "Melayu", makna: "Mata air syurga tertinggi", asal: "Dari Al-Quran surah Al-Mutaffifin" },
  { nama: "Thahirah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang suci dan bersih", asal: "Dari kata Arab tahara bermaksud suci" },
  { nama: "Thurayya", jantina: "perempuan", bahasa: "Melayu", makna: "Bintang Pleiades yang cantik", asal: "Nama kumpulan bintang dalam Arab" },
  { nama: "Tiqah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang dipercayai dan amanah", asal: "Dari kata Arab thiqa bermaksud percaya" },

  // ── HURUF U ──
  { nama: "Ulfah", jantina: "perempuan", bahasa: "Melayu", makna: "Persahabatan dan kemesraan", asal: "Dari kata Arab alifa bermaksud mesra" },
  { nama: "Umaimah", jantina: "perempuan", bahasa: "Melayu", makna: "Ibu kecil yang disayangi", asal: "Nama sahabiyah Nabi Muhammad S.A.W" },
  { nama: "Umi", jantina: "perempuan", bahasa: "Melayu", makna: "Ibuku, yang dikasihi", asal: "Dari kata Arab umm bermaksud ibu" },
  { nama: "Umniyah", jantina: "perempuan", bahasa: "Melayu", makna: "Harapan yang indah", asal: "Dari kata Arab tamanna bermaksud harapan" },
  { nama: "Urwah", jantina: "perempuan", bahasa: "Melayu", makna: "Pegangan yang kuat dan teguh", asal: "Dari kata Arab urwah bermaksud pegangan" },

  // ── HURUF W ──
  { nama: "Wardah", jantina: "perempuan", bahasa: "Melayu", makna: "Bunga ros yang cantik", asal: "Dari kata Arab ward bermaksud ros" },
  { nama: "Wardina", jantina: "perempuan", bahasa: "Melayu", makna: "Bunga ros yang indah", asal: "Dari kata Arab ward bermaksud ros" },
  { nama: "Watie", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan manis", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Widad", jantina: "perempuan", bahasa: "Melayu", makna: "Cinta dan kasih sayang tulus", asal: "Dari kata Arab wadda bermaksud cinta" },
  { nama: "Wieda", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan menawan", asal: "Variasi Melayu bermaksud kecantikan" },

  // ── HURUF Y ──
  { nama: "Yasmin", jantina: "perempuan", bahasa: "Melayu", makna: "Bunga jasmine yang harum", asal: "Nama bunga yang harum dalam Arab" },
  { nama: "Yusra", jantina: "perempuan", bahasa: "Melayu", makna: "Kemudahan, yang mudah urusannya", asal: "Dari Al-Quran surah Al-Insyirah" },
  { nama: "Yusrina", jantina: "perempuan", bahasa: "Melayu", makna: "Yang memberi kemudahan", asal: "Dari kata Arab yusra bermaksud mudah" },

  // ── HURUF Z ──
  { nama: "Zafirah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang berjaya dan menang", asal: "Dari kata Arab zafara bermaksud menang" },
  { nama: "Zahirah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang berseri dan bercahaya", asal: "Dari kata Arab zahara bermaksud bersinar" },
  { nama: "Zahra", jantina: "perempuan", bahasa: "Melayu", makna: "Bunga, yang bersinar cerah", asal: "Gelaran Saidatina Fatimah Al-Zahra" },
  { nama: "Zahrah", jantina: "perempuan", bahasa: "Melayu", makna: "Bunga yang cantik bersinar", asal: "Dari kata Arab zahara bermaksud bersinar" },
  { nama: "Zaidatul", jantina: "perempuan", bahasa: "Melayu", makna: "Pertambahan yang mulia", asal: "Dari kata Arab zada bermaksud bertambah" },
  { nama: "Zainab", jantina: "perempuan", bahasa: "Melayu", makna: "Pokok yang harum dan mulia", asal: "Nama puteri Nabi Muhammad S.A.W" },
  { nama: "Zainatul", jantina: "perempuan", bahasa: "Melayu", makna: "Hiasan yang mulia", asal: "Dari kata Arab zayn bermaksud hiasan" },
  { nama: "Zaleen", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan menarik", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Zalena", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik dan bersinar", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Zarith", jantina: "perempuan", bahasa: "Melayu", makna: "Bintang yang bersinar", asal: "Variasi Melayu bermaksud bintang" },
  { nama: "Zarith Sofea", jantina: "perempuan", bahasa: "Melayu", makna: "Bintang yang suci hati", asal: "Gabungan Zarith dan Sofea" },
  { nama: "Zaty", jantina: "perempuan", bahasa: "Melayu", makna: "Diri, yang bermakna dirinya", asal: "Dari kata Arab dzat bermaksud diri" },
  { nama: "Zawiyah", jantina: "perempuan", bahasa: "Melayu", makna: "Sudut, yang istimewa", asal: "Dari kata Arab zawiya bermaksud sudut" },
  { nama: "Zayyanah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang dihiasi dengan kebaikan", asal: "Dari kata Arab zayyanna bermaksud menghias" },
  { nama: "Ziyanah", jantina: "perempuan", bahasa: "Melayu", makna: "Hiasan, yang menghiasi", asal: "Dari kata Arab ziyana bermaksud hiasan" },
  { nama: "Zubaidah", jantina: "perempuan", bahasa: "Melayu", makna: "Yang terbaik, seperti krim susu", asal: "Dari kata Arab zubd bermaksud terbaik" },
  { nama: "Zulaika", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik jelita", asal: "Variasi dari Zulaikha" },
  { nama: "Zulaikha", jantina: "perempuan", bahasa: "Melayu", makna: "Yang cantik jelita memukau", asal: "Dari kisah Nabi Yusuf A.S" },
  { nama: "Zulfa", jantina: "perempuan", bahasa: "Melayu", makna: "Yang dekat kepada Allah", asal: "Dari kata Arab zulfa bermaksud dekat" },
  { nama: "Zuraida", jantina: "perempuan", bahasa: "Melayu", makna: "Bunga-bungaan yang indah", asal: "Dari kata Arab zuhr bermaksud bunga" },
  { nama: "Zuraidah", jantina: "perempuan", bahasa: "Melayu", makna: "Bunga-bungaan yang cantik", asal: "Variasi dari Zuraida" },
  { nama: "Zuriani", jantina: "perempuan", bahasa: "Melayu", makna: "Bunga yang indah dan cantik", asal: "Dari kata Arab zuhr bermaksud bunga" },
];
