// MAMAEXPERT — nama-data-3.js
// International — Jepun, Korea, Perancis, Spanish, English, Scandinavian, Greek, Latin, Hebrew

const namaJepunLelaki = [
  { nama: "Akio", makna: "Lelaki yang cerah dan cerdas", asal: "Dari Jepun aki (cerah) dan o (lelaki)" },
  { nama: "Akira", makna: "Yang terang, yang cerdas", asal: "Dari bahasa Jepun bermaksud terang" },
  { nama: "Aoi", makna: "Biru, seperti langit yang jernih", asal: "Dari bahasa Jepun bermaksud biru" },
  { nama: "Daichi", makna: "Tanah yang besar, yang kukuh", asal: "Dari Jepun dai (besar) dan chi (tanah)" },
  { nama: "Daisuke", makna: "Pembantu yang besar", asal: "Dari Jepun dai (besar) dan suke (pembantu)" },
  { nama: "Fujio", makna: "Lelaki pokok wisteria", asal: "Dari Jepun fuji (wisteria) dan o (lelaki)" },
  { nama: "Genki", makna: "Yang sihat, yang bersemangat", asal: "Dari bahasa Jepun bermaksud sihat" },
  { nama: "Haru", makna: "Musim bunga, yang segar", asal: "Dari bahasa Jepun bermaksud musim bunga" },
  { nama: "Haruki", makna: "Yang bersinar di musim bunga", asal: "Dari Jepun haru (musim bunga) dan ki (bersinar)" },
  { nama: "Hayate", makna: "Angin yang kencang", asal: "Dari bahasa Jepun bermaksud angin kencang" },
  { nama: "Hayato", makna: "Orang yang cepat seperti elang", asal: "Dari Jepun haya (cepat) dan to (orang)" },
  { nama: "Hibiki", makna: "Bunyi, yang bergema", asal: "Dari bahasa Jepun bermaksud gema" },
  { nama: "Hikaru", makna: "Yang bercahaya, yang bersinar", asal: "Dari bahasa Jepun bermaksud bersinar" },
  { nama: "Hiro", makna: "Murah hati, yang luas hati", asal: "Dari bahasa Jepun bermaksud luas" },
  { nama: "Hiroki", makna: "Pokok yang luas dan kuat", asal: "Dari Jepun hiro (luas) dan ki (pokok)" },
  { nama: "Hiroshi", makna: "Yang murah hati, yang besar", asal: "Dari bahasa Jepun bermaksud murah hati" },
  { nama: "Isamu", makna: "Yang berani, yang penuh semangat", asal: "Dari bahasa Jepun bermaksud berani" },
  { nama: "Jiro", makna: "Anak kedua yang baik", asal: "Dari Jepun ji (kedua) dan ro (anak lelaki)" },
  { nama: "Jun", makna: "Yang patuh, yang lembut", asal: "Dari bahasa Jepun bermaksud patuh" },
  { nama: "Kaito", makna: "Laut dan terbang, yang bebas", asal: "Dari Jepun kai (laut) dan to (terbang)" },
  { nama: "Kenji", makna: "Anak lelaki yang kuat dan bijak", asal: "Dari Jepun ken (kuat) dan ji (anak)" },
  { nama: "Kento", makna: "Yang kukuh dan berbudi", asal: "Dari Jepun ken (kukuh) dan to (berbudi)" },
  { nama: "Kenzo", makna: "Ketiga yang sihat", asal: "Dari Jepun ken (sihat) dan zo (ketiga)" },
  { nama: "Koji", makna: "Yang bersinar dengan kegembiraan", asal: "Dari Jepun ko (gembira) dan ji (bersinar)" },
  { nama: "Kotaro", makna: "Anak lelaki yang besar dan kuat", asal: "Dari Jepun ko (besar) dan taro (anak)" },
  { nama: "Makoto", makna: "Yang ikhlas, yang jujur", asal: "Dari bahasa Jepun bermaksud ikhlas" },
  { nama: "Masaki", makna: "Pokok yang berkembang maju", asal: "Dari Jepun masa (berkembang) dan ki (pokok)" },
  { nama: "Masato", makna: "Yang benar dan adil", asal: "Dari Jepun masa (benar) dan to (orang)" },
  { nama: "Minoru", makna: "Yang berbuah, yang berjaya", asal: "Dari bahasa Jepun bermaksud buah" },
  { nama: "Naoki", makna: "Pokok yang lurus dan kuat", asal: "Dari Jepun nao (lurus) dan ki (pokok)" },
  { nama: "Nao", makna: "Yang lurus, yang jujur", asal: "Dari bahasa Jepun bermaksud lurus" },
  { nama: "Noboru", makna: "Yang naik, yang meningkat", asal: "Dari bahasa Jepun bermaksud naik" },
  { nama: "Riku", makna: "Daratan, yang kukuh", asal: "Dari bahasa Jepun bermaksud daratan" },
  { nama: "Ren", makna: "Teratai, yang bersih", asal: "Dari bahasa Jepun bermaksud teratai" },
  { nama: "Ryo", makna: "Yang sejuk, yang luas", asal: "Dari bahasa Jepun bermaksud luas" },
  { nama: "Ryota", makna: "Yang besar dan kuat", asal: "Dari Jepun ryo (besar) dan ta (kuat)" },
  { nama: "Ryusei", makna: "Bintang jatuh, yang bersinar", asal: "Dari Jepun ryu (naga) dan sei (bintang)" },
  { nama: "Sho", makna: "Terbang tinggi, yang bebas", asal: "Dari bahasa Jepun bermaksud terbang" },
  { nama: "Shota", makna: "Yang kuat dan terbang bebas", asal: "Dari Jepun sho (terbang) dan ta (kuat)" },
  { nama: "Sota", makna: "Angin laut yang segar", asal: "Dari Jepun so (angin laut) dan ta (besar)" },
  { nama: "Subaru", makna: "Kumpulan bintang Pleiades", asal: "Dari bahasa Jepun bermaksud bintang Pleiades" },
  { nama: "Takeru", makna: "Yang gagah berani", asal: "Dari bahasa Jepun bermaksud berani" },
  { nama: "Takeshi", makna: "Yang kuat seperti buluh", asal: "Dari Jepun take (buluh) dan shi (kuat)" },
  { nama: "Taro", makna: "Anak lelaki sulung yang besar", asal: "Dari bahasa Jepun bermaksud anak sulung" },
  { nama: "Tatsuya", makna: "Yang seperti naga", asal: "Dari Jepun tatsu (naga) dan ya (orang)" },
  { nama: "Tomo", makna: "Sahabat, yang setia", asal: "Dari bahasa Jepun bermaksud sahabat" },
  { nama: "Toru", makna: "Yang menembus, yang luar biasa", asal: "Dari bahasa Jepun bermaksud menembus" },
  { nama: "Wataru", makna: "Yang merentasi, yang luas", asal: "Dari bahasa Jepun bermaksud merentasi" },
  { nama: "Yamato", makna: "Nama kuno Jepun, yang mulia", asal: "Nama kuno negara Jepun" },
  { nama: "Yuki", makna: "Salji, yang bahagia", asal: "Dari bahasa Jepun bermaksud salji" },
  { nama: "Yuto", makna: "Orang yang berguna dan luas", asal: "Dari Jepun yu (berguna) dan to (luas)" },
  { nama: "Yuuki", makna: "Keberanian, yang berani", asal: "Dari Jepun yuu (berani) dan ki (semangat)" },
];

const namaJepunPerempuan = [
  { nama: "Aiko", makna: "Anak yang dicintai", asal: "Dari Jepun ai (cinta) dan ko (anak)" },
  { nama: "Akane", makna: "Merah yang cerah", asal: "Dari bahasa Jepun bermaksud merah" },
  { nama: "Akemi", makna: "Kecantikan yang cerah", asal: "Dari Jepun ake (cerah) dan mi (kecantikan)" },
  { nama: "Akiko", makna: "Anak yang cerah dan cerdas", asal: "Dari Jepun aki (cerah) dan ko (anak)" },
  { nama: "Amaya", makna: "Hujan malam", asal: "Dari Jepun ama (hujan) dan ya (malam)" },
  { nama: "Asahi", makna: "Cahaya matahari pagi", asal: "Dari Jepun asa (pagi) dan hi (matahari)" },
  { nama: "Ayame", makna: "Bunga iris", asal: "Dari bahasa Jepun bermaksud bunga iris" },
  { nama: "Ayano", makna: "Kain warna-warni yang indah", asal: "Dari Jepun aya (kain) dan no (medan)" },
  { nama: "Azusa", makna: "Pokok katalpa, yang cantik", asal: "Dari bahasa Jepun bermaksud pokok katalpa" },
  { nama: "Chiaki", makna: "Cahaya seribu musim luruh", asal: "Dari Jepun chi (seribu) dan aki (musim luruh)" },
  { nama: "Chiharu", makna: "Seribu musim bunga", asal: "Dari Jepun chi (seribu) dan haru (musim bunga)" },
  { nama: "Chika", makna: "Yang dekat, yang dikasihi", asal: "Dari bahasa Jepun bermaksud dekat" },
  { nama: "Chikako", makna: "Anak yang bijak dan dekat", asal: "Dari Jepun chika dan ko (anak)" },
  { nama: "Emiko", makna: "Anak yang cantik dan tersenyum", asal: "Dari Jepun emi (senyum) dan ko (anak)" },
  { nama: "Erika", makna: "Pokok heather yang cantik", asal: "Dari Jepun bermaksud cantik seperti heather" },
  { nama: "Fumiko", makna: "Anak yang bersejarah", asal: "Dari Jepun fumi (sejarah) dan ko (anak)" },
  { nama: "Hana", makna: "Bunga yang mekar, kebahagiaan", asal: "Dari bahasa Jepun bermaksud bunga" },
  { nama: "Hanako", makna: "Anak bunga yang cantik", asal: "Dari Jepun hana (bunga) dan ko (anak)" },
  { nama: "Haruka", makna: "Yang jauh, yang bebas", asal: "Dari bahasa Jepun bermaksud jauh" },
  { nama: "Haruko", makna: "Anak musim bunga", asal: "Dari Jepun haru (musim bunga) dan ko (anak)" },
  { nama: "Hina", makna: "Cahaya, yang bersinar", asal: "Dari bahasa Jepun bermaksud cahaya" },
  { nama: "Hinata", makna: "Di bawah sinar matahari", asal: "Dari Jepun hi (matahari) dan nata (tempat)" },
  { nama: "Hiromi", makna: "Kecantikan yang luas", asal: "Dari Jepun hiro (luas) dan mi (kecantikan)" },
  { nama: "Honoka", makna: "Bunga gandum yang harmoni", asal: "Dari Jepun ho (gandum) dan hana (bunga)" },
  { nama: "Hotaru", makna: "Kelip-kelip, yang bersinar kecil", asal: "Dari bahasa Jepun bermaksud kelip-kelip" },
  { nama: "Ichika", makna: "Bunga satu seribu", asal: "Dari Jepun ichi (satu) dan ka (bunga)" },
  { nama: "Izumi", makna: "Mata air, yang segar", asal: "Dari bahasa Jepun bermaksud mata air" },
  { nama: "Kaede", makna: "Daun maple, yang cantik", asal: "Dari bahasa Jepun bermaksud daun maple" },
  { nama: "Kagami", makna: "Cermin, yang mencerminkan", asal: "Dari bahasa Jepun bermaksud cermin" },
  { nama: "Kaho", makna: "Bunga yang harum", asal: "Dari Jepun ka (harum) dan ho (bunga)" },
  { nama: "Kairi", makna: "Laut yang indah", asal: "Dari Jepun kai (laut) dan ri (lasa)" },
  { nama: "Kanon", makna: "Bunyi bunga, yang merdu", asal: "Dari Jepun ka (bunga) dan non (bunyi)" },
  { nama: "Karin", makna: "Bunga yang cantik", asal: "Dari Jepun ka (bunga) dan rin (cantik)" },
  { nama: "Kasumi", makna: "Kabus, yang misterius dan indah", asal: "Dari bahasa Jepun bermaksud kabus" },
  { nama: "Kazumi", makna: "Kecantikan yang harmoni", asal: "Dari Jepun kazu (harmoni) dan mi (cantik)" },
  { nama: "Kirara", makna: "Yang bersinar-sinar", asal: "Dari bahasa Jepun bermaksud bersinar" },
  { nama: "Kotone", makna: "Bunyi koto yang indah", asal: "Dari Jepun koto (alat muzik) dan ne (bunyi)" },
  { nama: "Kumiko", makna: "Anak yang permata abadi", asal: "Dari Jepun kumi (abadi) dan ko (anak)" },
  { nama: "Kurumi", makna: "Buah walnut, yang berharga", asal: "Dari bahasa Jepun bermaksud walnut" },
  { nama: "Maiko", makna: "Anak penari yang cantik", asal: "Dari Jepun mai (menari) dan ko (anak)" },
  { nama: "Makiko", makna: "Anak yang benar", asal: "Dari Jepun maki (benar) dan ko (anak)" },
  { nama: "Manami", makna: "Kecantikan kasih sayang", asal: "Dari Jepun mana (kasih) dan mi (cantik)" },
  { nama: "Mao", makna: "Benar dan tulus", asal: "Dari bahasa Jepun bermaksud tulus" },
  { nama: "Mayu", makna: "Kening yang cantik", asal: "Dari bahasa Jepun bermaksud kening" },
  { nama: "Michiko", makna: "Anak di jalan kebenaran", asal: "Dari Jepun michi (jalan) dan ko (anak)" },
  { nama: "Midori", makna: "Hijau, yang segar dan hidup", asal: "Dari bahasa Jepun bermaksud hijau" },
  { nama: "Miho", makna: "Lautan kecantikan", asal: "Dari Jepun mi (kecantikan) dan ho (lautan)" },
  { nama: "Mika", makna: "Cahaya cantik", asal: "Dari Jepun mi (cantik) dan ka (cahaya)" },
  { nama: "Miki", makna: "Pokok yang berkembang cantik", asal: "Dari Jepun mi (cantik) dan ki (pokok)" },
  { nama: "Mio", makna: "Tiga lautan yang indah", asal: "Dari Jepun mi (tiga) dan o (lautan)" },
  { nama: "Misaki", makna: "Tanjung yang cantik", asal: "Dari Jepun mi (cantik) dan saki (tanjung)" },
  { nama: "Mitsuki", makna: "Cahaya bulan yang cantik", asal: "Dari Jepun mitsu (cahaya) dan ki (bulan)" },
  { nama: "Miyu", makna: "Cantik dan lembut", asal: "Dari Jepun mi (cantik) dan yu (lembut)" },
  { nama: "Miyuki", makna: "Salji yang cantik", asal: "Dari Jepun mi (cantik) dan yuki (salji)" },
  { nama: "Mizuki", makna: "Cahaya air yang cantik", asal: "Dari Jepun mizu (air) dan ki (cahaya)" },
  { nama: "Momoka", makna: "Bunga pic yang cantik", asal: "Dari Jepun momo (pic) dan ka (bunga)" },
  { nama: "Momoko", makna: "Anak buah pic", asal: "Dari Jepun momo (pic) dan ko (anak)" },
  { nama: "Nana", makna: "Tujuh bunga yang cantik", asal: "Dari Jepun nana (tujuh) dan na (bunga)" },
  { nama: "Nanami", makna: "Tujuh lautan yang cantik", asal: "Dari Jepun nana (tujuh) dan mi (laut)" },
  { nama: "Nao", makna: "Yang lurus, yang jujur", asal: "Dari bahasa Jepun bermaksud lurus" },
  { nama: "Natsuki", makna: "Musim panas yang bersinar", asal: "Dari Jepun natsu (panas) dan ki (bersinar)" },
  { nama: "Natsumi", makna: "Kecantikan musim panas", asal: "Dari Jepun natsu (musim panas) dan mi (cantik)" },
  { nama: "Rin", makna: "Yang dingin dan elegan", asal: "Dari bahasa Jepun bermaksud elegan" },
  { nama: "Rina", makna: "Yang bersih dan murni", asal: "Dari bahasa Jepun bermaksud kejernihan" },
  { nama: "Risa", makna: "Kecantikan yang cerah", asal: "Dari Jepun ri (cerah) dan sa (cantik)" },
  { nama: "Sakura", makna: "Bunga ceri yang cantik", asal: "Dari bahasa Jepun bermaksud bunga ceri" },
  { nama: "Sana", makna: "Yang bersinar, yang mulia", asal: "Dari bahasa Arab bermaksud cahaya" },
  { nama: "Satsuki", makna: "Bulan Mei yang bersinar", asal: "Dari Jepun satsu (bulan Mei) dan ki (bersinar)" },
  { nama: "Saya", makna: "Yang cepat, yang jernih", asal: "Dari bahasa Jepun bermaksud jernih" },
  { nama: "Sayaka", makna: "Yang jernih dan cantik", asal: "Dari Jepun saya (jernih) dan ka (cantik)" },
  { nama: "Shiho", makna: "Empat lautan yang indah", asal: "Dari Jepun shi (empat) dan ho (lautan)" },
  { nama: "Shiori", makna: "Penanda buku, yang bersejarah", asal: "Dari bahasa Jepun bermaksud penanda buku" },
  { nama: "Sora", makna: "Langit yang luas", asal: "Dari bahasa Jepun bermaksud langit" },
  { nama: "Sumire", makna: "Bunga violet, yang cantik", asal: "Dari bahasa Jepun bermaksud violet" },
  { nama: "Yuki", makna: "Salji, kebahagiaan yang murni", asal: "Dari bahasa Jepun bermaksud salji" },
  { nama: "Yukiko", makna: "Anak salji yang cantik", asal: "Dari Jepun yuki (salji) dan ko (anak)" },
  { nama: "Yuna", makna: "Kelapa yang lembut", asal: "Dari bahasa Jepun bermaksud kelapa" },
  { nama: "Yuri", makna: "Bunga lily, yang cantik", asal: "Dari bahasa Jepun bermaksud bunga lily" },
];

const namaKoreaLelaki = [
  { nama: "Ahn", makna: "Yang aman, yang damai", asal: "Nama Korea bermaksud keamanan" },
  { nama: "Baek", makna: "Yang putih, yang bersih", asal: "Nama Korea bermaksud putih" },
  { nama: "Bin", makna: "Yang berbudi, yang elegan", asal: "Nama Korea bermaksud elegan" },
  { nama: "Bomi", makna: "Keindahan musim bunga", asal: "Dari Korea bom (musim bunga) dan i (cantik)" },
  { nama: "Chan", makna: "Yang bersinar, yang cemerlang", asal: "Nama Korea bermaksud bersinar" },
  { nama: "Choi", makna: "Yang tinggi, yang unggul", asal: "Nama keluarga Korea yang popular" },
  { nama: "Daesung", makna: "Kejayaan yang besar", asal: "Dari Korea dae (besar) dan sung (kejayaan)" },
  { nama: "Daewon", makna: "Taman yang besar", asal: "Dari Korea dae (besar) dan won (taman)" },
  { nama: "Dojun", makna: "Yang bermoral dan berbudi", asal: "Dari Korea do (bermoral) dan jun (berbudi)" },
  { nama: "Dongha", makna: "Laut timur yang besar", asal: "Dari Korea dong (timur) dan ha (laut)" },
  { nama: "Eunwoo", makna: "Belas kasihan yang berbudi", asal: "Dari Korea eun (belas) dan woo (berbudi)" },
  { nama: "Gunwoo", makna: "Yang mulia dan berbudi", asal: "Dari Korea gun (mulia) dan woo (berbudi)" },
  { nama: "Haneul", makna: "Langit yang luas", asal: "Nama Korea bermaksud langit" },
  { nama: "Hankyul", makna: "Keputusan yang satu", asal: "Dari Korea han (satu) dan kyul (keputusan)" },
  { nama: "Hyun", makna: "Yang bijak, yang cerdas", asal: "Nama Korea bermaksud bijaksana" },
  { nama: "Hyunjun", makna: "Pahlawan yang bijaksana", asal: "Dari Korea hyun (bijak) dan jun (pahlawan)" },
  { nama: "Injun", makna: "Manusia yang baik dan mulia", asal: "Dari Korea in (manusia) dan jun (mulia)" },
  { nama: "Jaehwan", makna: "Yang bersinar dan berbudi", asal: "Dari Korea jae (berbudi) dan hwan (bersinar)" },
  { nama: "Jaehyun", makna: "Yang bijak dan berbudi", asal: "Dari Korea jae (berbudi) dan hyun (bijak)" },
  { nama: "Jaemin", makna: "Yang bijak dan cerah", asal: "Dari Korea jae (bijak) dan min (cerah)" },
  { nama: "Jaewon", makna: "Asal yang berbudi", asal: "Dari Korea jae (berbudi) dan won (asal)" },
  { nama: "Jihun", makna: "Bakat dan kepintaran", asal: "Dari Korea ji (bakat) dan hun (kepintaran)" },
  { nama: "Jinho", makna: "Yang mulia dan baik", asal: "Dari Korea jin (mulia) dan ho (baik)" },
  { nama: "Jungkook", makna: "Yang kukuh dan mulia", asal: "Dari Korea jung (kukuh) dan kook (mulia)" },
  { nama: "Junho", makna: "Yang baik dan berbudi", asal: "Dari Korea jun (berbudi) dan ho (baik)" },
  { nama: "Kang", makna: "Yang kuat, yang kukuh", asal: "Nama Korea bermaksud kekuatan" },
  { nama: "Kyungmin", makna: "Yang mengagumkan dan cerah", asal: "Dari Korea kyung (mengagumkan) dan min (cerah)" },
  { nama: "Minjun", makna: "Yang cerah dan mulia", asal: "Dari Korea min (cerah) dan jun (mulia)" },
  { nama: "Minseok", makna: "Yang cerah dan mulia", asal: "Dari Korea min (cerah) dan seok (mulia)" },
  { nama: "Seojun", makna: "Yang baik dan mulia", asal: "Dari Korea seo (baik) dan jun (mulia)" },
];

const namaKoreaPerempuan = [
  { nama: "Areum", makna: "Yang cantik", asal: "Dari Korea areum bermaksud cantik" },
  { nama: "Bora", makna: "Ungu, yang cantik", asal: "Nama Korea bermaksud warna ungu" },
  { nama: "Chaeyeon", makna: "Bunga yang cantik", asal: "Dari Korea chae (berwarna) dan yeon (bunga)" },
  { nama: "Dahye", makna: "Cantik seperti rusa", asal: "Dari Korea da (banyak) dan hye (kebijaksanaan)" },
  { nama: "Dasom", makna: "Penuh dengan kasih sayang", asal: "Dari Korea da (banyak) dan som (kasih)" },
  { nama: "Eunha", makna: "Belas kasihan dan rahmat", asal: "Dari Korea eun (belas) dan ha (rahmat)" },
  { nama: "Eunjin", makna: "Belas kasihan yang mulia", asal: "Dari Korea eun (belas) dan jin (mulia)" },
  { nama: "Goeun", makna: "Yang cantik dan elok", asal: "Nama Korea bermaksud cantik" },
  { nama: "Haesol", makna: "Salji laut yang cantik", asal: "Dari Korea hae (laut) dan sol (salji)" },
  { nama: "Hana", makna: "Satu, yang istimewa", asal: "Dari Korea hana bermaksud satu yang istimewa" },
  { nama: "Haneul", makna: "Langit yang luas", asal: "Nama Korea bermaksud langit" },
  { nama: "Hayeon", makna: "Bunga musim panas", asal: "Dari Korea ha (musim panas) dan yeon (bunga)" },
  { nama: "Heewon", makna: "Taman yang gembira", asal: "Dari Korea hee (gembira) dan won (taman)" },
  { nama: "Hyeji", makna: "Yang bijak dan cantik", asal: "Dari Korea hye (bijak) dan ji (cantik)" },
  { nama: "Hyejin", makna: "Mutiara yang bijak", asal: "Dari Korea hye (bijak) dan jin (mutiara)" },
  { nama: "Hyuna", makna: "Yang cerah dan cantik", asal: "Dari Korea hyun (cerah) dan a (cantik)" },
  { nama: "Inyoung", makna: "Manusia yang mulia", asal: "Dari Korea in (manusia) dan young (mulia)" },
  { nama: "Jieun", makna: "Belas kasihan dan kebijaksanaan", asal: "Dari Korea ji (bijak) dan eun (belas)" },
  { nama: "Jihyo", makna: "Yang bijak dan baik", asal: "Dari Korea ji (bijak) dan hyo (baik)" },
  { nama: "Jimin", makna: "Yang cantik dan cerah", asal: "Dari Korea ji (cantik) dan min (cerah)" },
  { nama: "Jisoo", makna: "Yang bijak dan baik", asal: "Dari Korea ji (bijak) dan soo (baik)" },
  { nama: "Minji", makna: "Yang cantik dan bijak", asal: "Dari Korea min (cantik) dan ji (bijak)" },
  { nama: "Minkyung", makna: "Yang cantik dan mengagumkan", asal: "Dari Korea min (cantik) dan kyung (mengagumkan)" },
  { nama: "Naeun", makna: "Belas kasihan yang lembut", asal: "Dari Korea na (lembut) dan eun (belas)" },
  { nama: "Nayeon", makna: "Yang cantik dan lembut", asal: "Dari Korea na (cantik) dan yeon (lembut)" },
  { nama: "Seoyeon", makna: "Yang baik dan lembut", asal: "Dari Korea seo (baik) dan yeon (lembut)" },
  { nama: "Seulgi", makna: "Yang bijak dan kuat", asal: "Dari Korea seul (bijak) dan gi (kuat)" },
  { nama: "Sohee", makna: "Yang lembut dan gembira", asal: "Dari Korea so (lembut) dan hee (gembira)" },
  { nama: "Somi", makna: "Yang lembut dan cantik", asal: "Dari Korea so (lembut) dan mi (cantik)" },
  { nama: "Suzy", makna: "Bunga lily, yang cantik", asal: "Variasi Korea dari nama Eropah Susan" },
];

const namaScandinavianLelaki = [
  { nama: "Anders", makna: "Yang kuat dan berani", asal: "Scandinavian bermaksud kuat" },
  { nama: "Bjorn", makna: "Beruang, yang kuat", asal: "Dari Norse bermaksud beruang" },
  { nama: "Erik", makna: "Penguasa abadi", asal: "Dari Norse er (abadi) dan rik (penguasa)" },
  { nama: "Finn", makna: "Yang cerah, dari Finland", asal: "Nama Scandinavian bermaksud putih" },
  { nama: "Frederik", makna: "Raja yang damai", asal: "Dari German fred (damai) dan rik (raja)" },
  { nama: "Gustav", makna: "Tongkat Tuhan, yang mulia", asal: "Nama Scandinavian bermaksud staf Tuhan" },
  { nama: "Gunnar", makna: "Pejuang, yang berani berperang", asal: "Dari Norse bermaksud pejuang berani" },
  { nama: "Harald", makna: "Penguasa tentera", asal: "Dari Norse har (tentera) dan wald (penguasa)" },
  { nama: "Henrik", makna: "Penguasa rumah", asal: "Variasi Scandinavian dari Henry" },
  { nama: "Ingvar", makna: "Prajurit Ing yang kuat", asal: "Dari Norse ing (dewa) dan var (prajurit)" },
  { nama: "Jonas", makna: "Merpati Allah", asal: "Variasi Scandinavian dari Yunus" },
  { nama: "Karl", makna: "Lelaki yang bebas", asal: "Dari German bermaksud lelaki bebas" },
  { nama: "Lars", makna: "Yang dimahkota laurel", asal: "Variasi Scandinavian dari Laurence" },
  { nama: "Leif", makna: "Pewaris, yang diwarisi", asal: "Dari Norse bermaksud pewaris" },
  { nama: "Linus", makna: "Yang dari pokok flax", asal: "Dari Greek bermaksud pokok flax" },
  { nama: "Magnus", makna: "Yang besar, yang agung", asal: "Dari Latin bermaksud besar" },
  { nama: "Markus", makna: "Dari Mars, yang gagah", asal: "Variasi Scandinavian dari Marcus" },
  { nama: "Mikael", makna: "Siapakah seperti Allah", asal: "Variasi Scandinavian dari Mikail" },
  { nama: "Nils", makna: "Kemenangan rakyat", asal: "Variasi Scandinavian dari Nicholas" },
  { nama: "Oskar", makna: "Lembing Tuhan", asal: "Dari Norse bermaksud lembing Tuhan" },
  { nama: "Petter", makna: "Batu, yang kukuh", asal: "Variasi Scandinavian dari Peter" },
  { nama: "Rolf", makna: "Serigala yang terkenal", asal: "Dari Norse bermaksud serigala masyhur" },
  { nama: "Sigurd", makna: "Penjaga kemenangan", asal: "Dari Norse sig (menang) dan urd (penjaga)" },
  { nama: "Soren", makna: "Yang tegas, yang kuat", asal: "Dari Latin Severinus bermaksud tegas" },
  { nama: "Stefan", makna: "Yang bermahkota", asal: "Variasi Scandinavian dari Stephen" },
  { nama: "Stig", makna: "Yang mengembara", asal: "Dari Norse bermaksud pengembara" },
  { nama: "Thor", makna: "Tuhan guruh, yang kuat", asal: "Nama dewa Norse bermaksud guruh" },
  { nama: "Tobias", makna: "Allah adalah baik", asal: "Variasi Scandinavian dari Hebrew Tobiah" },
  { nama: "Torsten", makna: "Batu Thor", asal: "Dari Norse thor (dewa) dan sten (batu)" },
  { nama: "Vidar", makna: "Hutan yang luas", asal: "Dari Norse bermaksud hutan luas" },
];

const namaScandinavianPerempuan = [
  { nama: "Astrid", makna: "Kecantikan ilahi", asal: "Dari Norse as (dewa) dan frid (cantik)" },
  { nama: "Birgit", makna: "Yang mulia, yang kuat", asal: "Dari Celtic bermaksud kekuatan" },
  { nama: "Britta", makna: "Yang mulia, yang tinggi", asal: "Variasi Scandinavian dari Bridget" },
  { nama: "Dagny", makna: "Hari baru yang baru bermula", asal: "Dari Norse dag (hari) dan ny (baru)" },
  { nama: "Elsa", makna: "Yang bersumpah kepada Allah", asal: "Variasi Scandinavian dari Elizabeth" },
  { nama: "Embla", makna: "Pokok elm, nenek moyang", asal: "Dari Norse bermaksud pokok elm" },
  { nama: "Freya", makna: "Dewi cinta dan kesuburan", asal: "Nama dewi Norse bermaksud yang mulia" },
  { nama: "Gunhild", makna: "Pejuang perang wanita", asal: "Dari Norse gun (perang) dan hild (wanita)" },
  { nama: "Hanne", makna: "Allah memberi rahmat", asal: "Variasi Scandinavian dari Hannah" },
  { nama: "Helga", makna: "Yang suci, yang diberkati", asal: "Dari Norse bermaksud suci" },
  { nama: "Ida", makna: "Yang bekerja keras", asal: "Dari German bermaksud kerja keras" },
  { nama: "Inga", makna: "Yang dilindungi Ing", asal: "Dari Norse bermaksud dilindungi dewa" },
  { nama: "Ingrid", makna: "Yang cantik dan subur", asal: "Dari Norse ing (dewa) dan frid (cantik)" },
  { nama: "Karin", makna: "Yang suci, yang murni", asal: "Variasi Scandinavian dari Katherine" },
  { nama: "Katja", makna: "Yang suci, yang murni", asal: "Variasi Scandinavian dari Katherine" },
  { nama: "Kirsten", makna: "Pengikut Kristus", asal: "Variasi Scandinavian dari Christine" },
  { nama: "Lena", makna: "Yang bersinar terang", asal: "Dari Greek bermaksud cahaya" },
  { nama: "Linnea", makna: "Pokok tilia, yang lembut", asal: "Dari Scandinavian bermaksud pokok tilia" },
  { nama: "Maja", makna: "Yang mulia, bulan Mei", asal: "Variasi Scandinavian dari Maya" },
  { nama: "Mette", makna: "Kekuatan dalam pertempuran", asal: "Variasi Scandinavian dari Margaret" },
  { nama: "Nora", makna: "Cahaya, yang bersinar", asal: "Variasi Scandinavian dari Honora" },
  { nama: "Ragna", makna: "Nasihat dewa", asal: "Dari Norse ragna (dewa) dan bermaksud nasihat" },
  { nama: "Sigrid", makna: "Yang cantik dan menang", asal: "Dari Norse sig (menang) dan frid (cantik)" },
  { nama: "Silje", makna: "Yang buta, yang lemah lembut", asal: "Variasi Scandinavian dari Cecilia" },
  { nama: "Siri", makna: "Kecantikan yang menang", asal: "Dari Norse bermaksud cantik dan menang" },
  { nama: "Solveig", makna: "Jalan matahari", asal: "Dari Norse sol (matahari) dan veig (jalan)" },
  { nama: "Thora", makna: "Guruh, yang kuat", asal: "Dari Norse bermaksud guruh" },
  { nama: "Tuva", makna: "Yang suci, yang cantik", asal: "Dari Norse bermaksud cantik" },
  { nama: "Ulla", makna: "Yang berkehendak, yang kuat", asal: "Dari German bermaksud berkehendak" },
  { nama: "Ylva", makna: "Serigala betina, yang bebas", asal: "Dari Norse bermaksud serigala betina" },
];
