// MAMAEXPERT — nama-data-6.js
// Melayu Lelaki B-Z + Arab Perempuan B-Z tambahan

const namaMelayuLelakiTambahan = [
  // B
  { nama: "Badrul", jantina: "lelaki", bahasa: "Melayu", makna: "Bulan purnama yang bercahaya", asal: "Dari kata Arab badr bermaksud bulan purnama" },
  { nama: "Baharudin", jantina: "lelaki", bahasa: "Melayu", makna: "Keindahan agama", asal: "Gabungan bahar dan din" },
  { nama: "Baharuldin", jantina: "lelaki", bahasa: "Melayu", makna: "Keindahan agama Islam", asal: "Gabungan bahar dan din" },
  { nama: "Bahrul", jantina: "lelaki", bahasa: "Melayu", makna: "Laut yang luas", asal: "Dari kata Arab bahr bermaksud laut" },
  { nama: "Baihaqi", jantina: "lelaki", bahasa: "Melayu", makna: "Yang berkaitan dengan kebenaran", asal: "Dinisbahkan kepada Imam Al-Baihaqi" },
  { nama: "Bakr", jantina: "lelaki", bahasa: "Melayu", makna: "Yang muda dan bersemangat", asal: "Dari kata Arab bakr bermaksud muda" },
  { nama: "Baqir", jantina: "lelaki", bahasa: "Melayu", makna: "Yang membelah ilmu pengetahuan", asal: "Dari kata Arab baqa bermaksud membelah" },
  { nama: "Barakat", jantina: "lelaki", bahasa: "Melayu", makna: "Keberkatan yang melimpah", asal: "Dari kata Arab baraka bermaksud berkat" },
  { nama: "Basyir", jantina: "lelaki", bahasa: "Melayu", makna: "Pembawa berita gembira", asal: "Dari kata Arab bashshara bermaksud berita" },
  { nama: "Burhan", jantina: "lelaki", bahasa: "Melayu", makna: "Bukti yang nyata dan jelas", asal: "Dari kata Arab burhan bermaksud bukti" },
  { nama: "Burhanudin", jantina: "lelaki", bahasa: "Melayu", makna: "Bukti agama Islam", asal: "Gabungan burhan dan din" },

  // D
  { nama: "Danial", jantina: "lelaki", bahasa: "Melayu", makna: "Allah adalah hakimku", asal: "Nama nabi dalam tradisi Abrahamic" },
  { nama: "Daniyal", jantina: "lelaki", bahasa: "Melayu", makna: "Allah adalah hakimku", asal: "Variasi dari Danial" },
  { nama: "Darwisy", jantina: "lelaki", bahasa: "Melayu", makna: "Yang sufi dan zuhud", asal: "Dari kata Arab darwish bermaksud sufi" },
  { nama: "Dawud", jantina: "lelaki", bahasa: "Melayu", makna: "Yang dicintai Allah", asal: "Variasi dari Daud, nama Nabi A.S" },
  { nama: "Dhiyaul", jantina: "lelaki", bahasa: "Melayu", makna: "Cahaya yang menerangi", asal: "Dari kata Arab dhiya bermaksud cahaya" },
  { nama: "Dzakwan", jantina: "lelaki", bahasa: "Melayu", makna: "Yang cerdas dan tajam fikiran", asal: "Variasi dari Zakwan bermaksud cerdas" },
  { nama: "Dzikri", jantina: "lelaki", bahasa: "Melayu", makna: "Zikirku kepada Allah", asal: "Variasi dari Zikri bermaksud zikir" },
  { nama: "Dzulhijjah", jantina: "lelaki", bahasa: "Melayu", makna: "Bulan haji yang mulia", asal: "Nama bulan terakhir dalam Islam" },
  { nama: "Dzulqaifar", jantina: "lelaki", bahasa: "Melayu", makna: "Yang memiliki dua sisi pedang", asal: "Dari nama pedang Saidina Ali" },

  // E
  { nama: "Effendy", jantina: "lelaki", bahasa: "Melayu", makna: "Tuan yang terhormat", asal: "Dari bahasa Turki efendi bermaksud tuan" },
  { nama: "Ehsan", jantina: "lelaki", bahasa: "Melayu", makna: "Kebaikan yang sempurna", asal: "Variasi dari Ihsan bermaksud kebaikan" },
  { nama: "Ekhsan", jantina: "lelaki", bahasa: "Melayu", makna: "Berbuat baik dengan sempurna", asal: "Variasi dari Ihsan" },
  { nama: "Emran", jantina: "lelaki", bahasa: "Melayu", makna: "Kemakmuran dan kemuliaan", asal: "Variasi dari Imran" },
  { nama: "Ezhan", jantina: "lelaki", bahasa: "Melayu", makna: "Yang mulia dan berwibawa", asal: "Variasi Melayu bermaksud kemuliaan" },
  { nama: "Ezwan", jantina: "lelaki", bahasa: "Melayu", makna: "Yang mulia dan terhormat", asal: "Variasi Melayu bermaksud kemuliaan" },

  // F
  { nama: "Faheem", jantina: "lelaki", bahasa: "Melayu", makna: "Yang faham dan bijaksana", asal: "Dari kata Arab fahima bermaksud faham" },
  { nama: "Fahmi", jantina: "lelaki", bahasa: "Melayu", makna: "Kefahaman yang mendalam", asal: "Dari kata Arab fahima bermaksud faham" },
  { nama: "Faisal", jantina: "lelaki", bahasa: "Melayu", makna: "Yang memutuskan dengan adil", asal: "Dari kata Arab fasala bermaksud memutus" },
  { nama: "Fakhri", jantina: "lelaki", bahasa: "Melayu", makna: "Kebanggaanku yang mulia", asal: "Dari kata Arab fakhr bermaksud bangga" },
  { nama: "Fakhrul", jantina: "lelaki", bahasa: "Melayu", makna: "Kebanggaan yang terbaik", asal: "Dari kata Arab fakhr bermaksud bangga" },
  { nama: "Faqih", jantina: "lelaki", bahasa: "Melayu", makna: "Yang arif dalam fiqah Islam", asal: "Dari kata Arab faqiha bermaksud faham agama" },
  { nama: "Faraz", jantina: "lelaki", bahasa: "Melayu", makna: "Ketinggian, yang mulia", asal: "Dari bahasa Parsi bermaksud ketinggian" },
  { nama: "Fardaus", jantina: "lelaki", bahasa: "Melayu", makna: "Syurga tertinggi yang indah", asal: "Variasi dari Firdaus bermaksud syurga" },
  { nama: "Fareez", jantina: "lelaki", bahasa: "Melayu", makna: "Yang kuat dan teguh", asal: "Variasi Melayu bermaksud kekuatan" },
  { nama: "Farhan", jantina: "lelaki", bahasa: "Melayu", makna: "Yang gembira dan bahagia", asal: "Dari kata Arab farih bermaksud gembira" },
  { nama: "Faris", jantina: "lelaki", bahasa: "Melayu", makna: "Penunggang kuda, pahlawan", asal: "Dari kata Arab faris bermaksud pahlawan" },
  { nama: "Farish", jantina: "lelaki", bahasa: "Melayu", makna: "Pahlawan yang berani", asal: "Variasi dari Faris bermaksud pahlawan" },
  { nama: "Farouk", jantina: "lelaki", bahasa: "Melayu", makna: "Yang membezakan hak dan batil", asal: "Variasi dari Faruq" },
  { nama: "Farouq", jantina: "lelaki", bahasa: "Melayu", makna: "Yang membezakan yang benar dan salah", asal: "Variasi dari Faruq" },
  { nama: "Fathul", jantina: "lelaki", bahasa: "Melayu", makna: "Kemenangan yang mulia", asal: "Dari kata Arab fath bermaksud kemenangan" },
  { nama: "Fatih", jantina: "lelaki", bahasa: "Melayu", makna: "Yang membuka, yang menang", asal: "Dari kata Arab fataha bermaksud membuka" },
  { nama: "Fattah", jantina: "lelaki", bahasa: "Melayu", makna: "Yang banyak membuka pintu kejayaan", asal: "Salah satu nama Allah Al-Fattah" },
  { nama: "Fauzan", jantina: "lelaki", bahasa: "Melayu", makna: "Kemenangan dan kejayaan", asal: "Dari kata Arab faza bermaksud menang" },
  { nama: "Fawwaz", jantina: "lelaki", bahasa: "Melayu", makna: "Yang sering berjaya", asal: "Dari kata Arab faza bermaksud berjaya" },
  { nama: "Fayyadh", jantina: "lelaki", bahasa: "Melayu", makna: "Yang murah hati dan melimpah", asal: "Dari kata Arab fayadha bermaksud melimpah" },
  { nama: "Fayyaz", jantina: "lelaki", bahasa: "Melayu", makna: "Yang sangat pemurah", asal: "Dari kata Arab fayyad bermaksud pemurah" },
  { nama: "Fazli", jantina: "lelaki", bahasa: "Melayu", makna: "Kelebihanku dari Allah", asal: "Dari kata Arab fadl bermaksud kelebihan" },
  { nama: "Fazrul", jantina: "lelaki", bahasa: "Melayu", makna: "Kelebihan yang mulia", asal: "Dari kata Arab fadl bermaksud kelebihan" },
  { nama: "Firdaus", jantina: "lelaki", bahasa: "Melayu", makna: "Syurga tertinggi yang indah", asal: "Dari kata Arab firdaws bermaksud syurga" },
  { nama: "Fitri", jantina: "lelaki", bahasa: "Melayu", makna: "Yang fitrah dan suci", asal: "Dari kata Arab fitra bermaksud suci" },
  { nama: "Fuad", jantina: "lelaki", bahasa: "Melayu", makna: "Hati yang penuh kasih", asal: "Dari kata Arab fuad bermaksud hati" },

  // G
  { nama: "Ghaffar", jantina: "lelaki", bahasa: "Melayu", makna: "Yang banyak mengampuni", asal: "Salah satu nama Allah Al-Ghaffar" },
  { nama: "Ghafur", jantina: "lelaki", bahasa: "Melayu", makna: "Yang Maha Pengampun", asal: "Salah satu nama Allah Al-Ghafur" },
  { nama: "Ghalib", jantina: "lelaki", bahasa: "Melayu", makna: "Yang menang, yang unggul", asal: "Dari kata Arab ghalaba bermaksud menang" },
  { nama: "Ghani", jantina: "lelaki", bahasa: "Melayu", makna: "Yang kaya dan cukup", asal: "Salah satu nama Allah Al-Ghani" },
  { nama: "Ghazali", jantina: "lelaki", bahasa: "Melayu", makna: "Yang berkaitan dengan Imam Al-Ghazali", asal: "Dinisbahkan kepada Imam Al-Ghazali" },
  { nama: "Ghazwan", jantina: "lelaki", bahasa: "Melayu", makna: "Pejuang di jalan Allah", asal: "Dari kata Arab ghaza bermaksud berjuang" },

  // H
  { nama: "Hafeez", jantina: "lelaki", bahasa: "Melayu", makna: "Yang memelihara dan menjaga", asal: "Variasi dari Hafiz bermaksud penjaga" },
  { nama: "Haidar", jantina: "lelaki", bahasa: "Melayu", makna: "Singa, yang berani", asal: "Gelaran Saidina Ali bin Abi Talib" },
  { nama: "Hairudin", jantina: "lelaki", bahasa: "Melayu", makna: "Kebaikan agama Islam", asal: "Gabungan khayr dan din" },
  { nama: "Hakimi", jantina: "lelaki", bahasa: "Melayu", makna: "Yang bijaksana dalam hukum", asal: "Dari kata Arab hakama bermaksud hukum" },
  { nama: "Hamdan", jantina: "lelaki", bahasa: "Melayu", makna: "Yang banyak memuji Allah", asal: "Dari kata Arab hamida bermaksud memuji" },
  { nama: "Hamdani", jantina: "lelaki", bahasa: "Melayu", makna: "Yang suka memuji Allah", asal: "Dari kata Arab hamd bermaksud pujian" },
  { nama: "Hamdi", jantina: "lelaki", bahasa: "Melayu", makna: "Pujianku kepada Allah", asal: "Dari kata Arab hamd bermaksud pujian" },
  { nama: "Hamizul", jantina: "lelaki", bahasa: "Melayu", makna: "Yang memuji Allah", asal: "Gabungan hami dan zul bermaksud memuji" },
  { nama: "Hamzah", jantina: "lelaki", bahasa: "Melayu", makna: "Singa Allah yang gagah", asal: "Nama bapa saudara Nabi S.A.W" },
  { nama: "Hanafi", jantina: "lelaki", bahasa: "Melayu", makna: "Yang lurus beragama", asal: "Dinisbahkan kepada Imam Abu Hanifah" },
  { nama: "Hanif", jantina: "lelaki", bahasa: "Melayu", makna: "Yang lurus dan ikhlas beragama", asal: "Dari kata Arab hanifa bermaksud lurus" },
  { nama: "Hanifuddin", jantina: "lelaki", bahasa: "Melayu", makna: "Yang lurus dalam agama", asal: "Gabungan hanif dan din" },
  { nama: "Haqimi", jantina: "lelaki", bahasa: "Melayu", makna: "Yang berkaitan dengan kebenaran", asal: "Dari kata Arab haqq bermaksud benar" },
  { nama: "Harith", jantina: "lelaki", bahasa: "Melayu", makna: "Yang rajin bekerja dan berjuang", asal: "Nama sahabat Nabi S.A.W" },
  { nama: "Haris", jantina: "lelaki", bahasa: "Melayu", makna: "Penjaga yang melindungi", asal: "Dari kata Arab harasa bermaksud jaga" },
  { nama: "Harun", jantina: "lelaki", bahasa: "Melayu", makna: "Yang mulia dan tinggi", asal: "Nama Nabi Harun A.S, saudara Musa A.S" },
  { nama: "Hasyim", jantina: "lelaki", bahasa: "Melayu", makna: "Yang menghancurkan dan memberi makan", asal: "Nama moyang Nabi Muhammad S.A.W" },
  { nama: "Hayyan", jantina: "lelaki", bahasa: "Melayu", makna: "Yang penuh kehidupan", asal: "Dari kata Arab hayya bermaksud hidup" },
  { nama: "Hazwan", jantina: "lelaki", bahasa: "Melayu", makna: "Yang berhati-hati dan teliti", asal: "Variasi Melayu bermaksud kehati-hatian" },
  { nama: "Hazwani", jantina: "lelaki", bahasa: "Melayu", makna: "Yang tegas dan berhati-hati", asal: "Dari kata Arab hazm bermaksud tegas" },
  { nama: "Helmi", jantina: "lelaki", bahasa: "Melayu", makna: "Yang lemah lembut dan sabar", asal: "Dari kata Arab hilm bermaksud lembut" },
  { nama: "Hifzan", jantina: "lelaki", bahasa: "Melayu", makna: "Yang memelihara dan menjaga", asal: "Dari kata Arab hafiza bermaksud menjaga" },
  { nama: "Hilman", jantina: "lelaki", bahasa: "Melayu", makna: "Yang lemah lembut", asal: "Dari kata Arab hilm bermaksud lembut" },
  { nama: "Hisham", jantina: "lelaki", bahasa: "Melayu", makna: "Yang pemurah dan mulia", asal: "Nama khalifah Bani Umayyah" },
  { nama: "Hisyam", jantina: "lelaki", bahasa: "Melayu", makna: "Yang pemurah hati", asal: "Variasi dari Hisham" },
  { nama: "Husamudin", jantina: "lelaki", bahasa: "Melayu", makna: "Pedang agama yang tajam", asal: "Gabungan husam dan din" },
  { nama: "Husayn", jantina: "lelaki", bahasa: "Melayu", makna: "Yang cantik dan baik sekali", asal: "Variasi dari Hussain" },

  // I
  { nama: "Ikhwan", jantina: "lelaki", bahasa: "Melayu", makna: "Saudara-saudara yang setia", asal: "Dari kata Arab akh bermaksud saudara" },
  { nama: "Ikmal", jantina: "lelaki", bahasa: "Melayu", makna: "Yang sempurna dan lengkap", asal: "Dari kata Arab kamula bermaksud sempurna" },
  { nama: "Ikhlas", jantina: "lelaki", bahasa: "Melayu", makna: "Yang ikhlas dan tulus hati", asal: "Dari kata Arab akhlasa bermaksud ikhlas" },
  { nama: "Ilman", jantina: "lelaki", bahasa: "Melayu", makna: "Ilmuku, yang berpengetahuan", asal: "Dari kata Arab ilm bermaksud ilmu" },
  { nama: "Ilyaas", jantina: "lelaki", bahasa: "Melayu", makna: "Allah adalah Tuhanku", asal: "Variasi dari Ilyas, nama Nabi A.S" },
  { nama: "Imran", jantina: "lelaki", bahasa: "Melayu", makna: "Kemakmuran yang mulia", asal: "Disebut dalam Al-Quran surah Ali Imran" },
  { nama: "Iqmal", jantina: "lelaki", bahasa: "Melayu", makna: "Yang sempurna dan terbaik", asal: "Variasi dari Ikmal bermaksud sempurna" },
  { nama: "Iqram", jantina: "lelaki", bahasa: "Melayu", makna: "Penghormatan, yang dihormati", asal: "Dari kata Arab ikram bermaksud hormat" },
  { nama: "Irfan", jantina: "lelaki", bahasa: "Melayu", makna: "Pengetahuan dan kebijaksanaan", asal: "Dari kata Arab arafa bermaksud tahu" },
  { nama: "Irsyad", jantina: "lelaki", bahasa: "Melayu", makna: "Petunjuk dan bimbingan", asal: "Dari kata Arab arshada bermaksud membimbing" },
  { nama: "Iskandar", jantina: "lelaki", bahasa: "Melayu", makna: "Penakluk yang agung", asal: "Nama Alexander the Great dalam Islam" },
  { nama: "Islam", jantina: "lelaki", bahasa: "Melayu", makna: "Penyerahan diri kepada Allah", asal: "Nama agama Allah yang suci" },
  { nama: "Ismail", jantina: "lelaki", bahasa: "Melayu", makna: "Allah mendengar doaku", asal: "Nama Nabi Ismail A.S" },
  { nama: "Izzudin", jantina: "lelaki", bahasa: "Melayu", makna: "Kemuliaan agama Islam", asal: "Gabungan izz dan din" },
  { nama: "Izzwan", jantina: "lelaki", bahasa: "Melayu", makna: "Yang mulia dan terhormat", asal: "Variasi Melayu bermaksud kemuliaan" },

  // J
  { nama: "Jabir", jantina: "lelaki", bahasa: "Melayu", makna: "Yang mengubati dan memulih", asal: "Nama sahabat Nabi yang terkenal" },
  { nama: "Jafar", jantina: "lelaki", bahasa: "Melayu", makna: "Sungai kecil, yang mengalir", asal: "Nama sepupu Nabi Muhammad S.A.W" },
  { nama: "Jafri", jantina: "lelaki", bahasa: "Melayu", makna: "Dari keturunan Jafar yang mulia", asal: "Dinisbahkan kepada Saidina Jafar" },
  { nama: "Jalil", jantina: "lelaki", bahasa: "Melayu", makna: "Yang agung dan mulia", asal: "Salah satu nama Allah Al-Jalil" },
  { nama: "Jamalul", jantina: "lelaki", bahasa: "Melayu", makna: "Kecantikan yang mulia", asal: "Dari kata Arab jamal bermaksud cantik" },
  { nama: "Jamil", jantina: "lelaki", bahasa: "Melayu", makna: "Yang cantik dan tampan", asal: "Dari kata Arab jamala bermaksud cantik" },
  { nama: "Jasni", jantina: "lelaki", bahasa: "Melayu", makna: "Yang elok dan berseri", asal: "Variasi Melayu bermaksud keelokkan" },
  { nama: "Jauhari", jantina: "lelaki", bahasa: "Melayu", makna: "Yang seperti permata berharga", asal: "Dari kata Arab jawhar bermaksud permata" },
  { nama: "Jawwad", jantina: "lelaki", bahasa: "Melayu", makna: "Yang sangat pemurah", asal: "Dari kata Arab jawad bermaksud pemurah" },
  { nama: "Jazlan", jantina: "lelaki", bahasa: "Melayu", makna: "Yang gembira dan ceria", asal: "Dari kata Arab jazala bermaksud gembira" },
  { nama: "Jazmi", jantina: "lelaki", bahasa: "Melayu", makna: "Yang pasti dan tegas", asal: "Dari kata Arab jazama bermaksud pasti" },

  // K
  { nama: "Kamilin", jantina: "lelaki", bahasa: "Melayu", makna: "Yang sempurna dan lengkap", asal: "Dari kata Arab kamila bermaksud sempurna" },
  { nama: "Karimuddin", jantina: "lelaki", bahasa: "Melayu", makna: "Kemuliaan agama", asal: "Gabungan karim dan din" },
  { nama: "Kasim", jantina: "lelaki", bahasa: "Melayu", makna: "Yang membahagi dengan adil", asal: "Variasi dari Qasim" },
  { nama: "Khairil", jantina: "lelaki", bahasa: "Melayu", makna: "Kebaikan yang istimewa", asal: "Variasi dari Khairul bermaksud baik" },
  { nama: "Khairudin", jantina: "lelaki", bahasa: "Melayu", makna: "Kebaikan agama Islam", asal: "Gabungan khayr dan din" },
  { nama: "Khalilullah", jantina: "lelaki", bahasa: "Melayu", makna: "Kekasih Allah", asal: "Gelaran Nabi Ibrahim A.S" },
  { nama: "Khayrulazam", jantina: "lelaki", bahasa: "Melayu", makna: "Kebaikan yang paling agung", asal: "Gabungan khayr dan azam bermaksud agung" },

  // L
  { nama: "Laith", jantina: "lelaki", bahasa: "Melayu", makna: "Singa, yang gagah berani", asal: "Dari kata Arab laith bermaksud singa" },
  { nama: "Latif", jantina: "lelaki", bahasa: "Melayu", makna: "Yang lembut dan halus", asal: "Salah satu nama Allah Al-Latif" },
  { nama: "Lokman", jantina: "lelaki", bahasa: "Melayu", makna: "Yang bijaksana", asal: "Variasi dari Luqman" },
  { nama: "Luqman", jantina: "lelaki", bahasa: "Melayu", makna: "Yang bijaksana", asal: "Disebut dalam Al-Quran" },
  { nama: "Lutfil", jantina: "lelaki", bahasa: "Melayu", makna: "Kelembutan yang mulia", asal: "Dari kata Arab lutf bermaksud lembut" },
  { nama: "Lutfillah", jantina: "lelaki", bahasa: "Melayu", makna: "Kelembutan Allah", asal: "Gabungan lutf dan Allah" },
  { nama: "Lutfin", jantina: "lelaki", bahasa: "Melayu", makna: "Yang lembut dan baik hati", asal: "Dari kata Arab lutf bermaksud lembut" },

  // M
  { nama: "Maaruf", jantina: "lelaki", bahasa: "Melayu", makna: "Yang terkenal dan dikenal", asal: "Dari kata Arab arafa bermaksud dikenal" },
  { nama: "Mahathir", jantina: "lelaki", bahasa: "Melayu", makna: "Yang paling pandai", asal: "Dari kata Arab athara bermaksud pandai" },
  { nama: "Mahfuz", jantina: "lelaki", bahasa: "Melayu", makna: "Yang terpelihara dan terjaga", asal: "Dari kata Arab hafaza bermaksud jaga" },
  { nama: "Mahir", jantina: "lelaki", bahasa: "Melayu", makna: "Yang mahir dan cekap", asal: "Dari kata Arab mahara bermaksud mahir" },
  { nama: "Mahirul", jantina: "lelaki", bahasa: "Melayu", makna: "Yang paling mahir dan cekap", asal: "Dari kata Arab mahara bermaksud mahir" },
  { nama: "Mahmoud", jantina: "lelaki", bahasa: "Melayu", makna: "Yang terpuji", asal: "Variasi dari Mahmud bermaksud terpuji" },
  { nama: "Mahmud", jantina: "lelaki", bahasa: "Melayu", makna: "Yang terpuji dan disyukuri", asal: "Dari kata Arab hamida bermaksud memuji" },
  { nama: "Maizan", jantina: "lelaki", bahasa: "Melayu", makna: "Yang seimbang dan adil", asal: "Dari kata Arab mizan bermaksud timbangan" },
  { nama: "Maizul", jantina: "lelaki", bahasa: "Melayu", makna: "Yang istimewa dan unggul", asal: "Dari kata Arab mayaza bermaksud unggul" },
  { nama: "Makmur", jantina: "lelaki", bahasa: "Melayu", makna: "Yang makmur dan sejahtera", asal: "Dari kata Arab amara bermaksud makmur" },
  { nama: "Marzuki", jantina: "lelaki", bahasa: "Melayu", makna: "Yang diberi rezeki berlimpah", asal: "Dari kata Arab rizq bermaksud rezeki" },
  { nama: "Masri", jantina: "lelaki", bahasa: "Melayu", makna: "Yang dari Mesir, yang mulia", asal: "Dinisbahkan kepada negara Mesir" },
  { nama: "Masrur", jantina: "lelaki", bahasa: "Melayu", makna: "Yang gembira dan berbahagia", asal: "Dari kata Arab sarra bermaksud gembira" },
  { nama: "Mawardi", jantina: "lelaki", bahasa: "Melayu", makna: "Air mawar, yang harum", asal: "Dari kata Arab maward bermaksud air mawar" },
  { nama: "Mazlan", jantina: "lelaki", bahasa: "Melayu", makna: "Yang bersemangat dan gigih", asal: "Variasi Melayu bermaksud semangat" },
  { nama: "Mazni", jantina: "lelaki", bahasa: "Melayu", makna: "Yang cantik dan elok", asal: "Variasi Melayu bermaksud kecantikan" },
  { nama: "Mazwan", jantina: "lelaki", bahasa: "Melayu", makna: "Yang bersemangat dan kuat", asal: "Variasi Melayu bermaksud kekuatan" },
  { nama: "Miqdad", jantina: "lelaki", bahasa: "Melayu", makna: "Yang berani dan gigih", asal: "Nama sahabat Nabi yang terkenal" },
  { nama: "Miqdam", jantina: "lelaki", bahasa: "Melayu", makna: "Yang maju ke hadapan", asal: "Nama sahabat Nabi yang terkenal" },
  { nama: "Mirzam", jantina: "lelaki", bahasa: "Melayu", makna: "Bintang yang bersinar terang", asal: "Nama bintang dalam astronomi Arab" },
  { nama: "Mohamad", jantina: "lelaki", bahasa: "Melayu", makna: "Yang terpuji, nama Nabi S.A.W", asal: "Variasi dari Muhammad" },
  { nama: "Mohammad", jantina: "lelaki", bahasa: "Melayu", makna: "Yang terpuji", asal: "Variasi dari Muhammad" },
  { nama: "Mohd", jantina: "lelaki", bahasa: "Melayu", makna: "Yang terpuji", asal: "Singkatan dari Muhammad" },
  { nama: "Mokhtar", jantina: "lelaki", bahasa: "Melayu", makna: "Yang terpilih dan istimewa", asal: "Dari kata Arab ikhtara bermaksud memilih" },
  { nama: "Muadz", jantina: "lelaki", bahasa: "Melayu", makna: "Yang dilindungi Allah", asal: "Nama sahabat Nabi yang alim" },
  { nama: "Muammar", jantina: "lelaki", bahasa: "Melayu", makna: "Yang berumur panjang", asal: "Dari kata Arab ammara bermaksud makmur" },
  { nama: "Mubarak", jantina: "lelaki", bahasa: "Melayu", makna: "Yang diberkati Allah", asal: "Dari kata Arab baraka bermaksud berkat" },
  { nama: "Mufid", jantina: "lelaki", bahasa: "Melayu", makna: "Yang memberi manfaat", asal: "Dari kata Arab afada bermaksud manfaat" },
  { nama: "Muhajir", jantina: "lelaki", bahasa: "Melayu", makna: "Yang berhijrah di jalan Allah", asal: "Dari kata Arab hajara bermaksud hijrah" },
  { nama: "Muhannad", jantina: "lelaki", bahasa: "Melayu", makna: "Pedang India yang tajam", asal: "Dari kata Arab bermaksud pedang tajam" },
  { nama: "Muhib", jantina: "lelaki", bahasa: "Melayu", makna: "Yang mencintai Allah", asal: "Dari kata Arab habba bermaksud cinta" },
  { nama: "Muhibbuddin", jantina: "lelaki", bahasa: "Melayu", makna: "Pencinta agama Islam", asal: "Gabungan muhibb dan din" },
  { nama: "Muhsin", jantina: "lelaki", bahasa: "Melayu", makna: "Yang berbuat kebaikan", asal: "Dari kata Arab ahsana bermaksud berbuat baik" },
  { nama: "Muiz", jantina: "lelaki", bahasa: "Melayu", makna: "Yang memberi kemuliaan", asal: "Dari kata Arab azza bermaksud mulia" },
  { nama: "Mukhtaruddin", jantina: "lelaki", bahasa: "Melayu", makna: "Pilihan agama yang terbaik", asal: "Gabungan mukhtar dan din" },
  { nama: "Mukminin", jantina: "lelaki", bahasa: "Melayu", makna: "Orang-orang yang beriman", asal: "Dari kata Arab amana bermaksud beriman" },
  { nama: "Mulhim", jantina: "lelaki", bahasa: "Melayu", makna: "Yang mengilhamkan", asal: "Dari kata Arab alhama bermaksud ilham" },
  { nama: "Munawwar", jantina: "lelaki", bahasa: "Melayu", makna: "Yang bercahaya terang", asal: "Dari kata Arab nara bermaksud cahaya" },
  { nama: "Munif", jantina: "lelaki", bahasa: "Melayu", makna: "Yang tinggi dan mulia", asal: "Dari kata Arab manafa bermaksud tinggi" },
  { nama: "Munirul", jantina: "lelaki", bahasa: "Melayu", makna: "Yang menerangi dengan cahaya", asal: "Dari kata Arab anara bermaksud cahaya" },
  { nama: "Muntaha", jantina: "lelaki", bahasa: "Melayu", makna: "Yang mencapai puncak", asal: "Dari kata Arab intaha bermaksud puncak" },
  { nama: "Muqarrabin", jantina: "lelaki", bahasa: "Melayu", makna: "Yang dekat kepada Allah", asal: "Dari kata Arab qarraba bermaksud dekat" },
  { nama: "Murshid", jantina: "lelaki", bahasa: "Melayu", makna: "Pembimbing yang benar", asal: "Dari kata Arab rashada bermaksud membimbing" },
  { nama: "Murtadha", jantina: "lelaki", bahasa: "Melayu", makna: "Yang diredhai Allah", asal: "Dari kata Arab radha bermaksud redha" },
  { nama: "Musaddiq", jantina: "lelaki", bahasa: "Melayu", makna: "Yang membenarkan", asal: "Dari kata Arab sadaqa bermaksud benar" },
  { nama: "Mustaqim", jantina: "lelaki", bahasa: "Melayu", makna: "Yang lurus dan teguh", asal: "Dari kata Arab istaqama bermaksud lurus" },
  { nama: "Mutiullah", jantina: "lelaki", bahasa: "Melayu", makna: "Yang taat kepada Allah", asal: "Gabungan muti dan Allah" },
  { nama: "Muzaffar", jantina: "lelaki", bahasa: "Melayu", makna: "Yang menang dan berjaya", asal: "Dari kata Arab zafara bermaksud menang" },

  // N
  { nama: "Nabil", jantina: "lelaki", bahasa: "Melayu", makna: "Yang mulia dan cerdas", asal: "Dari kata Arab nabala bermaksud mulia" },
  { nama: "Nadhir", jantina: "lelaki", bahasa: "Melayu", makna: "Pemberi amaran yang jujur", asal: "Dari kata Arab andhara bermaksud memberi amaran" },
  { nama: "Nafis", jantina: "lelaki", bahasa: "Melayu", makna: "Yang berharga dan bernilai", asal: "Dari kata Arab nafasa bermaksud berharga" },
  { nama: "Naim", jantina: "lelaki", bahasa: "Melayu", makna: "Yang hidup senang dan mewah", asal: "Dari kata Arab naama bermaksud nikmat" },
  { nama: "Najib", jantina: "lelaki", bahasa: "Melayu", makna: "Yang mulia dan cerdas", asal: "Dari kata Arab najaba bermaksud mulia" },
  { nama: "Najibuddin", jantina: "lelaki", bahasa: "Melayu", makna: "Kemuliaan agama Islam", asal: "Gabungan najib dan din" },
  { nama: "Nasarudin", jantina: "lelaki", bahasa: "Melayu", makna: "Kemenangan agama Islam", asal: "Gabungan nasar dan din" },
  { nama: "Nashrul", jantina: "lelaki", bahasa: "Melayu", makna: "Kemenangan yang mulia", asal: "Dari kata Arab nasr bermaksud kemenangan" },
  { nama: "Nasim", jantina: "lelaki", bahasa: "Melayu", makna: "Angin sepoi yang segar", asal: "Dari kata Arab nasama bermaksud angin" },
  { nama: "Naufal", jantina: "lelaki", bahasa: "Melayu", makna: "Yang pemurah dan banyak memberi", asal: "Dari kata Arab nafala bermaksud memberi" },
  { nama: "Nawawi", jantina: "lelaki", bahasa: "Melayu", makna: "Yang berkaitan dengan Imam Nawawi", asal: "Dinisbahkan kepada Imam Al-Nawawi" },
  { nama: "Nazhan", jantina: "lelaki", bahasa: "Melayu", makna: "Yang bersih dan suci", asal: "Dari kata Arab nazaha bermaksud bersih" },
  { nama: "Nazif", jantina: "lelaki", bahasa: "Melayu", makna: "Yang bersih dan suci", asal: "Dari kata Arab nazufa bermaksud bersih" },
  { nama: "Nazim", jantina: "lelaki", bahasa: "Melayu", makna: "Yang teratur dan tersusun rapi", asal: "Dari kata Arab nazama bermaksud susun" },
  { nama: "Nazmi", jantina: "lelaki", bahasa: "Melayu", makna: "Yang tersusun dan teratur", asal: "Dari kata Arab nazm bermaksud susunan" },
  { nama: "Nazrin", jantina: "lelaki", bahasa: "Melayu", makna: "Bunga ros liar yang cantik", asal: "Variasi dari Persian bermaksud ros" },
  { nama: "Noorazlan", jantina: "lelaki", bahasa: "Melayu", makna: "Cahaya singa yang gagah", asal: "Gabungan noor dan azlan" },
  { nama: "Noorhazwan", jantina: "lelaki", bahasa: "Melayu", makna: "Cahaya yang tegas dan teliti", asal: "Gabungan noor dan hazwan" },
  { nama: "Norazlan", jantina: "lelaki", bahasa: "Melayu", makna: "Cahaya singa yang mulia", asal: "Gabungan nur dan azlan" },
  { nama: "Norzaidi", jantina: "lelaki", bahasa: "Melayu", makna: "Cahaya yang bertambah", asal: "Gabungan nur dan zaidi" },
  { nama: "Norzaihan", jantina: "lelaki", bahasa: "Melayu", makna: "Cahaya yang cantik berseri", asal: "Gabungan nur dan zaihan" },
  { nama: "Norzaki", jantina: "lelaki", bahasa: "Melayu", makna: "Cahaya yang suci", asal: "Gabungan nur dan zaki" },
  { nama: "Norzamir", jantina: "lelaki", bahasa: "Melayu", makna: "Cahaya pemimpin", asal: "Gabungan nur dan zamir" },
  { nama: "Norzamri", jantina: "lelaki", bahasa: "Melayu", makna: "Cahaya rakan yang baik", asal: "Gabungan nur dan zamri" },
  { nama: "Norzarul", jantina: "lelaki", bahasa: "Melayu", makna: "Cahaya yang mulia", asal: "Gabungan nur dan zarul" },

  // O
  { nama: "Omar", jantina: "lelaki", bahasa: "Melayu", makna: "Umur panjang dan makmur", asal: "Variasi dari Umar bermaksud makmur" },
  { nama: "Othman", jantina: "lelaki", bahasa: "Melayu", makna: "Yang lembut dan penyayang", asal: "Variasi dari Uthman" },

  // P
  { nama: "Putera", jantina: "lelaki", bahasa: "Melayu", makna: "Anak lelaki yang mulia", asal: "Variasi dari Putra bermaksud anak raja" },

  // Q
  { nama: "Qaiser", jantina: "lelaki", bahasa: "Melayu", makna: "Raja, yang berkuasa", asal: "Dari kata Arab qaysar bermaksud raja" },
  { nama: "Qarib", jantina: "lelaki", bahasa: "Melayu", makna: "Yang dekat kepada Allah", asal: "Dari kata Arab qariba bermaksud dekat" },
  { nama: "Qodri", jantina: "lelaki", bahasa: "Melayu", makna: "Yang berkuasa, yang berkemampuan", asal: "Dari kata Arab qadara bermaksud berkuasa" },
  { nama: "Qushairi", jantina: "lelaki", bahasa: "Melayu", makna: "Yang berkaitan dengan ilmu tasawwuf", asal: "Dinisbahkan kepada Imam Al-Qushairi" },

  // R
  { nama: "Rabbani", jantina: "lelaki", bahasa: "Melayu", makna: "Yang berkaitan dengan Allah", asal: "Dari kata Arab rabb bermaksud Tuhan" },
  { nama: "Radhi", jantina: "lelaki", bahasa: "Melayu", makna: "Yang redha dan berpuas hati", asal: "Dari kata Arab radha bermaksud redha" },
  { nama: "Radhwan", jantina: "lelaki", bahasa: "Melayu", makna: "Keredhaan dan kesyukuran", asal: "Variasi dari Ridhwan" },
  { nama: "Rahim", jantina: "lelaki", bahasa: "Melayu", makna: "Yang penyayang dan berbelas kasih", asal: "Salah satu nama Allah Al-Rahim" },
  { nama: "Rahimin", jantina: "lelaki", bahasa: "Melayu", makna: "Yang penuh kasih sayang", asal: "Dari kata Arab rahima bermaksud kasih" },
  { nama: "Ramadan", jantina: "lelaki", bahasa: "Melayu", makna: "Bulan puasa yang mulia", asal: "Nama bulan suci dalam Islam" },
  { nama: "Ramadhan", jantina: "lelaki", bahasa: "Melayu", makna: "Bulan Ramadhan yang diberkati", asal: "Variasi dari Ramadan" },
  { nama: "Ramli", jantina: "lelaki", bahasa: "Melayu", makna: "Yang lembut seperti pasir", asal: "Dari kata Arab raml bermaksud pasir" },
  { nama: "Rasydan", jantina: "lelaki", bahasa: "Melayu", makna: "Yang mendapat petunjuk benar", asal: "Dari kata Arab rashada bermaksud petunjuk" },
  { nama: "Rauf", jantina: "lelaki", bahasa: "Melayu", makna: "Yang penyayang dan berbelas kasih", asal: "Salah satu nama Allah Al-Rauf" },
  { nama: "Razali", jantina: "lelaki", bahasa: "Melayu", makna: "Rezekiku yang mulia", asal: "Dari kata Arab rizq bermaksud rezeki" },
  { nama: "Redzuan", jantina: "lelaki", bahasa: "Melayu", makna: "Keredhaan Allah", asal: "Variasi dari Ridhwan bermaksud redha" },
  { nama: "Ridhaudin", jantina: "lelaki", bahasa: "Melayu", makna: "Keredhaan agama Islam", asal: "Gabungan ridha dan din" },
  { nama: "Ridhwan", jantina: "lelaki", bahasa: "Melayu", makna: "Keredhaan dan nama penjaga syurga", asal: "Disebutkan dalam hadis" },
  { nama: "Riyaz", jantina: "lelaki", bahasa: "Melayu", makna: "Taman-taman yang indah", asal: "Dari kata Arab rawdha bermaksud taman" },
  { nama: "Riyadh", jantina: "lelaki", bahasa: "Melayu", makna: "Taman-taman bunga yang indah", asal: "Variasi dari Riyaz bermaksud taman" },
  { nama: "Rizqi", jantina: "lelaki", bahasa: "Melayu", makna: "Rezekiku dari Allah", asal: "Dari kata Arab rizq bermaksud rezeki" },
  { nama: "Rohaizad", jantina: "lelaki", bahasa: "Melayu", makna: "Rohani yang bertambah baik", asal: "Gabungan roh dan izad bermaksud rohani" },
  { nama: "Rohimi", jantina: "lelaki", bahasa: "Melayu", makna: "Yang penuh belas kasihan", asal: "Dari kata Arab rahima bermaksud kasih" },
  { nama: "Rohizat", jantina: "lelaki", bahasa: "Melayu", makna: "Rohani yang bersih", asal: "Gabungan roh dan izat bermaksud rohani" },
  { nama: "Ruzaini", jantina: "lelaki", bahasa: "Melayu", makna: "Yang bersemangat dan gigih", asal: "Variasi Melayu bermaksud semangat" },
  { nama: "Ruzairi", jantina: "lelaki", bahasa: "Melayu", makna: "Yang bersemangat dan kuat", asal: "Variasi Melayu bermaksud semangat" },

  // S
  { nama: "Saifudin", jantina: "lelaki", bahasa: "Melayu", makna: "Pedang agama Islam", asal: "Gabungan saif dan din" },
  { nama: "Saifuddin", jantina: "lelaki", bahasa: "Melayu", makna: "Pedang agama yang tajam", asal: "Gabungan saif dan din" },
  { nama: "Saifullah", jantina: "lelaki", bahasa: "Melayu", makna: "Pedang Allah", asal: "Gelaran Khalid bin Walid" },
  { nama: "Salahudin", jantina: "lelaki", bahasa: "Melayu", makna: "Kebaikan agama Islam", asal: "Nama panglima Islam yang terkenal" },
  { nama: "Salmaan", jantina: "lelaki", bahasa: "Melayu", makna: "Yang selamat dan sejahtera", asal: "Variasi dari Salman" },
  { nama: "Samsul", jantina: "lelaki", bahasa: "Melayu", makna: "Matahari yang bersinar", asal: "Dari kata Arab shams bermaksud matahari" },
  { nama: "Samsuri", jantina: "lelaki", bahasa: "Melayu", makna: "Matahari yang membantu", asal: "Gabungan syams dan uri" },
  { nama: "Shahril", jantina: "lelaki", bahasa: "Melayu", makna: "Bulan yang bersinar indah", asal: "Dari kata Arab syahr bermaksud bulan" },
  { nama: "Shahrir", jantina: "lelaki", bahasa: "Melayu", makna: "Bulan yang mulia", asal: "Dari kata Arab syahr bermaksud bulan" },
  { nama: "Shahrizal", jantina: "lelaki", bahasa: "Melayu", makna: "Bulan yang turun bertemu", asal: "Gabungan syahr dan izal" },
  { nama: "Shahrom", jantina: "lelaki", bahasa: "Melayu", makna: "Bulan yang tinggi mulia", asal: "Dari kata Arab syahr bermaksud bulan" },
  { nama: "Shahrul", jantina: "lelaki", bahasa: "Melayu", makna: "Bulan yang terkenal", asal: "Dari kata Arab syahr bermaksud bulan" },
  { nama: "Shahrulanuar", jantina: "lelaki", bahasa: "Melayu", makna: "Bulan cahaya yang terang", asal: "Gabungan shahrul dan anwar" },
  { nama: "Sharifuddin", jantina: "lelaki", bahasa: "Melayu", makna: "Kemuliaan agama Islam", asal: "Gabungan syarif dan din" },
  { nama: "Shukri", jantina: "lelaki", bahasa: "Melayu", makna: "Kesyukuranku kepada Allah", asal: "Variasi dari Syukri bermaksud syukur" },
  { nama: "Sobri", jantina: "lelaki", bahasa: "Melayu", makna: "Yang sabar dan tabah", asal: "Variasi dari Sabri bermaksud sabar" },
  { nama: "Sofian", jantina: "lelaki", bahasa: "Melayu", makna: "Yang cepat bergerak dan tangkas", asal: "Variasi dari Sufian" },
  { nama: "Solihin", jantina: "lelaki", bahasa: "Melayu", makna: "Orang-orang yang soleh", asal: "Dari kata Arab salaha bermaksud soleh" },
  { nama: "Suhaimi", jantina: "lelaki", bahasa: "Melayu", makna: "Yang mudah dan bintang Canopus", asal: "Dari kata Arab suhail bermaksud mudah" },
  { nama: "Suhimi", jantina: "lelaki", bahasa: "Melayu", makna: "Yang mudah dan senang", asal: "Variasi dari Suhaimi" },
  { nama: "Syafaat", jantina: "lelaki", bahasa: "Melayu", makna: "Syafaat dan bantuan Allah", asal: "Dari kata Arab syafaata bermaksud syafaat" },
  { nama: "Syafie", jantina: "lelaki", bahasa: "Melayu", makna: "Yang memberi syafaat", asal: "Dinisbahkan kepada Imam Al-Syafii" },
  { nama: "Syahir", jantina: "lelaki", bahasa: "Melayu", makna: "Yang terkenal dan masyhur", asal: "Dari kata Arab syahara bermaksud masyhur" },
  { nama: "Syahril", jantina: "lelaki", bahasa: "Melayu", makna: "Bulan yang indah bersinar", asal: "Dari kata Arab syahr bermaksud bulan" },
  { nama: "Syahrin", jantina: "lelaki", bahasa: "Melayu", makna: "Dua bulan yang bersinar", asal: "Dari kata Arab syahrayn bermaksud dua bulan" },
  { nama: "Syairazi", jantina: "lelaki", bahasa: "Melayu", makna: "Yang dari Shiraz, yang mulia", asal: "Dinisbahkan kepada kota Shiraz" },
  { nama: "Syakir", jantina: "lelaki", bahasa: "Melayu", makna: "Yang bersyukur kepada Allah", asal: "Dari kata Arab syakara bermaksud syukur" },
  { nama: "Syamsul", jantina: "lelaki", bahasa: "Melayu", makna: "Matahari yang bersinar", asal: "Dari kata Arab syams bermaksud matahari" },
  { nama: "Syamsulbahri", jantina: "lelaki", bahasa: "Melayu", makna: "Matahari laut yang cerah", asal: "Gabungan syams dan bahr" },
  { nama: "Syamsuri", jantina: "lelaki", bahasa: "Melayu", makna: "Matahari yang membantu", asal: "Gabungan syams dan uri" },
  { nama: "Syazwan", jantina: "lelaki", bahasa: "Melayu", makna: "Yang harum dan wangi", asal: "Variasi Melayu bermaksud keharuman" },

  // T
  { nama: "Tarmizi", jantina: "lelaki", bahasa: "Melayu", makna: "Yang berkaitan dengan ilmu hadis", asal: "Dinisbahkan kepada Imam At-Tirmizi" },
  { nama: "Taufik", jantina: "lelaki", bahasa: "Melayu", makna: "Pertolongan dan kejayaan Allah", asal: "Variasi dari Taufiq" },
  { nama: "Tawfik", jantina: "lelaki", bahasa: "Melayu", makna: "Pertolongan Allah untuk berjaya", asal: "Variasi dari Taufiq" },
  { nama: "Tazkirah", jantina: "lelaki", bahasa: "Melayu", makna: "Peringatan dan ingatan", asal: "Dari kata Arab tazakkara bermaksud ingat" },

  // U
  { nama: "Ubaidah", jantina: "lelaki", bahasa: "Melayu", makna: "Hamba kecil yang taat beribadah", asal: "Nama sahabat Nabi yang terkenal" },
  { nama: "Usamah", jantina: "lelaki", bahasa: "Melayu", makna: "Singa yang gagah berani", asal: "Nama anak angkat Nabi S.A.W" },
  { nama: "Uthman", jantina: "lelaki", bahasa: "Melayu", makna: "Yang lembut dan penyayang", asal: "Nama Khalifah Islam ketiga" },
  { nama: "Uzair", jantina: "lelaki", bahasa: "Melayu", makna: "Pertolongan Allah", asal: "Nama nabi dalam Al-Quran" },

  // W
  { nama: "Wafi", jantina: "lelaki", bahasa: "Melayu", makna: "Yang menepati janji", asal: "Dari kata Arab wafa bermaksud janji" },
  { nama: "Wahab", jantina: "lelaki", bahasa: "Melayu", makna: "Yang banyak memberi", asal: "Salah satu nama Allah Al-Wahhab" },
  { nama: "Wahid", jantina: "lelaki", bahasa: "Melayu", makna: "Yang tunggal dan unik", asal: "Salah satu nama Allah Al-Wahid" },
  { nama: "Wajdi", jantina: "lelaki", bahasa: "Melayu", makna: "Yang penuh perasaan kasih", asal: "Dari kata Arab wajada bermaksud rasa" },
  { nama: "Waliyullah", jantina: "lelaki", bahasa: "Melayu", makna: "Wali Allah yang dikasihi", asal: "Gabungan wali dan Allah" },
  { nama: "Wan Mohd", jantina: "lelaki", bahasa: "Melayu", makna: "Putera Muhammad yang mulia", asal: "Wan adalah gelaran bangsawan Melayu" },
  { nama: "Wardani", jantina: "lelaki", bahasa: "Melayu", makna: "Yang seperti bunga ros", asal: "Dari kata Arab ward bermaksud ros" },
  { nama: "Wazir", jantina: "lelaki", bahasa: "Melayu", makna: "Menteri, pembantu yang mulia", asal: "Dari kata Arab wazara bermaksud menanggung" },

  // Y
  { nama: "Yahaya", jantina: "lelaki", bahasa: "Melayu", makna: "Yang hidup dan menghidupkan", asal: "Variasi dari Yahya, nama Nabi A.S" },
  { nama: "Yazid", jantina: "lelaki", bahasa: "Melayu", makna: "Yang bertambah baik dan maju", asal: "Dari kata Arab zada bermaksud bertambah" },
  { nama: "Yusri", jantina: "lelaki", bahasa: "Melayu", makna: "Yang mudah dan bertuah", asal: "Dari kata Arab yasara bermaksud mudah" },
  { nama: "Yusuf", jantina: "lelaki", bahasa: "Melayu", makna: "Allah menambah dan yang cantik", asal: "Nama Nabi Yusuf A.S" },

  // Z
  { nama: "Zahid", jantina: "lelaki", bahasa: "Melayu", makna: "Yang zuhud dan tidak tamak dunia", asal: "Dari kata Arab zahada bermaksud zuhud" },
  { nama: "Zahir", jantina: "lelaki", bahasa: "Melayu", makna: "Yang jelas dan bersinar", asal: "Dari kata Arab zahara bermaksud jelas" },
  { nama: "Zaidin", jantina: "lelaki", bahasa: "Melayu", makna: "Pertambahan agama", asal: "Gabungan zayd dan din" },
  { nama: "Zainudin", jantina: "lelaki", bahasa: "Melayu", makna: "Hiasan agama Islam", asal: "Gabungan zayn dan din" },
  { nama: "Zainuddin", jantina: "lelaki", bahasa: "Melayu", makna: "Kecantikan agama Islam", asal: "Gabungan zayn dan din" },
  { nama: "Zaki", jantina: "lelaki", bahasa: "Melayu", makna: "Yang suci dan cerdas", asal: "Dari kata Arab zaka bermaksud suci" },
  { nama: "Zakiruddin", jantina: "lelaki", bahasa: "Melayu", makna: "Yang mengingati agama Allah", asal: "Gabungan zakir dan din" },
  { nama: "Zamri", jantina: "lelaki", bahasa: "Melayu", makna: "Rakan seperjuangan yang setia", asal: "Dari kata Arab zamala bermaksud rakan" },
  { nama: "Zarul", jantina: "lelaki", bahasa: "Melayu", makna: "Yang mulia dan bersinar", asal: "Variasi Melayu bermaksud kemuliaan" },
  { nama: "Zarulnizam", jantina: "lelaki", bahasa: "Melayu", makna: "Yang mulia dan tersusun", asal: "Gabungan zarul dan nizam" },
  { nama: "Zharif", jantina: "lelaki", bahasa: "Melayu", makna: "Yang bijak dan peramah", asal: "Dari kata Arab zarafa bermaksud bijak" },
  { nama: "Zikrullah", jantina: "lelaki", bahasa: "Melayu", makna: "Zikir kepada Allah", asal: "Gabungan zikr dan Allah" },
  { nama: "Ziyad", jantina: "lelaki", bahasa: "Melayu", makna: "Pertambahan dan kemajuan", asal: "Dari kata Arab zada bermaksud tambah" },
  { nama: "Zubir", jantina: "lelaki", bahasa: "Melayu", makna: "Yang kuat dan gagah", asal: "Variasi dari Zubair" },
  { nama: "Zuhair", jantina: "lelaki", bahasa: "Melayu", makna: "Yang bersinar dan harum", asal: "Dari kata Arab zahara bermaksud sinar" },
  { nama: "Zulhazwan", jantina: "lelaki", bahasa: "Melayu", makna: "Yang memiliki ketegasan", asal: "Gabungan zul dan hazwan" },
  { nama: "Zulhelmi", jantina: "lelaki", bahasa: "Melayu", makna: "Yang memiliki kelembutan", asal: "Gabungan zul dan helmi" },
  { nama: "Zulifqar", jantina: "lelaki", bahasa: "Melayu", makna: "Nama pedang Saidina Ali", asal: "Nama pedang yang terkenal dalam Islam" },
  { nama: "Zulkarnain", jantina: "lelaki", bahasa: "Melayu", makna: "Yang bertanduk dua, raja agung", asal: "Disebutkan dalam Al-Quran" },
  { nama: "Zulkiflee", jantina: "lelaki", bahasa: "Melayu", makna: "Yang mempunyai keistimewaan", asal: "Variasi dari Zulkifli, nama Nabi A.S" },
  { nama: "Zulkifli", jantina: "lelaki", bahasa: "Melayu", makna: "Yang mempunyai keistimewaan", asal: "Nama Nabi Zulkifli A.S" },
  { nama: "Zunaidi", jantina: "lelaki", bahasa: "Melayu", makna: "Yang kuat dan gagah berani", asal: "Dari kata Arab junud bermaksud tentera" },
];
